/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\aapb0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = aapb0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=62;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   aapb1  11                aapb2  12                aapb3  13             
   aapb3a  14               aapb4  15                aapb4a  16            
   aapb5  17                aapb6  18                aapb7  19             
   aapb7a  20               aapb8  21                aapb9  22             
   aapb10  23               aapb11  24               aapb12  25            
   aapb13  26               aapb14  27               aapb14a  28           
   aapb15  29               aapb16  30               aapb17  31            
   aapb18  32               aapb19  33               aapb20  34            
   aapb21  35               aapb22  36               aapb23  37            
   aapb24  38               aapb25  39               aapb26  40            
   aapb27  41               aapb28  42               aapb29  43            
   aapb30  44               aapb30a  45              aapb31  46            
   aapb32  47               aapb32a  48              aapb33 $ 49-51        
   aapb34 DATE11.         ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   aapb1 = "children comfort mother"
   aapb2 = "teach children with physical punishment"
   aapb3 = "children main comfort source for parent"
   aapb3a = "well-behaved child loves mother"
   aapb4 = "young children hug sad mother"
   aapb4a = "ok if child misses school to help family"
   aapb5 = "parents spoil by comforting crying child"
   aapb6 = "children verbally express by age one"
   aapb7 = "good child comforts arguing parents"
   aapb7a = "children 8-10 years left home alone"
   aapb8 = "good behavior learned by physical punish"
   aapb9 = "strong character by strict discipline"
   aapb10 = "children under 3 begin care of self"
   aapb11 = "young children comfort parent after work"
   aapb12 = "parents slap bad child"
   aapb13 = "always spank misbehaving children"
   aapb14 = "children responsible fo parent happiness"
   aapb14a = "family problem talk ok near children <6"
   aapb15 = "parent responsibility to spank bad child"
   aapb16 = "child feed self by 12 months"
   aapb17 = "children grow at same rate physically"
   aapb18 = "secure children expect too much"
   aapb19 = "children always pay for misbehavior"
   aapb20 = "feed, bathe, clothe self at early age"
   aapb21 = "spoil children by being sensitive"
   aapb22 = "children deserve more discipline"
   aapb23 = "unattended children more independent"
   aapb24 = "encouraging communication is bad"
   aapb25 = "learn good behavior when spanked"
   aapb26 = "ignore crying children"
   aapb27 = "5-mnth old sense what parents expect"
   aapb28 = "spoiled kids get too much love"
   aapb29 = "forced respect for parental authority"
   aapb30 = "kids try to make parents^ life better"
   aapb30a = "7-yr old gets own meals"
   aapb31 = "hugged kissed kids grow to sissies"
   aapb32 = "kids comfort upset father"
   aapb32a = "12-yr old discipline young siblings"
   aapb33 = "interviewer initials"
   aapb34 = "date of interview" ;

FORMAT
   aapb34 DATE9. ;
     

LENGTH
   visit 3                  aapb1 3                  aapb2 3               
   aapb3 3                  aapb3a 3                 aapb4 3               
   aapb4a 3                 aapb5 3                  aapb6 3               
   aapb7 3                  aapb7a 3                 aapb8 3               
   aapb9 3                  aapb10 3                 aapb11 3              
   aapb12 3                 aapb13 3                 aapb14 3              
   aapb14a 3                aapb15 3                 aapb16 3              
   aapb17 3                 aapb18 3                 aapb19 3              
   aapb20 3                 aapb21 3                 aapb22 3              
   aapb23 3                 aapb24 3                 aapb25 3              
   aapb26 3                 aapb27 3                 aapb28 3              
   aapb29 3                 aapb30 3                 aapb30a 3             
   aapb31 3                 aapb32 3                 aapb32a 3 ;

       

RUN ;
