/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\acia0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = acia0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=70;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   acia1 $ 11-13            acia2 DATE11.            acia3  25-26          
   acia3a $ 27-51           acia4  52                acia5  53             
   acia5a $ 54-69           acia6  70              ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   acia1 = "interviewer initials"
   acia2 = "date of interview"
   acia3 = "respondent^s relationship to child"
   acia3a = "respondent^s other relationship to child"
   acia4 = "type of interview"
   acia5 = "language of administration"
   acia5a = "respondent^s first language"
   acia6 = "respondent^s level of privacy in intrvw" ;

FORMAT
   acia2 DATE9.           ;
                     

LENGTH
   visit 3                  acia3 3                  acia4 3               
   acia5 3                  acia6 3 ;

         

RUN ;
