/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\acic1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = acic1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=79;
INPUT
   CENTER $ 1-2             ID $ 3-9                 ACIC1 $ 10-12         
   ACIC3B $ 13-24           ACIC3C $ 25-38           ACIC4A $ 39-47        
   ACIC5A $ 48-61           VISIT  62-63             ACIC3  64-65          
   ACIC3A  66               ACIC4  67                ACIC5  68             
   ACIC2 DATE11.          ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   ACIC1 = "Interviewer initials"
   ACIC3B = "Respondent's other relationship to child"
   ACIC3C = "Relationship-desribe"
   ACIC4A = "Respondent's first language"
   ACIC5A = "Description of other interview"
   VISIT = "VISIT NUMBER"
   ACIC3 = "Respondent's relationship to child"
   ACIC3A = "Respondent's other relationship to child"
   ACIC4 = "Language of administration"
   ACIC5 = "Type of interview"
   ACIC2 = "Date of interview" ;

FORMAT
   ACIC2 DATE9. ;
      

LENGTH
   VISIT 3                  ACIC3 3                  ACIC3A 3              
   ACIC4 3                  ACIC5 3 ;

         

RUN ;
