/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\agrb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = agrb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=83;
INPUT
   CENTER $ 1-2             ID $ 3-9                 AGRB14 $ 10           
   AGRB14A $ 11-12          VISIT  13-14             AGRB1  15             
   AGRB2  16                AGRB3  17                AGRB4  18             
   AGRB5  19-20             AGRB6  21                AGRB7  22             
   AGRB8  23                AGRB9  24                AGRB10  25            
   AGRB11  26               AGRB12  27               AGRB13  28            
   AGRB10A  29              AGRB10AYA  30            AGRB10YA  31          
   AGRB11A  32              AGRB12A  33              AGRB13A  34           
   AGRB14AGR  35            AGRB1A  36-38            AGRB1B  39            
   AGRB1C  40               AGRB1D  41               AGRB1E  42            
   AGRB1F  43               AGRB1G  44               AGRB1H  45            
   AGRB1I  46               AGRB2A  47-48            AGRB2B  49            
   AGRB2C  50               AGRB2D  51               AGRB2E  52            
   AGRB2F  53               AGRB2G  54               AGRB2H  55            
   AGRB3A  56               AGRB3B  57               AGRB3C  58            
   AGRB3D  59               AGRB3E  60               AGRB3F  61            
   AGRB3G  62               AGRB3H  63               AGRB4A  64            
   AGRB4B  65               AGRB4C  66               AGRB4D  67            
   AGRB4E  68               AGRB4F  69               AGRB4G  70            
   AGRB4H  71               AGRB5A  72               AGRB5B  73            
   AGRB5C  74               AGRB5D  75-76            AGRB5DGR  77          
   AGRB5E  78               AGRB5GR  79              AGRB6A  80            
   AGRB7A  81               AGRB8A  82               AGRB9A  83            
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   AGRB14 = "Whole life:ever felt much more nervous"
   AGRB14A = "How old-when u felt much more nervous"
   VISIT = "VISIT NUMBER"
   AGRB1 = "Last yr:often been afraid of travelling"
   AGRB2 = "Last yr:afraid of bridges/tunnels"
   AGRB3 = "Last yr:scared of crowded places"
   AGRB4 = "Last yr:afraid to go out by yourself"
   AGRB5 = "How old when you 1st time u felt afraid"
   AGRB6 = "Most prblm/scared:family/friends annoyed"
   AGRB7 = "Fear keep you from things with family"
   AGRB8 = "Fear keep you from things with other"
   AGRB9 = "Worst prblms/scared:schl/work difficult"
   AGRB10 = "Being scared:teacher/boss upset with you"
   AGRB11 = "Worst prblms/scared: make you feel bad"
   AGRB12 = "Seen someone in hospital in last year"
   AGRB13 = "Who did you see/ are going to see"
   AGRB10A = "How often:teacher/boss upset with you"
   AGRB10AYA = "How bad were prblms with doing things"
   AGRB10YA = "Worst prblms/scared make self care hard"
   AGRB11A = "How bad scared: make you feel bad"
   AGRB12A = "Have appointment re: being overactive"
   AGRB13A = "What person you saw say the matter was"
   AGRB14AGR = "Grade-when u felt much more nervous"
   AGRB1A = "Which have you been afraid of"
   AGRB1B = "Scared/travel 'cause-sudden attak/afraid"
   AGRB1C = "Afraid because-might get trapped"
   AGRB1D = "Afraid that other people will notice"
   AGRB1E = "Time most afraid:try to keep from going"
   AGRB1F = "Time most afraid/go:feel nervous/upset"
   AGRB1G = "Somebody with you-feel less scared"
   AGRB1H = "Afraid/travel because people look at you"
   AGRB1I = "Last 4wks:often afraid of travelling"
   AGRB2A = "Which have you been afraid of"
   AGRB2B = "Scared because-sudden attack/afraid"
   AGRB2C = "Scared because u might get trapped"
   AGRB2D = "Afraid that other people will notice"
   AGRB2E = "Most afrd:refuse to go on bridges/tunnel"
   AGRB2F = "Time most afraid/go:feel nervous/upset"
   AGRB2G = "Somebody with you-feel less scared"
   AGRB2H = "Last 4wks:often afraid of bridges/tunnel"
   AGRB3A = "Which have you been afraid of"
   AGRB3B = "Scared because-sudden attack/afraid"
   AGRB3C = "Scared because u might not get out"
   AGRB3D = "Most afraid/in crowd:feel nervous/upset"
   AGRB3E = "Most afrd:avoid crowded places"
   AGRB3F = "Somebody with you-feel less scared"
   AGRB3G = "Afraid that other people will notice"
   AGRB3H = "Last 4wks:often afraid/crowded places"
   AGRB4A = "Scared because-sudden attack/afraid"
   AGRB4B = "Scared because u might not get help"
   AGRB4C = "Afraid that other people will notice"
   AGRB4D = "Most afraid/tried to go by yourself"
   AGRB4E = "Most afraid/ gou out:feel nervous/upset"
   AGRB4F = "Somebody with you-feel less nervous"
   AGRB4G = "Not want to leave 'cause closest person"
   AGRB4H = "Last 4wks:often afraid of going out"
   AGRB5A = "Was 1st time afraid >a yr ago"
   AGRB5B = "Ever a time when you were not afraid"
   AGRB5C = "Time not afraid last for 2>2 mths"
   AGRB5D = "Last yr:how old when feelings began"
   AGRB5DGR = "Last yr:grade when feelings began"
   AGRB5E = "Did you start feeling afraid >a yr ago"
   AGRB5GR = "Grade when you felt afraid"
   AGRB6A = "Sacred-how often family/friends annoyed"
   AGRB7A = "Often fear keep you from things-family"
   AGRB8A = "Often fear keep you from things-other"
   AGRB9A = "How bad prblms with school/work" ;

LENGTH
   VISIT 3                  AGRB1 3                  AGRB2 3               
   AGRB3 3                  AGRB4 3                  AGRB5 3               
   AGRB6 3                  AGRB7 3                  AGRB8 3               
   AGRB9 3                  AGRB10 3                 AGRB11 3              
   AGRB12 3                 AGRB13 3                 AGRB10A 3             
   AGRB10AYA 3              AGRB10YA 3               AGRB11A 3             
   AGRB12A 3                AGRB13A 3                AGRB14AGR 3           
   AGRB1A 4                 AGRB1B 3                 AGRB1C 3              
   AGRB1D 3                 AGRB1E 3                 AGRB1F 3              
   AGRB1G 3                 AGRB1H 3                 AGRB1I 3              
   AGRB2A 3                 AGRB2B 3                 AGRB2C 3              
   AGRB2D 3                 AGRB2E 3                 AGRB2F 3              
   AGRB2G 3                 AGRB2H 3                 AGRB3A 3              
   AGRB3B 3                 AGRB3C 3                 AGRB3D 3              
   AGRB3E 3                 AGRB3F 3                 AGRB3G 3              
   AGRB3H 3                 AGRB4A 3                 AGRB4B 3              
   AGRB4C 3                 AGRB4D 3                 AGRB4E 3              
   AGRB4F 3                 AGRB4G 3                 AGRB4H 3              
   AGRB5A 3                 AGRB5B 3                 AGRB5C 3              
   AGRB5D 3                 AGRB5DGR 3               AGRB5E 3              
   AGRB5GR 3                AGRB6A 3                 AGRB7A 3              
   AGRB8A 3                 AGRB9A 3 ;

        

RUN ;
