/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\agrs1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = agrs1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=23;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   YAG001  12               YAG002  13               YAG003  14            
   YAG004  15               YAG1AM  16               YAG1BY  17            
   YAG1BM  18               YAGY  19                 YAGM  20              
   YAGCRITY  21             YAGCRITM  22             YAGSYMP  23           
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   YAG001 = "Last yr:often been afraid of travelling"
   YAG002 = "Last yr:afraid of bridges/tunnels"
   YAG003 = "Last yr:scared of crowded places"
   YAG004 = "Last yr:afraid to go out by yourself"
   YAG1AM = "Anxiety where escape difficult or help not available"
   YAG1BY = "Situations are avoided"
   YAG1BM = "Situations are avoided"
   YAGY = "Year: diagnosis for agoraphobia"
   YAGM = "Month: diagnosis for agoraphobia"
   YAGCRITY = "Youth Agoraphobia Criteria Count - Last Year"
   YAGCRITM = "Youth Agoraphobia Criteria Count - Last Month"
   YAGSYMP = "Youth Agoraphobia Symptom Count" ;

LENGTH
   VISIT 3                  YAG001 3                 YAG002 3              
   YAG003 3                 YAG004 3                 YAG1AM 3              
   YAG1BY 3                 YAG1BM 3                 YAGY 3                
   YAGM 3                   YAGCRITY 3               YAGCRITM 3            
   YAGSYMP 3 ;

       

RUN ;
