/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ampa1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ampa1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=61;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   AMPA1A  12               AMPA1B  13               AMPA2A  14            
   AMPA2B  15               AMPA3A  16               AMPA3B  17            
   AMPA4A  18               AMPA4B  19               AMPA5A  20            
   AMPA5B  21               AMPA6A  22               AMPA6B  23            
   AMPA7A  24               AMPA7B  25               AMPA8A  26            
   AMPA8B  27               AMPA9A  28               AMPA9B  29            
   AMPA10A  30              AMPA10B  31              AMPA11A  32           
   AMPA11B  33              AMPA12A  34              AMPA12B  35           
   AMPA13A  36              AMPA13B  37              AMPA14A  38           
   AMPA14B  39              AMPA15A  40              AMPA15B  41           
   AMPA16A  42              AMPA16B  43              AMPA17A  44           
   AMPA17B  45              AMPA18A  46              AMPA18B  47           
   AMPA19A  48              AMPA19B  49              AMPA20A  50           
   AMPA20B  51              AMPA21A  52              AMPA21B  53           
   AMPA22A  54              AMPA22B  55              AMPA23A  56           
   AMPA23B  57              AMPA24A  58              AMPA24B  59           
   AMPA25A  60              AMPA25B  61            ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   AMPA1A = "ElemSch/parents did things w/you for fun"
   AMPA1B = "LastYr/parents did things w/you for fun"
   AMPA2A = "ElemSch/parents interested in activities"
   AMPA2B = "LastYr/parents interested in activities"
   AMPA3A = "ElemSch/parents helped with homework"
   AMPA3B = "LastYr/parents helped with homework"
   AMPA4A = "ElemSch/parents asked what doing if out"
   AMPA4B = "LastYr/parents asked what doing if out"
   AMPA5A = "ElemSch/parents comforted you if upset"
   AMPA5B = "LastYr/parents comforted you if upset"
   AMPA6A = "ElemSch/parents made sure you bathed"
   AMPA6B = "LastYr/parents made sure you bathed"
   AMPA7A = "ElemSch/parents helped you do your best"
   AMPA7B = "LastYr/parents helped you do your best"
   AMPA8A = "ElemSch/parents made sure went to school"
   AMPA8B = "LastYr/parents made sure went to school"
   AMPA9A = "ElemSch/parents cared in trouble at schl"
   AMPA9B = "LastYr/parents cared in trouble at schl"
   AMPA10A = "ElemSch/parents made sure you saw doctor"
   AMPA10B = "LastYr/parents made sure you saw doctor"
   AMPA11A = "ElemSch/parents interested in friends"
   AMPA11B = "LastYr/parents interested in friends"
   AMPA12A = "ElemSch/parents gave you enough to eat"
   AMPA12B = "LastYr/parents gave you enough to eat"
   AMPA13A = "ElemSch/parents helped you understand"
   AMPA13B = "LastYr/parents helped you understand"
   AMPA14A = "ElemSch/parents read books to you"
   AMPA14B = "LastYr/parents read books to you"
   AMPA15A = "ElemSch/parents helped when had problems"
   AMPA15B = "LastYr/parents helped when had problems"
   AMPA16A = "ElemSch/parents praised you"
   AMPA16B = "LastYr/parents praised you"
   AMPA17A = "ElemSch/parents cared if did bad things"
   AMPA17B = "LastYr/parents cared if did bad things"
   AMPA18A = "ElemSch/parents told you they loved you"
   AMPA18B = "LastYr/parents told you they loved you"
   AMPA19A = "ElemSch/parents kept the house clean"
   AMPA19B = "LastYr/parents kept the house clean"
   AMPA20A = "ElemSch/parents gave enough clothes"
   AMPA20B = "LastYr/parents gave enough clothes"
   AMPA21A = "ElemSch/parents took care when sick"
   AMPA21B = "LastYr/parents took care when sick"
   AMPA22A = "ElemSch/parents had food when hungry"
   AMPA22B = "LastYr/parents had food when hungry"
   AMPA23A = "ElemSch/parents provided safe play place"
   AMPA23B = "LastYr/parents provided safe play place"
   AMPA24A = "ElemSch/parents left home alone at night"
   AMPA24B = "LastYr/parents left home alone at night"
   AMPA25A = "ElemSch/parents left home alone in day"
   AMPA25B = "LastYr/parents left home alone in day" ;

LENGTH
   VISIT 3                  AMPA1A 3                 AMPA1B 3              
   AMPA2A 3                 AMPA2B 3                 AMPA3A 3              
   AMPA3B 3                 AMPA4A 3                 AMPA4B 3              
   AMPA5A 3                 AMPA5B 3                 AMPA6A 3              
   AMPA6B 3                 AMPA7A 3                 AMPA7B 3              
   AMPA8A 3                 AMPA8B 3                 AMPA9A 3              
   AMPA9B 3                 AMPA10A 3                AMPA10B 3             
   AMPA11A 3                AMPA11B 3                AMPA12A 3             
   AMPA12B 3                AMPA13A 3                AMPA13B 3             
   AMPA14A 3                AMPA14B 3                AMPA15A 3             
   AMPA15B 3                AMPA16A 3                AMPA16B 3             
   AMPA17A 3                AMPA17B 3                AMPA18A 3             
   AMPA18B 3                AMPA19A 3                AMPA19B 3             
   AMPA20A 3                AMPA20B 3                AMPA21A 3             
   AMPA21B 3                AMPA22A 3                AMPA22B 3             
   AMPA23A 3                AMPA23B 3                AMPA24A 3             
   AMPA24B 3                AMPA25A 3                AMPA25B 3 ;

       

RUN ;
