/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\apia1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = apia1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=49;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   APIA1  12                APIA2  13                APIA3  14             
   APIA4  15                APIA5  16                APIA6  17             
   APIA7  18                APIA8  19                APIA9  20             
   APIA10  21               APIA11  22               APIA12  23            
   APIA13  24               APIA14  25               APIA15  26            
   APIA16  27               APIA17  28               APIA18  29            
   APIA19  30               APIA20  31               APIA21  32            
   APIA22  33               APIA23  34               APIA24  35            
   APIA25  36               APIA26  37               APIA27  38            
   APIA28  39               APIA29  40               APIA30  41            
   APIA31  42               APIA32  43               APIA14A  44           
   APIA30A  45              APIA32A  46              APIA3A  47            
   APIA4A  48               APIA7A  49             ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   APIA1 = "Young children should comfort mother"
   APIA2 = "Parents-teach childrn/use phys.punishmnt"
   APIA3 = "Children-the main source of comfort/care"
   APIA4 = "Young children-hug their mother"
   APIA5 = "Parents spoil childrn by picking them up"
   APIA6 = "Children-verbally express before 1 yr"
   APIA7 = "Good chld-comfort parnts aftr they argue"
   APIA8 = "Child learn good behavior-phys.punishmnt"
   APIA9 = "Childrn/strong charcter-strict disciplin"
   APIA10 = "Parents-children < 3/begin self care"
   APIA11 = "Young child.-ways/comfort prnts aftr wrk"
   APIA12 = "Parents slap child when s/he done wrong"
   APIA13 = "Children-spanked when they misbehave"
   APIA14 = "Young child.-responsible/parnt happiness"
   APIA15 = "Parents resp.-spank child-s/he misbehave"
   APIA16 = "Parnts-expect child-feed selves-12 mths"
   APIA17 = "Parnts-expect child.-phys.grow/same rate"
   APIA18 = "Young chldrn/feel secure/expect too much"
   APIA19 = "Children always pay the price-misbehaving"
   APIA20 = "Children expect to feed etc.-early age"
   APIA21 = "Prnts senstive/child.feelings-spoil them"
   APIA22 = "Children deserve more discipline"
   APIA23 = "Chldrn/unattended needs-grow independent"
   APIA24 = "Parnts/comunication-listen to complaints"
   APIA25 = "Chldrn learn approp.behavior whn spanked"
   APIA26 = "Children-quit crying faster if ignored"
   APIA27 = "Chldrn 5 mths-sense what parents expect"
   APIA28 = "Children/too much parents love-spoiled"
   APIA29 = "Children-forced/respect parent authority"
   APIA30 = "Yung chldrn-make parent life pleasurable"
   APIA31 = "Young children/huggged/kised-sissies"
   APIA32 = "Young children-comfort father when upset"
   APIA14A = "Talking prblm in front young child.-OK"
   APIA30A = "7 yr old-old enough to get his/her meals"
   APIA32A = "Older daughtr-disciplin youngr bro/sis."
   APIA3A = "Child loves mother-will be well behaved"
   APIA4A = "OK-child to stay home from school"
   APIA7A = "Prnts work night-oldr chldren/respons'ty" ;

LENGTH
   VISIT 3                  APIA1 3                  APIA2 3               
   APIA3 3                  APIA4 3                  APIA5 3               
   APIA6 3                  APIA7 3                  APIA8 3               
   APIA9 3                  APIA10 3                 APIA11 3              
   APIA12 3                 APIA13 3                 APIA14 3              
   APIA15 3                 APIA16 3                 APIA17 3              
   APIA18 3                 APIA19 3                 APIA20 3              
   APIA21 3                 APIA22 3                 APIA23 3              
   APIA24 3                 APIA25 3                 APIA26 3              
   APIA27 3                 APIA28 3                 APIA29 3              
   APIA30 3                 APIA31 3                 APIA32 3              
   APIA14A 3                APIA30A 3                APIA32A 3             
   APIA3A 3                 APIA4A 3                 APIA7A 3 ;

        

RUN ;
