/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\asea0807.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = asea0807 ;

DATA library.&dataset ;
INFILE datafile LRECL=33;
INPUT
   ID $ 1-7                 CENTER $ 8-9             VISIT  10-11          
   ASEA1  12                ASEA2  13                ASEA3A  14            
   ASEA3B  15               ASEA4A  16               ASEA4B  17            
   ASEA4C  18               ASEA4D  19               ASEA4E  20            
   ASEA5A  21               ASEA5B  22               ASEA6  23             
   ASEA7  24                ASEA8  25                ASEA9  26             
   ASEA10  27               ASEA11A  28              ASEA12A  29           
   ASEA11B  30              ASEA12B  31              ASEA13  32            
   ASEA14  33             ;                       

LABEL
   ID = "LONGSCAN SUBJECT ID"
   CENTER = "FIELD CENTER"
   VISIT = "VISIT NUMBER"
   ASEA1 = "Have you ever had sex"
   ASEA2 = "How old first time you had sex"
   ASEA3A = "Girls/How many boys/men had sex with"
   ASEA3B = "Boys/How many girls/women had sex with"
   ASEA4A = "Protection last time had sex/nothing"
   ASEA4B = "Protection last time had sex/condom"
   ASEA4C = "Protection last time had sex/pill"
   ASEA4D = "Protection last time had sex/withdrawal"
   ASEA4E = "Protection last time had sex/other"
   ASEA5A = "Girls/Have you ever been pregnant"
   ASEA5B = "Boys/Have you gotten someone pregnant"
   ASEA6 = "Do you have any children"
   ASEA7 = "How many children do you have"
   ASEA8 = "How likely have sex during next 6 months"
   ASEA9 = "Could keep from having sex if wanted to"
   ASEA10 = "What friends think of sex at your age"
   ASEA11A = "Girls/How happy if you got pregnant now"
   ASEA12A = "Girls/Like to get pregnant in next year"
   ASEA11B = "Boys/Happy if got someone pregnant now"
   ASEA12B = "Boys/Like to get someone preg in next yr"
   ASEA13 = "Friends believe important to use condoms"
   ASEA14 = "How many friends having sex use condoms" ;

LENGTH
   VISIT 3                  ASEA1 3                  ASEA2 3               
   ASEA3A 3                 ASEA3B 3                 ASEA4A 3              
   ASEA4B 3                 ASEA4C 3                 ASEA4D 3              
   ASEA4E 3                 ASEA5A 3                 ASEA5B 3              
   ASEA6 3                  ASEA7 3                  ASEA8 3               
   ASEA9 3                  ASEA10 3                 ASEA11A 3             
   ASEA12A 3                ASEA11B 3                ASEA12B 3             
   ASEA13 3                 ASEA14 3 ;

        

RUN ;
