/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\badm1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = badm1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=48;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   BADA1AM  12              BADA1BM  13              BADA1CM  14           
   BADA1DM  15              BADA1EM  16              BADA1FM  17           
   BADA1GM  18              BADA1HM  19              BADA1IM  20           
   BADA2AM  21              BADA2BM  22              BADA2CM  23           
   BADA2DM  24              BADA2EM  25              BADA2FM  26           
   BADA2GM  27              BADA2HM  28              BADA2IM  29           
   BADA1M  30               BADA2M  31               BADAM  32             
   BADB1  33                BADB2  34                BADB  35              
   BADC1M  36               BADC2M  37               BADCM  38             
   BAD1M  39                BAD2M  40                BAD3M  41             
   BADM  42                 BADCRT1M  43             BADCRT2M  44          
   BADSYMP  45-48         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   BADA1AM = "Fails to give close attention"
   BADA1BM = "Difficulty sustaining attention"
   BADA1CM = "Does not listen"
   BADA1DM = "Fails to follow through on instructions"
   BADA1EM = "Difficulty organizing tasks"
   BADA1FM = "Avoids, dislikes tasks that require sustained attention"
   BADA1GM = "Loses things"
   BADA1HM = "Easily distracted by extraneous stimuli"
   BADA1IM = "Forgetful"
   BADA2AM = "Fidgets"
   BADA2BM = "Leaves seat"
   BADA2CM = "Runs about or climbs excessively"
   BADA2DM = "Difficulty playing quietly"
   BADA2EM = "Often on the go/driven by a motor"
   BADA2FM = "Talks excessively"
   BADA2GM = "Blurts out answers"
   BADA2HM = "Difficulty awaiting turn"
   BADA2IM = "Interrupts or intrudes"
   BADA1M = "Inattention"
   BADA2M = "Hyperactivity-impulsivity"
   BADCM = "Impairment in two or more settings"
   BAD1M = "Inattention type"
   BAD2M = "Hyperactive type"
   BAD3M = "Combined type"
   BADM = "ADHD diagnosis"
   BADCRT1M = "Parent ADHD type 1-inatten Criteria Count - Past Month"
   BADCRT2M = "Parent ADHD type 2-hyp-impul Criteria Count - Past Month"
   BADSYMP = "Parent ADHD Symptom Count" ;

LENGTH
   VISIT 3                  BADA1AM 3                BADA1BM 3             
   BADA1CM 3                BADA1DM 3                BADA1EM 3             
   BADA1FM 3                BADA1GM 3                BADA1HM 3             
   BADA1IM 3                BADA2AM 3                BADA2BM 3             
   BADA2CM 3                BADA2DM 3                BADA2EM 3             
   BADA2FM 3                BADA2GM 3                BADA2HM 3             
   BADA2IM 3                BADA1M 3                 BADA2M 3              
   BADAM 3                  BADB1 3                  BADB2 3               
   BADB 3                   BADC1M 3                 BADC2M 3              
   BADCM 3                  BAD1M 3                  BAD2M 3               
   BAD3M 3                  BADM 3                   BADCRT1M 3            
   BADCRT2M 3 ;

      

RUN ;
