/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\bcdm1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = bcdm1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=51;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   BCDA1Y  12               BCDA1M  13               BCDA2Y  14            
   BCDA2M  15               BCDA3Y  16               BCDA3M  17            
   BCDA4Y  18               BCDA4M  19               BCDA5Y  20            
   BCDA5M  21               BCDA6Y  22               BCDA6M  23            
   BCDA7Y  24               BCDA7M  25               BCDA8Y  26            
   BCDA8M  27               BCDA9Y  28               BCDA9M  29            
   BCDA10Y  30              BCDA10M  31              BCDA11Y  32           
   BCDA11M  33              BCDA12Y  34              BCDA12M  35           
   BCDA13Y  36              BCDA13M  37              BCDA14Y  38           
   BCDA14M  39              BCDA15Y  40              BCDA15M  41           
   BCDAY  42                BCDAM  43                BCDY  44              
   BCDM  45                 BCDCRITY  46             BCDCRITM  47          
   BCDSYMP  48-51         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   BCDA1Y = "Past year: bullies, threatens, others"
   BCDA1M = "Past 6 months: bullies, threatens, others"
   BCDA2Y = "Past year: initiates physical fights"
   BCDA2M = "Past 6 months: initiates physical fights"
   BCDA3Y = "Past year: used a weapon"
   BCDA3M = "Past 6 months: used a weapon"
   BCDA4Y = "Past year: physically cruel to people"
   BCDA4M = "Past 6 months: physically cruel to people"
   BCDA5Y = "Past year: physically cruel to animals"
   BCDA5M = "Past 6 months: physically cruel to animals"
   BCDA6Y = "Past year: stolen with confrontation"
   BCDA6M = "Past 6 months: stolen with confrontation"
   BCDA7Y = "Past year: forced sex"
   BCDA7M = "Past 6 months: forced sex"
   BCDA8Y = "Past year: fire setting"
   BCDA8M = "Past 6 months: fire setting"
   BCDA9Y = "Past year: destroyed property"
   BCDA9M = "Past 6 months: destroyed property"
   BCDA10Y = "Past year: broken into house, building or car"
   BCDA10M = "Past 6 months: broken into house, building or car"
   BCDA11Y = "Past year: lies to obtain goods or favors, avoid obligations"
   BCDA11M = "Past 6 months: lies to obtain goods or favors, avoid obligations"
   BCDA12Y = "Past year: stolen without confrontation"
   BCDA12M = "Past 6 months: stolen without confrontation"
   BCDA13Y = "Past year: stays out late"
   BCDA13M = "Past 6 months: stays out late"
   BCDA14Y = "Past year: run away from home"
   BCDA14M = "Past 6 months: run away from home"
   BCDA15Y = "Past year: truant"
   BCDA15M = "Past 6 months: truant"
   BCDAY = "Past year: repetitive and persistent pattern of behavior"
   BCDAM = "Past 6 months: repetitive and persistent pattern of behavior"
   BCDY = "Past year: diagnosis for conduct disorder"
   BCDM = "Past month: diagnosis for conduct disorder"
   BCDCRITY = "Criterion Count for CD - past year"
   BCDCRITM = "Criterion Count for CD - past 6 months"
   BCDSYMP = "Symptom Count for Conduct Disorder - Comb" ;

LENGTH
   VISIT 3                  BCDA1Y 3                 BCDA1M 3              
   BCDA2Y 3                 BCDA2M 3                 BCDA3Y 3              
   BCDA3M 3                 BCDA4Y 3                 BCDA4M 3              
   BCDA5Y 3                 BCDA5M 3                 BCDA6Y 3              
   BCDA6M 3                 BCDA7Y 3                 BCDA7M 3              
   BCDA8Y 3                 BCDA8M 3                 BCDA9Y 3              
   BCDA9M 3                 BCDA10Y 3                BCDA10M 3             
   BCDA11Y 3                BCDA11M 3                BCDA12Y 3             
   BCDA12M 3                BCDA13Y 3                BCDA13M 3             
   BCDA14Y 3                BCDA14M 3                BCDA15Y 3             
   BCDA15M 3                BCDAY 3                  BCDAM 3               
   BCDY 3                   BCDM 3                   BCDCRITY 3            
   BCDCRITM 3 ;

      

RUN ;
