/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\bk6a0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = bk6a0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=119;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   bk6a1 DATE11.            bk6a2  22                bk6a3  23             
   bk6a3a $ 24-43           bk6a4  44                bk6a4a $ 45-61        
   bk6a5  62                bk6a5a  63               bk6a5b $ 64-83        
   bk6a6  84                bk6a7  85                bk6a7a $ 86-105       
   bk6a8 $ 106-108          bk6a9 DATE11.          ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   bk6a1 = "child^s date of birth"
   bk6a2 = "child^s sex"
   bk6a3 = "child^s racial-ethnic group"
   bk6a3a = "other racial-ethnic group"
   bk6a4 = "child^s first language"
   bk6a4a = "other language"
   bk6a5 = "does child have a second language"
   bk6a5a = "child^s second language"
   bk6a5b = "other second language"
   bk6a6 = "child^s position in family"
   bk6a7 = "person who makes decisions re: child"
   bk6a7a = "other person makes decisions re:child"
   bk6a8 = "interviewer initials"
   bk6a9 = "date of interview" ;

FORMAT
   bk6a1 DATE9.             bk6a9 DATE9. ;
      

LENGTH
   visit 3                  bk6a2 3                  bk6a3 3               
   bk6a4 3                  bk6a5 3                  bk6a5a 3              
   bk6a6 3                  bk6a7 3 ;

         

RUN ;
