/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\bsta0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = bsta0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=131;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   bsta0 DATE11.            bsta1  22                bsta2  23             
   bsta3  24                bsta4  25                bsta5  26             
   bsta6  27                bsta7  28                bsta8  29             
   bsta9  30                bsta10  31               bsta11  32            
   bsta12  33               bsta13  34               bsta14  35            
   bsta15  36               bsta16  37               bsta17  38            
   bsta18  39               bsta19  40               bsta20  41            
   bsta21  42               bsta22  43               bsta23  44            
   bsta24  45               bsta25  46               bsta26  47            
   bsta27  48               bsta28  49               bsta29  50            
   bsta30  51               bsta31  52               bsta32  53            
   bsta33  54               bsta34  55               bsta35  56            
   bsta36  57               bsta37  58               bsta38  59            
   bsta39  60               bsta40  61               bsta41  62            
   bsta42  63               bsta43  64               bsta44  65            
   bsta45  66               bsta46  67               bsta47  68            
   bsta48  69               bsta49  70               bsta50  71            
   bsta51  72               bsta52  73               bsta53  74            
   bsta54  75               bsta55  76               bsta56  77            
   bsta57  78               bsta58  79               bsta59  80            
   bsta60  81               bsta61  82               bsta62  83            
   bsta63  84               bsta64  85               bsta65  86            
   bsta66  87               bsta67  88               bsta68  89            
   bsta69  90               bsta70  91               bsta71  92            
   bsta72  93               bsta73  94               bsta74  95            
   bsta75  96               bsta76  97               bsta77  98            
   bsta78  99               bsta79  100              bsta80  101           
   bsta81  102              bsta82  103              bsta83  104           
   bsta84  105              bsta85  106              bsta86  107           
   bsta87  108              bsta88  109              bsta89  110           
   bsta90  111              bsta91  112              bsta92  113           
   bsta93  114              bsta94  115              bsta95  116           
   bsta96  117              bsta97 $ 118-120         bsta98 DATE11.        
 ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   bsta0 = "date of battelle administration"
   bsta1 = "awareness of hands"
   bsta2 = "desire to be picked up or held"
   bsta3 = "plays peekaboo"
   bsta4 = "responds to name"
   bsta5 = "initiates peer contact in play"
   bsta6 = "imitates other children at play"
   bsta7 = "follows daily routine directions"
   bsta8 = "plays alone around peers"
   bsta9 = "knows first name"
   bsta10 = "pronoun-name use for self"
   bsta11 = "aware of male and female"
   bsta12 = "responds to social contact"
   bsta13 = "describes feelings"
   bsta14 = "chooses own friends"
   bsta15 = "competitive play activities"
   bsta16 = "knows socially acceptable-nonacceptable"
   bsta17 = "leader in peer relationships"
   bsta18 = "asks for adult help"
   bsta19 = "uses adult help in peer problems"
   bsta20 = "admits responsibility"
   bsta21 = "swallows food from spoon"
   bsta22 = "attends to sound-activity 15+ sec."
   bsta23 = "holds-supports bottle to feed self"
   bsta24 = "feeds self bite-size pieces"
   bsta25 = "use utensil to feed self"
   bsta26 = "removes small clothing item"
   bsta27 = "knows food-nonfood items"
   bsta28 = "removes simple garment"
   bsta29 = "expresses need for bathroom"
   bsta30 = "gets drink by self"
   bsta31 = "can do 1-2 buttons"
   bsta32 = "sleeps all night without bedwetting"
   bsta33 = "dresses-undresses alone"
   bsta34 = "completes tasks with 2+ steps"
   bsta35 = "goes to school, etc. unattended"
   bsta36 = "answers what-do-i-do-if? questions"
   bsta37 = "knows address"
   bsta38 = "proper use of phone-operator"
   bsta39 = "handles own money"
   bsta40 = "performs household chores"
   bsta41 = "hand to mouth movement"
   bsta42 = "reaches for-touches objects"
   bsta43 = "crawls 3+ feet"
   bsta44 = "partial finger prehension"
   bsta45 = "up 4+ steps with support"
   bsta46 = "neat pincer grasp"
   bsta47 = "up and down stairs alone"
   bsta48 = "places 4 rings on post"
   bsta49 = "jumps forward, feet together"
   bsta50 = "turns knob to open door"
   bsta51 = "uses scissors to cut paper"
   bsta52 = "folds paper twice"
   bsta53 = "one foot hop for 10 feet"
   bsta54 = "copies triangle"
   bsta55 = "stands on each foot alt."
   bsta56 = "copies numbers 1 to 5"
   bsta57 = "heel-toe walking 6 ft. line"
   bsta58 = "copies upper-lower case letters in words"
   bsta59 = "jumps rope alone"
   bsta60 = "copies 2 tilted triangles"
   bsta61 = "turns head toward unseen sound source"
   bsta62 = "makes sounds to express feelings"
   bsta63 = "associates spoken words with things"
   bsta64 = "single-syllable consonant-vowel sounds"
   bsta65 = "responds to simultaneous words-gestures"
   bsta66 = "uses 10 or more words"
   bsta67 = "responds to prepositions"
   bsta68 = "uses pronouns"
   bsta69 = "follows 2 step verbal commands"
   bsta70 = "uses plural forms ending w s or z sound"
   bsta71 = "understands regular plural forms"
   bsta72 = "uses 5 or 6 word sentences"
   bsta73 = "understands future tense of to be"
   bsta74 = "uses regular comparative forms"
   bsta75 = "knows active and passive voices"
   bsta76 = "talks about things that might be"
   bsta77 = "knows bright, hard, sweet   people"
   bsta78 = "uses passive voice"
   bsta79 = "follows visual stimulus"
   bsta80 = "feels-explores objects"
   bsta81 = "uncovers hidden toy"
   bsta82 = "searches for removed object"
   bsta83 = "reaches around barrier"
   bsta84 = "recognizes self as cause of events"
   bsta85 = "matches circle, square, triangle"
   bsta86 = "repeats two digit sequences"
   bsta87 = "identifies big and small shapes"
   bsta88 = "identifies simple objects by touch"
   bsta89 = "answers simple logic questions"
   bsta90 = "completes opposite analogies"
   bsta91 = "identifies colors of familiar objects"
   bsta92 = "identifies first-last objects in row"
   bsta93 = "recalls facts from oral story"
   bsta94 = "simple add-minus problems"
   bsta95 = "word problems involving subtraction"
   bsta96 = "simple multiplication problems"
   bsta97 = "interviewer initials"
   bsta98 = "date of interview" ;

FORMAT
   bsta0 DATE9.             bsta98 DATE9. ;
     

LENGTH
   visit 3                  bsta1 3                  bsta2 3               
   bsta3 3                  bsta4 3                  bsta5 3               
   bsta6 3                  bsta7 3                  bsta8 3               
   bsta9 3                  bsta10 3                 bsta11 3              
   bsta12 3                 bsta13 3                 bsta14 3              
   bsta15 3                 bsta16 3                 bsta17 3              
   bsta18 3                 bsta19 3                 bsta20 3              
   bsta21 3                 bsta22 3                 bsta23 3              
   bsta24 3                 bsta25 3                 bsta26 3              
   bsta27 3                 bsta28 3                 bsta29 3              
   bsta30 3                 bsta31 3                 bsta32 3              
   bsta33 3                 bsta34 3                 bsta35 3              
   bsta36 3                 bsta37 3                 bsta38 3              
   bsta39 3                 bsta40 3                 bsta41 3              
   bsta42 3                 bsta43 3                 bsta44 3              
   bsta45 3                 bsta46 3                 bsta47 3              
   bsta48 3                 bsta49 3                 bsta50 3              
   bsta51 3                 bsta52 3                 bsta53 3              
   bsta54 3                 bsta55 3                 bsta56 3              
   bsta57 3                 bsta58 3                 bsta59 3              
   bsta60 3                 bsta61 3                 bsta62 3              
   bsta63 3                 bsta64 3                 bsta65 3              
   bsta66 3                 bsta67 3                 bsta68 3              
   bsta69 3                 bsta70 3                 bsta71 3              
   bsta72 3                 bsta73 3                 bsta74 3              
   bsta75 3                 bsta76 3                 bsta77 3              
   bsta78 3                 bsta79 3                 bsta80 3              
   bsta81 3                 bsta82 3                 bsta83 3              
   bsta84 3                 bsta85 3                 bsta86 3              
   bsta87 3                 bsta88 3                 bsta89 3              
   bsta90 3                 bsta91 3                 bsta92 3              
   bsta93 3                 bsta94 3                 bsta95 3              
   bsta96 3 ;

        

RUN ;
