/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\cda0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = cda0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=29;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   cda1  11                 cda2  12                 cda3  13              
   cda4  14                 cda5  15                 cda6 $ 16-18          
   cda7 DATE11.           ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   cda1 = "child's health compared to other chldrn"
   cda2 = "how well child plays with others"
   cda3 = "how quickly child learns new things"
   cda4 = "how well child expresses with words"
   cda5 = "happiness of child this year"
   cda6 = "interviewer initials"
   cda7 = "date of interview" ;

FORMAT
   cda7 DATE9. ;
       

LENGTH
   visit 3                  cda1 3                   cda2 3                
   cda3 3                   cda4 3                   cda5 3 ;

          

RUN ;
