/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ch6a0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ch6a0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=325;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   ch6a1  11                ch6a2a1  12              ch6a2a2 $ 13-42       
   ch6a2b1  43              ch6a2b2 $ 44-73          ch6a2c1  74           
   ch6a2c2 $ 75-104         ch6a2d1  105             ch6a2d2 $ 106-135     
   ch6a2e1  136             ch6a2e2 $ 137-166        ch6a2f1  167          
   ch6a2f2 $ 168-197        ch6a2g1  198             ch6a2g2 $ 199-228     
   ch6a2h1  229             ch6a2h2 $ 230-259        ch6a2i1  260          
   ch6a2i2 $ 261-290        ch6a3  291               ch6a3a $ 292-311      
   ch6a4 $ 312-314          ch6a5 DATE11.          ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   ch6a1 = "child^s health"
   ch6a2a1 = "child:  hearing problem"
   ch6a2a2 = "descript: hearing problem"
   ch6a2b1 = "child:  speech-talking problem"
   ch6a2b2 = "descript: speech-talking problem"
   ch6a2c1 = "child:  vision-seeing problem"
   ch6a2c2 = "descript: vision-seeing problem"
   ch6a2d1 = "child:  chronic illness"
   ch6a2d2 = "descript: chronic illness"
   ch6a2e1 = "child:  physical handicap"
   ch6a2e2 = "descript: physical handicap"
   ch6a2f1 = "child:  hyperactivity-attention problem"
   ch6a2f2 = "descript: hyperactivity-att. problem"
   ch6a2g1 = "child:  learning problem"
   ch6a2g2 = "descript: learning problem"
   ch6a2h1 = "child:  emotional problem"
   ch6a2h2 = "descript: emotional problem"
   ch6a2i1 = "child:  mental retardation"
   ch6a2i2 = "descript: mental retardation"
   ch6a3 = "child illness-prob affctng grwth-dev."
   ch6a3a = "descript: illness-prob affctng grwth-dev"
   ch6a4 = "interviewer initials"
   ch6a5 = "date of interview" ;

FORMAT
   ch6a5 DATE9. ;
      

LENGTH
   visit 3                  ch6a1 3                  ch6a2a1 3             
   ch6a2b1 3                ch6a2c1 3                ch6a2d1 3             
   ch6a2e1 3                ch6a2f1 3                ch6a2g1 3             
   ch6a2h1 3                ch6a2i1 3                ch6a3 3 ;

         

RUN ;
