/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\cops1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = cops1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=38;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   VENTFEEL  12-13          SEEKDIV  14-15           SELFREL  16-17        
   DEVSSUPP  18-19          SOLVEFP  20-21           AVOIDPRB  22-23       
   SPRTSUPP  24-25          CLOSEFRD  26-27          PROFSUPP  28-29       
   DEMNDACT  30-31          HUMOR  32-33             RELAXING  34-35       
   TOTACOPE  36-38        ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   VENTFEEL = "Ventilating Feelings"
   SEEKDIV = "Seeking Diversions"
   SELFREL = "Developing Self-Reliance and Optimism"
   DEVSSUPP = "Developing Social Support"
   SOLVEFP = "Solving Family Problems"
   AVOIDPRB = "Avoiding Problems"
   SPRTSUPP = "Seeking Spiritual Support"
   CLOSEFRD = "Investing in Close Friends"
   PROFSUPP = "Seeking Professional Support"
   DEMNDACT = "Engaging in Demanding Activity"
   HUMOR = "Being Humorous"
   RELAXING = "Relaxing"
   TOTACOPE = "Total Coping Score" ;

LENGTH
   VISIT 3                  VENTFEEL 3               SEEKDIV 3             
   SELFREL 3                DEVSSUPP 3               SOLVEFP 3             
   AVOIDPRB 3               SPRTSUPP 3               CLOSEFRD 3            
   PROFSUPP 3               DEMNDACT 3               HUMOR 3               
   RELAXING 3               TOTACOPE 4 ;

      

RUN ;
