/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\crc0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = crc0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=28;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   crc1 $ 11-13             crc2 DATE11.             crc3  25              
   crc4  26-27              crc0  28               ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   crc1 = "interviewer initials"
   crc2 = "date of interview"
   crc3 = "location of interview"
   crc4 = "relationship of respondent to child"
   crc0 = "language of administration" ;

FORMAT
   crc2 DATE9.            ;
                     

LENGTH
   visit 3                  crc3 3                   crc4 3                
   crc0 3 ;

          

RUN ;
