/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ctb0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ctb0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=48;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   ctb0a  11                ctb0b  12-13             ctb0c  14-15          
   ctb1  16                 ctb2  17                 ctb3  18              
   ctb4  19                 ctb5  20                 ctb6  21              
   ctb7  22                 ctb8  23                 ctb9  24              
   ctb10  25                ctb11  26                ctb12  27             
   ctb13  28                ctb14  29                ctb15  30             
   ctb16  31                ctb17  32                ctb18  33             
   ctb19  34                ctb20 $ 35-37            ctb21 DATE11.         
 ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   ctb0a = "do you have spouse/partner/boyfriend"
   ctb0b = "# years been with partner"
   ctb0c = "# months been with partner"
   ctb1 = "discuss issue calmly"
   ctb2 = "get info to back up his side of things"
   ctb3 = "bring in someone to help settle things"
   ctb4 = "insult or swear at you"
   ctb5 = "sulk or refuse to talk to you"
   ctb6 = "stomp out of the room/house/yard"
   ctb7 = "cry"
   ctb8 = "do or say something to spite you"
   ctb9 = "threaten to hit/throw something at you"
   ctb10 = "throw/smash/hit/kick something else"
   ctb11 = "throw something at you"
   ctb12 = "push/grab/shove you"
   ctb13 = "slap you"
   ctb14 = "kick/bite/hit you with his fist"
   ctb15 = "hit or try to hit you with something"
   ctb16 = "beat you up"
   ctb17 = "choke you"
   ctb18 = "threaten you with a knife or gun"
   ctb19 = "use a knife or gun"
   ctb20 = "interviewer initials"
   ctb21 = "date of interview" ;

FORMAT
   ctb21 DATE9. ;
      

LENGTH
   visit 3                  ctb0a 3                  ctb0b 3               
   ctb0c 3                  ctb1 3                   ctb2 3                
   ctb3 3                   ctb4 3                   ctb5 3                
   ctb6 3                   ctb7 3                   ctb8 3                
   ctb9 3                   ctb10 3                  ctb11 3               
   ctb12 3                  ctb13 3                  ctb14 3               
   ctb15 3                  ctb16 3                  ctb17 3               
   ctb18 3                  ctb19 3 ;

         

RUN ;
