/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\dab0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = dab0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=30;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   dab1a  11                dab2  12                 dab3  13              
   dab4  14                 dab5  15                 dab6  16              
   dab7 $ 17-19             dab8 DATE11.           ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   dab1a = "does child have primary father-figure"
   dab2 = "relationship of father-figure to child"
   dab3 = "how much time does he spend with child"
   dab4 = "how much does he comfort/encourage child"
   dab5 = "how much he contributes to child^s care"
   dab6 = "how much he helps with financial needs"
   dab7 = "interviewer initials"
   dab8 = "date of interview" ;

FORMAT
   dab8 DATE9. ;
       

LENGTH
   visit 3                  dab1a 3                  dab2 3                
   dab3 3                   dab4 3                   dab5 3                
   dab6 3 ;

          

RUN ;
