/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\dema0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = dema0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=71;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   dema1  11-12             dema2  13                dema3  14             
   dema4  15                dema5  16                dema6  17             
   dema6b  18               dema7  19                dema8  20             
   dema9  21                dema10  22-23            dema11  24-25         
   dema12a  26              dema12b  27              dema12c  28           
   dema12d  29              dema12e  30              dema12f  31           
   dema12g  32              dema12h  33              dema12i  34           
   dema12j  35              dema12k  36              dema13a  37           
   dema13b  38              dema13c  39              dema14  40            
   dema15 DATE11.           dema17  52               dema18  53            
   dema19  54               dema20  55               dema21  56            
   dema22  57               dema23 $ 58-60           dema24 DATE11.        
 ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   dema1 = "years education- respondent"
   dema2 = "high school diploma or equiv-respondent"
   dema3 = "highest degree post high schl-respondent"
   dema4 = "current employment status-respondent"
   dema5 = "respondent has more than 1 job"
   dema6 = "hollingshead occup code-respondent"
   dema6b = "does respondent have husband/partner"
   dema7 = "current employment status-resp^s spouse"
   dema8 = "respondent^s spouse has more than 1 job"
   dema9 = "hollingshead occup code-resp^s spouse"
   dema10 = "total family income"
   dema11 = "# people dependent on family income"
   dema12a = "source income:work done by respondent"
   dema12b = "source income:work-other adults in home"
   dema12c = "source income:work-adults not in home"
   dema12d = "source income:work-children under 18"
   dema12e = "source income:child support"
   dema12f = "source income:afdc"
   dema12g = "source income:disability check"
   dema12h = "source income:unemployment"
   dema12i = "source income:workman^s comp"
   dema12j = "source income:social security retirement"
   dema12k = "source income:other"
   dema13a = "household receives medicaid"
   dema13b = "household receives wic"
   dema13c = "household receives food stamps"
   dema14 = "household receives housing assistance"
   dema15 = "date of birth-respondent"
   dema17 = "primary language-respondent"
   dema18 = "race-respondent"
   dema19 = "marital status-respondent"
   dema20 = "religious affiliation-respondent"
   dema21 = "frequency respondent attended relig serv"
   dema22 = "relig important in raising children"
   dema23 = "interviewer initials"
   dema24 = "date on interview" ;

FORMAT
   dema15 DATE9.            dema24 DATE9. ;
     

LENGTH
   visit 3                  dema1 3                  dema2 3               
   dema3 3                  dema4 3                  dema5 3               
   dema6 3                  dema6b 3                 dema7 3               
   dema8 3                  dema9 3                  dema10 3              
   dema11 3                 dema12a 3                dema12b 3             
   dema12c 3                dema12d 3                dema12e 3             
   dema12f 3                dema12g 3                dema12h 3             
   dema12i 3                dema12j 3                dema12k 3             
   dema13a 3                dema13b 3                dema13c 3             
   dema14 3                 dema17 3                 dema18 3              
   dema19 3                 dema20 3                 dema21 3              
   dema22 3 ;

        

RUN ;
