/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\depa0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = depa0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=44;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   depa1  11                depa2  12                depa3  13             
   depa4  14                depa5  15                depa6  16             
   depa7  17                depa8  18                depa9  19             
   depa10  20               depa11  21               depa12  22            
   depa13  23               depa14  24               depa15  25            
   depa16  26               depa17  27               depa18  28            
   depa19  29               depa20  30               depa21 $ 31-33        
   depa22 DATE11.         ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   depa1 = "bothered by normal things"
   depa2 = "poor appetite"
   depa3 = "could not shake off blues"
   depa4 = "just as good as others"
   depa5 = "trouble concentrating"
   depa6 = "felt depressed"
   depa7 = "everything an effort"
   depa8 = "hopeful about future"
   depa9 = "life a failure"
   depa10 = "felt fearful"
   depa11 = "restless sleep"
   depa12 = "happy"
   depa13 = "talked less"
   depa14 = "lonely"
   depa15 = "people unfriendly"
   depa16 = "enjoyed life"
   depa17 = "crying spells"
   depa18 = "felt sad"
   depa19 = "people disliked me"
   depa20 = "could not get going"
   depa21 = "interviewer initials"
   depa22 = "date of interview" ;

FORMAT
   depa22 DATE9. ;
     

LENGTH
   visit 3                  depa1 3                  depa2 3               
   depa3 3                  depa4 3                  depa5 3               
   depa6 3                  depa7 3                  depa8 3               
   depa9 3                  depa10 3                 depa11 3              
   depa12 3                 depa13 3                 depa14 3              
   depa15 3                 depa16 3                 depa17 3              
   depa18 3                 depa19 3                 depa20 3 ;

        

RUN ;
