/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\dhc1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = dhc1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=213;
INPUT
   CENTER $ 1-2             ID $ 3-9                 RELCG_4  10-11        
   FOSCG_4  12              CGSEX_4  13              RELCG_6  14-15        
   FOSCG_6  16              CGSEX_6  17              RELCG_8  18-19        
   FOSCG_8  20              CGSEX_8  21              RELCG_12  22-23       
   FOSCG_12  24             CGSEX_12  25             RELCG_14  26-27       
   FOSCG_14  28             CGSEX_14  29             RELCG_16  30-31       
   FOSCG_16  32             CGSEX_16  33             NADLTS_4  34          
   NKIDS_4  35-36           NINHOM_4  37-38          ADLRAT_4  39-42       
   BIOMOM_4  43             ADPMOM_4  44             STPMOM_4  45          
   FSTMOM_4  46             DADPAR_4  47             BIODAD_4  48          
   ADPDAD_4  49             STPDAD_4  50             FSTDAD_4  51          
   MOMPAR_4  52             GRANDM_4  53             GRANDF_4  54          
   ADSIBS_4  55             FEMREL_4  56             MALREL_4  57          
   UNRFEM_4  58             UNRMAL_4  59             MLTGEN_4  60          
   FAMST_4  61              FAM_4  62                NADLTS_6  63          
   NKIDS_6  64-65           NINHOM_6  66-67          ADLRAT_6  68-71       
   BIOMOM_6  72             ADPMOM_6  73             STPMOM_6  74          
   FSTMOM_6  75             DADPAR_6  76             BIODAD_6  77          
   ADPDAD_6  78             STPDAD_6  79             FSTDAD_6  80          
   MOMPAR_6  81             GRANDM_6  82             GRANDF_6  83          
   ADSIBS_6  84             FEMREL_6  85             MALREL_6  86          
   UNRFEM_6  87             UNRMAL_6  88             MLTGEN_6  89          
   FAMST_6  90              FAM_6  91                NADLTS_8  92          
   NKIDS_8  93-94           NINHOM_8  95-96          ADLRAT_8  97-100      
   BIOMOM_8  101            ADPMOM_8  102            STPMOM_8  103         
   FSTMOM_8  104            DADPAR_8  105            BIODAD_8  106         
   ADPDAD_8  107            STPDAD_8  108            FSTDAD_8  109         
   MOMPAR_8  110            GRANDM_8  111            GRANDF_8  112         
   ADSIBS_8  113            FEMREL_8  114            MALREL_8  115         
   UNRFEM_8  116            UNRMAL_8  117            MLTGEN_8  118         
   FAMST_8  119             FAM_8  120               NADLTS12  121         
   NKIDS_12  122-123        NINHOM12  124-125        ADLRAT12  126-129     
   BIOMOM12  130            ADPMOM12  131            STPMOM12  132         
   FSTMOM12  133            DADPAR12  134            BIODAD12  135         
   ADPDAD12  136            STPDAD12  137            FSTDAD12  138         
   MOMPAR12  139            GRANDM12  140            GRANDF12  141         
   ADSIBS12  142            FEMREL12  143            MALREL12  144         
   UNRFEM12  145            UNRMAL12  146            MLTGEN12  147         
   FAMST_12  148            FAM_12  149              NADLTS14  150         
   NKIDS_14  151-152        NINHOM14  153-154        ADLRAT14  155-158     
   BIOMOM14  159            ADPMOM14  160            STPMOM14  161         
   FSTMOM14  162            DADPAR14  163            BIODAD14  164         
   ADPDAD14  165            STPDAD14  166            FSTDAD14  167         
   MOMPAR14  168            GRANDM14  169            GRANDF14  170         
   ADSIBS14  171            FEMREL14  172            MALREL14  173         
   UNRFEM14  174            UNRMAL14  175            MLTGEN14  176         
   FAMST_14  177            FAM_14  178              NADLTS16  179         
   NKIDS_16  180-181        NINHOM16  182-183        ADLRAT16  184-187     
   BIOMOM16  188            ADPMOM16  189            STPMOM16  190         
   FSTMOM16  191            DADPAR16  192            BIODAD16  193         
   ADPDAD16  194            STPDAD16  195            FSTDAD16  196         
   MOMPAR16  197            GRANDM16  198            GRANDF16  199         
   ADSIBS16  200            FEMREL16  201            MALREL16  202         
   UNRFEM16  203            UNRMAL16  204            MLTGEN16  205         
   FAMST_16  206            FAM_16  207              LIVE_4  208           
   LIVE_6  209              LIVE_8  210              LIVE_12  211          
   LIVE_14  212             LIVE_16  213           ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   RELCG_4 = "Respondent Relationship to Child @ T4"
   FOSCG_4 = "Caregiver Foster Status @ T4"
   CGSEX_4 = "Gender of Respondent @ T4"
   RELCG_6 = "Respondent Relationship to Child @ T6"
   FOSCG_6 = "Caregiver Foster Status @ T6"
   CGSEX_6 = "Gender of Respondent @ T6"
   RELCG_8 = "Respondent Relationship to Child @ T8"
   FOSCG_8 = "Caregiver Foster Status @ T8"
   CGSEX_8 = "Gender of Respondent @ T8"
   RELCG_12 = "Respondent Relationship to Child @ T12"
   FOSCG_12 = "Caregiver Foster Status @ T12"
   CGSEX_12 = "Gender of Respondent @ T12"
   RELCG_14 = "Respondent Relationship to Child @ T14"
   FOSCG_14 = "Caregiver Foster Status @ T14"
   CGSEX_14 = "Gender of Respondent @ T14"
   RELCG_16 = "Respondent Relationship to Child @ T16"
   FOSCG_16 = "Caregiver Foster Status @ T16"
   CGSEX_16 = "Gender of Respondent @ T16"
   NADLTS_4 = "Number of adults in household @ T4"
   NKIDS_4 = "Number of kids in household @ T4"
   NINHOM_4 = "Number of people in household @ T4"
   ADLRAT_4 = "Ratio of adults to total in home @ T4"
   BIOMOM_4 = "Bio Mom in the home @ T4"
   ADPMOM_4 = "Adoptive Mom in the home @ T4"
   STPMOM_4 = "Step Mom in the home @ T4"
   FSTMOM_4 = "Foster Mom in the home @ T4"
   DADPAR_4 = "Fathers Partner in the home @ T4"
   BIODAD_4 = "Bio Dad in the home @ T4"
   ADPDAD_4 = "Adoptive Dad in the home @ T4"
   STPDAD_4 = "Step Dad in the home @ T4"
   FSTDAD_4 = "Foster Dad in the home @ T4"
   MOMPAR_4 = "Mothers Partner in the home @ T4"
   GRANDM_4 = "Grandmother in the home @ T4"
   GRANDF_4 = "Grandfather in the home @ T4"
   ADSIBS_4 = "# of adult siblings in the home @ T4"
   FEMREL_4 = "Other female relatives in home @ T4"
   MALREL_4 = "Other male relatives in the home @ T4"
   UNRFEM_4 = "# unrelated adult females in home @ T4"
   UNRMAL_4 = "# of unrelated adult males in home @ T4"
   MLTGEN_4 = "Multigenerational household @ T4"
   FAMST_4 = "Basic Family Structure: Age 4"
   FAM_4 = "parent configuration age 4"
   NADLTS_6 = "Number of adults in household @ T6"
   NKIDS_6 = "Number of kids in household @ T6"
   NINHOM_6 = "Number of people in household @ T6"
   ADLRAT_6 = "Ratio of adults to total in home @ T6"
   BIOMOM_6 = "Bio Mom in the home @ T6"
   ADPMOM_6 = "Adoptive Mom in the home @ T6"
   STPMOM_6 = "Step Mom in the home @ T6"
   FSTMOM_6 = "Foster Mom in the home @ T6"
   DADPAR_6 = "Fathers Partner in the home @ T6"
   BIODAD_6 = "Bio Dad in the home @ T6"
   ADPDAD_6 = "Adoptive Dad in the home @ T6"
   STPDAD_6 = "Step Dad in the home @ T6"
   FSTDAD_6 = "Foster Dad in the home @ T6"
   MOMPAR_6 = "Mothers Partner in the home @ T6"
   GRANDM_6 = "Grandmother in the home @ T6"
   GRANDF_6 = "Grandfather in the home @ T6"
   ADSIBS_6 = "# of adult siblings in the home @ T6"
   FEMREL_6 = "other female relatives in the home @ T6"
   MALREL_6 = "Other male relatives in the home @ T6"
   UNRFEM_6 = "# unrelated adult females in home @ T6"
   UNRMAL_6 = "# of unrelated adult males in home @ T6"
   MLTGEN_6 = "Multigenerational household @ T6"
   FAMST_6 = "Basic Family Structure: Age 6"
   FAM_6 = "parent configuration age 6"
   NADLTS_8 = "Number of adults in household @ T8"
   NKIDS_8 = "Number of kids in household @ T8"
   NINHOM_8 = "Number of people in household @ T8"
   ADLRAT_8 = "Ratio of adults to total in home @ T8"
   BIOMOM_8 = "Bio Mom in the home @ T8"
   ADPMOM_8 = "Adoptive Mom in the home @ T8"
   STPMOM_8 = "Step Mom in the home @ T8"
   FSTMOM_8 = "Foster Mom in the home @ T8"
   DADPAR_8 = "Fathers Partner in the home @ T8"
   BIODAD_8 = "Bio Dad in the home @ T8"
   ADPDAD_8 = "Adoptive Dad in the home @ T8"
   STPDAD_8 = "Step Dad in the home @ T8"
   FSTDAD_8 = "Foster Dad in the home @ T8"
   MOMPAR_8 = "Mothers Partner in the home @ T8"
   GRANDM_8 = "Grandmother in the home @ T8"
   GRANDF_8 = "Grandfather in the home @ T8"
   ADSIBS_8 = "# of adult siblings in the home @ T8"
   FEMREL_8 = "other female relatives in the home @ T8"
   MALREL_8 = "Other male relatives in the home @ T8"
   UNRFEM_8 = "# unrelated adult females in home @ T8"
   UNRMAL_8 = "# of unrelated adult males in home @ T8"
   MLTGEN_8 = "Multigenerational household @ T8"
   FAMST_8 = "Basic Family Structure: Age 8"
   FAM_8 = "parent configuration age 8"
   NADLTS12 = "Number of adults in household @ T12"
   NKIDS_12 = "Number of kids in household @ T12"
   NINHOM12 = "Number of people in household @ T12"
   ADLRAT12 = "Ratio of adults to total in home @ T12"
   BIOMOM12 = "Bio Mom in the home @ T12"
   ADPMOM12 = "Adoptive Mom in the home @ T12"
   STPMOM12 = "Step Mom in the home @ T12"
   FSTMOM12 = "Foster Mom in the home @ T12"
   DADPAR12 = "Fathers Partner in the home @ T12"
   BIODAD12 = "Bio Dad in the home @ T12"
   ADPDAD12 = "Adoptive Dad in the home @ T12"
   STPDAD12 = "Step Dad in the home @ T12"
   FSTDAD12 = "Foster Dad in the home @ T12"
   MOMPAR12 = "Mothers Partner in the home @ T12"
   GRANDM12 = "Grandmother in the home @ T12"
   GRANDF12 = "Grandfather in the home @ T12"
   ADSIBS12 = "# of adult siblings in the home @ T12"
   FEMREL12 = "other female relatives in the home @ T12"
   MALREL12 = "Other male relatives in the home @ T12"
   UNRFEM12 = "# unrelated adult females in home @ T12"
   UNRMAL12 = "# of unrelated adult males in home @ T12"
   MLTGEN12 = "Multigenerational household @ T12"
   FAMST_12 = "Basic Family Structure: Age 12"
   FAM_12 = "parent configuration age 12"
   NADLTS14 = "Number of adults in household @ T14"
   NKIDS_14 = "Number of kids in household @ T14"
   NINHOM14 = "Number of people in household @ T14"
   ADLRAT14 = "Ratio of adults to total in home @ T14"
   BIOMOM14 = "Bio Mom in the home @ T14"
   ADPMOM14 = "Adoptive Mom in the home @ T14"
   STPMOM14 = "Step Mom in the home @ T14"
   FSTMOM14 = "Foster Mom in the home @ T14"
   DADPAR14 = "Fathers Partner in the home @ T14"
   BIODAD14 = "Bio Dad in the home @ T14"
   ADPDAD14 = "Adoptive Dad in the home @ T14"
   STPDAD14 = "Step Dad in the home @ T14"
   FSTDAD14 = "Foster Dad in the home @ T14"
   MOMPAR14 = "Mothers Partner in the home @ T14"
   GRANDM14 = "Grandmother in the home @ T14"
   GRANDF14 = "Grandfather in the home @ T14"
   ADSIBS14 = "# of adult siblings in the home @ T14"
   FEMREL14 = "other female relatives in the home @ T14"
   MALREL14 = "Other male relatives in the home @ T14"
   UNRFEM14 = "# unrelated adult females in home @ T14"
   UNRMAL14 = "# of unrelated adult males in home @ T14"
   MLTGEN14 = "Multigenerational household @ T14"
   FAMST_14 = "Basic Family Structure: Age 14"
   FAM_14 = "parent configuration age 14"
   NADLTS16 = "Number of adults in household @ T16"
   NKIDS_16 = "Number of kids in household @ T16"
   NINHOM16 = "Number of people in household @ T16"
   ADLRAT16 = "Ratio of adults to total in home @ T16"
   BIOMOM16 = "Bio Mom in the home @ T16"
   ADPMOM16 = "Adoptive Mom in the home @ T16"
   STPMOM16 = "Step Mom in the home @ T16"
   FSTMOM16 = "Foster Mom in the home @ T16"
   DADPAR16 = "Fathers Partner in the home @ T16"
   BIODAD16 = "Bio Dad in the home @ T16"
   ADPDAD16 = "Adoptive Dad in the home @ T16"
   STPDAD16 = "Step Dad in the home @ T16"
   FSTDAD16 = "Foster Dad in the home @ T16"
   MOMPAR16 = "Mothers Partner in the home @ T16"
   GRANDM16 = "Grandmother in the home @ T16"
   GRANDF16 = "Grandfather in the home @ T16"
   ADSIBS16 = "# of adult siblings in the home @ T16"
   FEMREL16 = "other female relatives in the home @ T16"
   MALREL16 = "Other male relatives in the home @ T16"
   UNRFEM16 = "# unrelated adult females in home @ T16"
   UNRMAL16 = "# of unrelated adult males in home @ T16"
   MLTGEN16 = "Multigenerational household @ T16"
   FAMST_16 = "Basic Family Structure: Age 16"
   FAM_16 = "parent configuration age 16"
   LIVE_4 = "LIVING ARRANGEMENT AT T4"
   LIVE_6 = "LIVING ARRANGEMENT AT T6"
   LIVE_8 = "LIVING ARRANGEMENT AT T8"
   LIVE_12 = "LIVING ARRANGEMENT AT T12"
   LIVE_14 = "LIVING ARRANGEMENT AT T14"
   LIVE_16 = "LIVING ARRANGEMENT AT T16" ;

LENGTH
   RELCG_4 3                FOSCG_4 3                CGSEX_4 3             
   RELCG_6 3                FOSCG_6 3                CGSEX_6 3             
   RELCG_8 3                FOSCG_8 3                CGSEX_8 3             
   RELCG_12 3               FOSCG_12 3               CGSEX_12 3            
   RELCG_14 3               FOSCG_14 3               CGSEX_14 3            
   RELCG_16 3               FOSCG_16 3               CGSEX_16 3            
   NADLTS_4 3               NKIDS_4 3                NINHOM_4 3            
   BIOMOM_4 3               ADPMOM_4 3               STPMOM_4 3            
   FSTMOM_4 3               DADPAR_4 3               BIODAD_4 3            
   ADPDAD_4 3               STPDAD_4 3               FSTDAD_4 3            
   MOMPAR_4 3               GRANDM_4 3               GRANDF_4 3            
   ADSIBS_4 3               FEMREL_4 3               MALREL_4 3            
   UNRFEM_4 3               UNRMAL_4 3               MLTGEN_4 3            
   FAMST_4 3                FAM_4 3                  NADLTS_6 3            
   NKIDS_6 3                NINHOM_6 3               BIOMOM_6 3            
   ADPMOM_6 3               STPMOM_6 3               FSTMOM_6 3            
   DADPAR_6 3               BIODAD_6 3               ADPDAD_6 3            
   STPDAD_6 3               FSTDAD_6 3               MOMPAR_6 3            
   GRANDM_6 3               GRANDF_6 3               ADSIBS_6 3            
   FEMREL_6 3               MALREL_6 3               UNRFEM_6 3            
   UNRMAL_6 3               MLTGEN_6 3               FAMST_6 3             
   FAM_6 3                  NADLTS_8 3               NKIDS_8 3             
   NINHOM_8 3               BIOMOM_8 3               ADPMOM_8 3            
   STPMOM_8 3               FSTMOM_8 3               DADPAR_8 3            
   BIODAD_8 3               ADPDAD_8 3               STPDAD_8 3            
   FSTDAD_8 3               MOMPAR_8 3               GRANDM_8 3            
   GRANDF_8 3               ADSIBS_8 3               FEMREL_8 3            
   MALREL_8 3               UNRFEM_8 3               UNRMAL_8 3            
   MLTGEN_8 3               FAMST_8 3                FAM_8 3               
   NADLTS12 3               NKIDS_12 3               NINHOM12 3            
   BIOMOM12 3               ADPMOM12 3               STPMOM12 3            
   FSTMOM12 3               DADPAR12 3               BIODAD12 3            
   ADPDAD12 3               STPDAD12 3               FSTDAD12 3            
   MOMPAR12 3               GRANDM12 3               GRANDF12 3            
   ADSIBS12 3               FEMREL12 3               MALREL12 3            
   UNRFEM12 3               UNRMAL12 3               MLTGEN12 3            
   FAMST_12 3               FAM_12 3                 NADLTS14 3            
   NKIDS_14 3               NINHOM14 3               BIOMOM14 3            
   ADPMOM14 3               STPMOM14 3               FSTMOM14 3            
   DADPAR14 3               BIODAD14 3               ADPDAD14 3            
   STPDAD14 3               FSTDAD14 3               MOMPAR14 3            
   GRANDM14 3               GRANDF14 3               ADSIBS14 3            
   FEMREL14 3               MALREL14 3               UNRFEM14 3            
   UNRMAL14 3               MLTGEN14 3               FAMST_14 3            
   FAM_14 3                 NADLTS16 3               NKIDS_16 3            
   NINHOM16 3               BIOMOM16 3               ADPMOM16 3            
   STPMOM16 3               FSTMOM16 3               DADPAR16 3            
   BIODAD16 3               ADPDAD16 3               STPDAD16 3            
   FSTDAD16 3               MOMPAR16 3               GRANDM16 3            
   GRANDF16 3               ADSIBS16 3               FEMREL16 3            
   MALREL16 3               UNRFEM16 3               UNRMAL16 3            
   MLTGEN16 3               FAMST_16 3               FAM_16 3              
   LIVE_4 3                 LIVE_6 3                 LIVE_8 3              
   LIVE_12 3                LIVE_14 3                LIVE_16 3 ;

       

RUN ;
