/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\dma0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = dma0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=3155;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   dma2a $ 11-68            dma2a2 $ 69-144          dma3a $ 145-183       
   dma3a2 $ 184-259         dma4a $ 260-335          dma4a2 $ 336-411      
   dma4b $ 412-443          dma4b2 $ 444-519         dma4c $ 520-544       
   dma4c2 $ 545-620         dma4d $ 621-666          dma4d2 $ 667-742      
   dma5a $ 743-818          dma5a2 $ 819-894         dma5b $ 895-923       
   dma5b2 $ 924-999         dma5c $ 1000-1075        dma5c2 $ 1076-1151    
   dma5d $ 1152-1196        dma5d2 $ 1197-1272       dma6a $ 1273-1348     
   dma6a2 $ 1349-1424       dma6b $ 1425-1453        dma6b2 $ 1454-1529    
   dma6c $ 1530-1605        dma6c2 $ 1606-1681       dma6d $ 1682-1726     
   dma6d2 $ 1727-1802       dma7a $ 1803-1878        dma7a2 $ 1879-1954    
   dma7b $ 1955-1983        dma7b2 $ 1984-2059       dma7c $ 2060-2135     
   dma7c2 $ 2136-2211       dma7d $ 2212-2256        dma7d2 $ 2257-2332    
   dma8a $ 2333-2408        dma8a2 $ 2409-2484       dma8b $ 2485-2513     
   dma8b2 $ 2514-2589       dma8c $ 2590-2665        dma8c2 $ 2666-2741    
   dma8d $ 2742-2786        dma8d2 $ 2787-2862       dma26a $ 2863-2915    
   dma26a2 $ 2916-2991      dma26a3 $ 2992-3067      dma27 $ 3068-3070     
   dma1  3071               dma2a1  3072-3073        dma3a1  3074-3075     
   dma4a0  3076             dma4a1  3077-3078        dma4e  3079           
   dma4b1  3080-3081        dma4c1  3082-3083        dma4d1  3084-3085     
   dma5a0  3086             dma5a1  3087-3088        dma5e  3089           
   dma5b1  3090-3091        dma5c1  3092-3093        dma5d1  3094-3095     
   dma6a0  3096             dma6a1  3097-3098        dma6e  3099           
   dma6b1  3100-3101        dma6c1  3102-3103        dma6d1  3104-3105     
   dma7a0  3106             dma7a1  3107-3108        dma7e  3109           
   dma7b1  3110-3111        dma7c1  3112-3113        dma7d1  3114-3115     
   dma8a0  3116             dma8a1  3117-3118        dma8e  3119           
   dma8b1  3120-3121        dma8c1  3122-3123        dma8d1  3124-3125     
   dma9  3126               dma10  3127              dma11  3128           
   dma12  3129              dma13  3130              dma14  3131           
   dma15  3132              dma16  3133              dma17  3134           
   dma18  3135              dma19  3136              dma20  3137           
   dma21  3138              dma22  3139              dma23  3140           
   dma24  3141              dma25  3142              dma26a1  3143-3144    
   dma28 DATE11.          ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   dma2a = "biggest behavior problem line #1"
   dma2a2 = "biggest behavior problem line #2"
   dma3a = "how handled biggest problem line #1"
   dma3a2 = "how handled biggest problem line #2"
   dma4a = "child doesn^t obey/method 1 line 1"
   dma4a2 = "child doesn^t obey/method 1 line 2"
   dma4b = "child doesn^t obey/method 2 line 1"
   dma4b2 = "child doesn^t obey/method 2 line 2"
   dma4c = "if child didn^t obey/method 1 line 1"
   dma4c2 = "if child didn^t obey/method 1 line 2"
   dma4d = "if child didn^t obey/method 2 line 1"
   dma4d2 = "if child didn^t obey/method 2 line 2"
   dma5a = "child hits child/method 1 line 1"
   dma5a2 = "child hits child/method 1 line 2"
   dma5b = "child hits child/method 2 line 1"
   dma5b2 = "child hits child/method 2 line 2"
   dma5c = "if child hit child/method 1 line 1"
   dma5c2 = "if child hit child/method 1 line 2"
   dma5d = "if child hit child/method 2 line 1"
   dma5d2 = "if child hit child/method 2 line 2"
   dma6a = "child talks back/method 1 line 1"
   dma6a2 = "child talks back/method 1 line 2"
   dma6b = "child talks back/method 2 line 1"
   dma6b2 = "child talks back/method 2 line 2"
   dma6c = "if child talked back/method 1 line 1"
   dma6c2 = "if child talked back/method 1 line 2"
   dma6d = "if child talked back/method 2 line 1"
   dma6d2 = "if child talked back/method 2 line 2"
   dma7a = "child lies/method 1 line 1"
   dma7a2 = "child lies/method 1 line 2"
   dma7b = "child lies/method 2 line 1"
   dma7b2 = "child lies/method 2 line 2"
   dma7c = "if child lied/method 1 line 1"
   dma7c2 = "if child lied/method 1 line 2"
   dma7d = "if child lied/method 2 line 1"
   dma7d2 = "if child lied/method 2 line 2"
   dma8a = "child steals/method 1 line 1"
   dma8a2 = "child steals/method 1 line 2"
   dma8b = "child steals/method 2 line 1"
   dma8b2 = "child steals/method 2 line 2"
   dma8c = "if child stole/method 1 line 1"
   dma8c2 = "if child stole/method 1 line 2"
   dma8d = "if child stole/method 2 line 1"
   dma8d2 = "if child stole/method 2 line 2"
   dma26a = "most effective discipline method line #1"
   dma26a2 = "most effective discipline method line #2"
   dma26a3 = "most effective discipline method line #3"
   dma27 = "interviewer initials"
   dma1 = "how easy is it to manage child behavior"
   dma2a1 = "code biggest behavior problem"
   dma3a1 = "code how handled biggest problem"
   dma4a0 = "child doesn^t obey/did this occur"
   dma4a1 = "child doesn^t obey/code method 1"
   dma4e = "child doesn^t obey/method 1 always works"
   dma4b1 = "child doesn^t obey/code method 2"
   dma4c1 = "if child didn^t obey/code method 1"
   dma4d1 = "if child didn^t obey/code method 2"
   dma5a0 = "child hits child/did this occur"
   dma5a1 = "child hits child/code method 1"
   dma5e = "child hits child/method 1 always works"
   dma5b1 = "child hits child/code method 2"
   dma5c1 = "if child hit child/code method 1"
   dma5d1 = "if child hit child/code method 2"
   dma6a0 = "child talks back/did this occur"
   dma6a1 = "child talks back/code method 1"
   dma6e = "child talks back/method 1 always works"
   dma6b1 = "child talks back/code method 2"
   dma6c1 = "if child talked back/code method 1"
   dma6d1 = "if child talked back/code method 2"
   dma7a0 = "child lies/did this occur"
   dma7a1 = "child lies/code method 1"
   dma7e = "child lies/method 1 always works"
   dma7b1 = "child lies/code method 2"
   dma7c1 = "if child lied/code method 1"
   dma7d1 = "if child lied/code method 2"
   dma8a0 = "child steals/did this occur"
   dma8a1 = "child steals/code method 1"
   dma8e = "child steals/method 1 always works"
   dma8b1 = "child steals/code method 2"
   dma8c1 = "if child stole/code method 1"
   dma8d1 = "if child stole/code method 2"
   dma9 = "does anyone else discipline child"
   dma10 = "yell or scream at child"
   dma11 = "insult or swear at child"
   dma12 = "sulk or refuse to talk"
   dma13 = "stomp out of room or yard"
   dma14 = "do/say something to spite child"
   dma15 = "threaten to hit/throw something at child"
   dma16 = "throw/hit somethng due to child behavior"
   dma17 = "push or grab or shove child"
   dma18 = "spank chld"
   dma19 = "slap child"
   dma20 = "kick or bite or hit child with fist"
   dma21 = "hit/try to hit child with something"
   dma22 = "beat up child due to behavior"
   dma23 = "burn or scald child"
   dma24 = "threaten child with knife or gun"
   dma25 = "use knife or gun on child"
   dma26a1 = "code most effective discipline method"
   dma28 = "date of interview" ;

FORMAT
   dma28 DATE9. ;
      

LENGTH
   visit 3                  dma1 3                   dma2a1 3              
   dma3a1 3                 dma4a0 3                 dma4a1 3              
   dma4e 3                  dma4b1 3                 dma4c1 3              
   dma4d1 3                 dma5a0 3                 dma5a1 3              
   dma5e 3                  dma5b1 3                 dma5c1 3              
   dma5d1 3                 dma6a0 3                 dma6a1 3              
   dma6e 3                  dma6b1 3                 dma6c1 3              
   dma6d1 3                 dma7a0 3                 dma7a1 3              
   dma7e 3                  dma7b1 3                 dma7c1 3              
   dma7d1 3                 dma8a0 3                 dma8a1 3              
   dma8e 3                  dma8b1 3                 dma8c1 3              
   dma8d1 3                 dma9 3                   dma10 3               
   dma11 3                  dma12 3                  dma13 3               
   dma14 3                  dma15 3                  dma16 3               
   dma17 3                  dma18 3                  dma19 3               
   dma20 3                  dma21 3                  dma22 3               
   dma23 3                  dma24 3                  dma25 3               
   dma26a1 3 ;

       

RUN ;
