/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\eatb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = eatb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=146;
INPUT
   CENTER $ 1-2             ID $ 3-9                 EATBX1 $ 10           
   EATBX2 $ 11              EATBKG $ 12              EATBX3 $ 13           
   EATBX4 $ 14              EATBX5 $ 15              EATB22E $ 16          
   EATB27YA $ 17            EATB27AYA $ 18           VISIT  19-20          
   EATB0  21                EATB1  22-25             EATB2  26-28          
   EATB3  29-31             EATB4  32                EATB5  33             
   EATB6  34                EATB7  35                EATB8  36             
   EATB9  37                EATB10  38               EATB11  39            
   EATB12  40               EATB13  41               EATB14  42            
   EATB15  43               EATB16  44               EATB17  45            
   EATB18  46               EATB19  47               EATB20  48            
   EATB21  49-50            EATB23  51               EATB24  52            
   EATB25  53               EATB26  54               EATB27  55            
   EATB28  56               EATB29  57               EATB30  58            
   EATB31  59               EATB10A  60              EATB10B  61           
   EATB11A  62              EATB11B  63              EATB12A  64           
   EATB12B  65              EATB12C  66              EATB12D  67           
   EATB12E  68              EATB12F  69              EATB13A  70           
   EATB13B  71              EATB13C  72              EATB14A  73           
   EATB14B  74              EATB14C  75              EATB14D  76           
   EATB14E  77              EATB15A  78              EATB15B  79           
   EATB15C  80              EATB15D  81              EATB15E  82           
   EATB16A  83              EATB16B  84              EATB16C  85           
   EATB16D  86              EATB16E  87              EATB16F  88           
   EATB16G  89              EATB17A  90              EATB17B  91           
   EATB17C  92              EATB17D  93              EATB17E  94           
   EATB18A  95              EATB18B  96              EATB18C  97           
   EATB18D  98              EATB18E  99              EATB1CM  100          
   EATB20A  101             EATB20B  102             EATB20C  103          
   EATB20D  104             EATB20E  105             EATB20F  106          
   EATB20G  107             EATB20H  108             EATB20I  109          
   EATB21A  110             EATB21B  111             EATB21C  112          
   EATB21D  113-114         EATB21DGR  115           EATB21GR  116         
   EATB22A  117             EATB22B  118             EATB22C  119          
   EATB22D  120-121         EATB22DGR  122           EATB23A  123          
   EATB24A  124             EATB25A  125             EATB26A  126          
   EATB27A  127             EATB28A  128             EATB29A  129          
   EATB31A  130-131         EATB31AGR  132           EATB3KG  133          
   EATB4A  134              EATB5A  135              EATB5B  136           
   EATB5C  137              EATB5D  138              EATB6A  139           
   EATB7A  140              EATB10C  141             EATB21E  142          
   EATB22  143-144          EATB22GR  145            EATB30A  146          
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   EATBX1 = "Was height measured for study"
   EATBX2 = "Was weight measured for study"
   EATBKG = "How much do you weigh now-kg"
   EATBX3 = "Was youth underweight"
   EATBX4 = "INV response"
   EATBX5 = "Were  responses coded for Q14-18"
   EATB22E = "Start doing these things >1 yr ago"
   EATB27YA = "When prblms worst:hard to care for self"
   EATB27AYA = "How bad were prblms with doing things"
   VISIT = "VISIT NUMBER"
   EATB0 = "CM/KG/FT/IN/LBS"
   EATB1 = "How tall are you-ft/in"
   EATB2 = "How much do you weigh now-lb"
   EATB3 = "Last yr- your lowest weight-lb"
   EATB4 = "Last yr-anyone worried- too thin"
   EATB5 = "Least weight time-were you worried"
   EATB6 = "Last yr-weighed least-think overweight"
   EATB7 = "Do you think you are overwight now"
   EATB8 = "Last yr-low weight cause health prblm"
   EATB9 = "Think weight now could cause hlth prblms"
   EATB10 = "Last yr-felt bad 'cause fat/overweight"
   EATB11 = "Last yr-time thght abt food all the time"
   EATB12 = "Last yr-have you had an eating binge"
   EATB13 = "Last yr-refused foods that make you fat"
   EATB14 = "Last yr-made yourself throw up"
   EATB15 = "Last yr-taken pills/meds- no weightgain"
   EATB16 = "Last yr-done thing to go to toilet a lot"
   EATB17 = "Last yr-eaten no food for at 24 hrs"
   EATB18 = "Last yr-spend time exrcising/lose wght"
   EATB19 = "Last yr-did things like this for 3mths"
   EATB20 = "Have you started to menstruate"
   EATB21 = "Worry about being thin-how old 1st time"
   EATB23 = "Last yr:family upset/thngs you did"
   EATB24 = "No wgtgain thngs keep u from doing thngs"
   EATB25 = "Wgtthngs keep u from doing thng wth othr"
   EATB26 = "When prblms worst:make it hard for you"
   EATB27 = "No wghtgain thngs cause tchr/boss upset"
   EATB28 = "When prblms worst:things make you upset"
   EATB29 = "Seen someone in hospital in last year"
   EATB30 = "Who did you see/ are going to see"
   EATB31 = "Life/wghtgain:time u/other more worried"
   EATB10A = "Think losing weight most important thing"
   EATB10B = "Last yr-thinnest:losing wght most import"
   EATB11A = "When thgt abt food:dificlt to think othr"
   EATB11B = "Last 4wks-time thnk of food all the time"
   EATB12A = "During binge-eat > most young men/women"
   EATB12B = "Did you eat food in a very short time"
   EATB12C = "Binge-feel you wouldn't be able to stop"
   EATB12D = "Last yr-have binge twice a week"
   EATB12E = "Have binges teice a weeek for 3 mths"
   EATB12F = "Last 4wks-had several eating binges"
   EATB13A = "Refused fat foods most day for 3 mths"
   EATB13B = "Last yr-refused fat food when thinnest"
   EATB13C = "Last 4 wks-often refused fat foods"
   EATB14A = "Last yr-made self throw up/weightgain"
   EATB14B = "Last yr-made self throw up twice a week"
   EATB14C = "Make self throw up twice a wk for 3 mths"
   EATB14D = "Last yr/thinnest-make self throw up"
   EATB14E = "Last 4wks-have you made self throw up"
   EATB15A = "What did you take meds)"
   EATB15B = "Last yr-take pills/meds twice a week"
   EATB15C = "Take meds twice a week for 3 mths"
   EATB15D = "Last yr thinnest-take meds to lose wght"
   EATB15E = "Last 4wks-often take meds"
   EATB16A = "What did you do"
   EATB16B = "Go to toilet to keep from gaining wght"
   EATB16C = "Did somthng twice a wk to go to toilet"
   EATB16D = "Did you oftn do toilet thngs for 3 mths"
   EATB16E = "Last yr/thinnest-do thngs/go to toilet"
   EATB16F = "Last 4wks-done thngs to go to toilet"
   EATB16G = "Last 4wks-how often doen this twice a wk"
   EATB17A = "Eaten no food to keep from weightgain"
   EATB17B = "Time when no food for 2 days a week"
   EATB17C = "No food 2 days a wk for 3 mths"
   EATB17D = "Last yr/thinnest-refsed to eat food"
   EATB17E = "Last 4wks-often eaten no food"
   EATB18A = "Time exercising that got in the way"
   EATB18B = "Exercising got in the way 2 days a week"
   EATB18C = "Did you exercise like this for 3 mths"
   EATB18D = "Last yr/thinnest-spend time exercising"
   EATB18E = "Last 4wks-exercisng got in the way"
   EATB1CM = "Height in cm"
   EATB20A = "Ever had regular periods"
   EATB20B = "Regular periods start more than a yr ago"
   EATB20C = "Last yr-miss 3 mnthly periods in a row"
   EATB20D = "Missed periods when thinnest"
   EATB20E = "Had a period in last 3 mths"
   EATB20F = "Do you take birth control pills"
   EATB20G = "Last yr-taken BC pills every month"
   EATB20H = "When not taking pils-have period"
   EATB20I = "When missed period were you very thin"
   EATB21A = "Was that more than a year ago"
   EATB21B = "Worry/thin-since 1st time ever stopped"
   EATB21C = "Stopped worry-did that tiem last 2 mths"
   EATB21D = "Last yr-how old when started(symptom)"
   EATB21DGR = "Last yr-grade when started(symptom)"
   EATB21GR = "Worry about being thin-grade 1st time"
   EATB22A = "Did these things more mthan a yr ago"
   EATB22B = "Since 1st time ever  didn't do thngs"
   EATB22C = "Time didn't do thngs-ever last 2/>2 mths"
   EATB22D = "Symptom-how old when statred this time"
   EATB22DGR = "Symptom-grade when statred this time"
   EATB23A = "How often family/friends seem upset"
   EATB24A = "How often this kept you from doing thngs"
   EATB25A = "Often way u ate keep u from doing thngs"
   EATB26A = "How bad were problems with schl/work"
   EATB27A = "How often tchr/boss upset"
   EATB28A = "How bad did these thngs make you feel"
   EATB29A = "Have appointment re: being overactive"
   EATB31A = "Age when you/other most worried"
   EATB31AGR = "Grade when you/other most worried"
   EATB3KG = "Last yr- your lowest weight-kg"
   EATB4A = "Last 4 wks-anyone worried- too thin"
   EATB5A = "Time you worried every day abt too thin"
   EATB5B = "Too thin/worried-difficult think things"
   EATB5C = "Worrying abt fat keep your weight down"
   EATB5D = "Last 4 wks-worried about being fat"
   EATB6A = "Did you think you were too thin"
   EATB7A = "Do you think you are too thin"
   EATB10C = "Last 4wks-felt bad 'cause fat/overwhgt"
   EATB21E = "Started (symptom) >1 yr ago"
   EATB22 = "Age 1st time did (sypmtom)"
   EATB22GR = "Garde 1st time did (sypmtom)"
   EATB30A = "What did person U saw say was the matter" ;

LENGTH
   VISIT 3                  EATB0 3                  EATB2 4               
   EATB3 4                  EATB4 3                  EATB5 3               
   EATB6 3                  EATB7 3                  EATB8 3               
   EATB9 3                  EATB10 3                 EATB11 3              
   EATB12 3                 EATB13 3                 EATB14 3              
   EATB15 3                 EATB16 3                 EATB17 3              
   EATB18 3                 EATB19 3                 EATB20 3              
   EATB21 3                 EATB23 3                 EATB24 3              
   EATB25 3                 EATB26 3                 EATB27 3              
   EATB28 3                 EATB29 3                 EATB30 3              
   EATB31 3                 EATB10A 3                EATB10B 3             
   EATB11A 3                EATB11B 3                EATB12A 3             
   EATB12B 3                EATB12C 3                EATB12D 3             
   EATB12E 3                EATB12F 3                EATB13A 3             
   EATB13B 3                EATB13C 3                EATB14A 3             
   EATB14B 3                EATB14C 3                EATB14D 3             
   EATB14E 3                EATB15A 3                EATB15B 3             
   EATB15C 3                EATB15D 3                EATB15E 3             
   EATB16A 3                EATB16B 3                EATB16C 3             
   EATB16D 3                EATB16E 3                EATB16F 3             
   EATB16G 3                EATB17A 3                EATB17B 3             
   EATB17C 3                EATB17D 3                EATB17E 3             
   EATB18A 3                EATB18B 3                EATB18C 3             
   EATB18D 3                EATB18E 3                EATB1CM 3             
   EATB20A 3                EATB20B 3                EATB20C 3             
   EATB20D 3                EATB20E 3                EATB20F 3             
   EATB20G 3                EATB20H 3                EATB20I 3             
   EATB21A 3                EATB21B 3                EATB21C 3             
   EATB21D 3                EATB21DGR 3              EATB21GR 3            
   EATB22A 3                EATB22B 3                EATB22C 3             
   EATB22D 3                EATB22DGR 3              EATB23A 3             
   EATB24A 3                EATB25A 3                EATB26A 3             
   EATB27A 3                EATB28A 3                EATB29A 3             
   EATB31A 3                EATB31AGR 3              EATB3KG 3             
   EATB4A 3                 EATB5A 3                 EATB5B 3              
   EATB5C 3                 EATB5D 3                 EATB6A 3              
   EATB7A 3                 EATB10C 3                EATB21E 3             
   EATB22 3                 EATB22GR 3               EATB30A 3 ;

       

RUN ;
