/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\empa1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = empa1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=14;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   EMPA1A  12               EMPA1B  13               EMPA2  14             
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   EMPA1A = "Wk: # hrs spend working for pay"
   EMPA1B = "Wk/schl : # hrs spend working for pay"
   EMPA2 = "Wk/ no schl  # hrs spend working for pay" ;

LENGTH
   VISIT 3                  EMPA1A 3                 EMPA1B 3              
   EMPA2 3 ;

         

RUN ;
