/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\guna1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = guna1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=17;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   GUNA1  12                GUNA2  13                GUNA3  14             
   GUNA4  15                GUNA5  16                GUNA6  17             
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   GUNA1 = "Are there guns now kept in your home now"
   GUNA2 = "Handled loaded gun without supervision"
   GUNA3 = "Access to gun/ammunition; no permission"
   GUNA4 = "Is there a handgun in/around your home"
   GUNA5 = "Is there a loaded gun"
   GUNA6 = "Is there an unlocked gun" ;

LENGTH
   VISIT 3                  GUNA1 3                  GUNA2 3               
   GUNA3 3                  GUNA4 3                  GUNA5 3               
   GUNA6 3 ;

         

RUN ;
