/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\hrba1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = hrba1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=38;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   HRBA1  12                HRBA2  13                HRBA3  14             
   HRBA4  15                HRBA5  16                HRBA6  17             
   HRBA7  18                HRBA8  19                HRBA9  20             
   HRBA10  21               HRBA11  22               HRBA12  23            
   HRBA13  24               HRBA14  25               HRBA15  26            
   HRBA16  27               HRBA17  28               HRBA18  29            
   HRBA19  30               HRBA20  31               HRBA16A  32           
   HRBA16B  33              HRBA16C  34              HRBA4A1  35           
   HRBA4A2  36              HRBA4A3  37              HRBA4A4  38           
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   HRBA1 = "Last 12 mths:gained >10 lbs"
   HRBA2 = "Last 12 mths:lost >10 lbs"
   HRBA3 = "Last 12 mths:tried to gain weight"
   HRBA4 = "Last 12 mths:tried to lose weight"
   HRBA5 = "Consider yourself overweight"
   HRBA6 = "Consider yourself underweight"
   HRBA7 = "Weekday-# hrs watch TV/watch video games"
   HRBA8 = "Past 7 dys-# did you exercise-20 mins"
   HRBA9 = "Past 7 dys-# did you exercise-3 mins"
   HRBA10 = "Past 7 dys-# did you exercise-strength"
   HRBA11 = "Past 7 dys-exercise usual amount"
   HRBA12 = "How often do you wear a seat belt"
   HRBA13 = "Past 30 dys-# times in car/someone drink"
   HRBA14 = "Past 30 dys-# times in car/you drink"
   HRBA15 = "Do you have a driver's license"
   HRBA16 = "Ever run away from home overnight"
   HRBA17 = "Last 12 mths:consider suicide"
   HRBA18 = "Last 12 mths:plan suicide"
   HRBA19 = "Last 12 mths:attempt suicide"
   HRBA20 = "Last 12 mths:suicide result in injury"
   HRBA16A = "# times run away overnight"
   HRBA16B = "Age-1st time run away overnight"
   HRBA16C = "Age-last time run away overnight"
   HRBA4A1 = "Weight control:skipping meals"
   HRBA4A2 = "Weight control:not eating several meals"
   HRBA4A3 = "Weight control:vomiting"
   HRBA4A4 = "Weight control:taking diet pills" ;

LENGTH
   VISIT 3                  HRBA1 3                  HRBA2 3               
   HRBA3 3                  HRBA4 3                  HRBA5 3               
   HRBA6 3                  HRBA7 3                  HRBA8 3               
   HRBA9 3                  HRBA10 3                 HRBA11 3              
   HRBA12 3                 HRBA13 3                 HRBA14 3              
   HRBA15 3                 HRBA16 3                 HRBA17 3              
   HRBA18 3                 HRBA19 3                 HRBA20 3              
   HRBA16A 3                HRBA16B 3                HRBA16C 3             
   HRBA4A1 3                HRBA4A2 3                HRBA4A3 3             
   HRBA4A4 3 ;

       

RUN ;
