/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\irca0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = irca0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=247;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   irca1  11                irca2  12                irca3  13             
   irca4  14                irca5  15                irca6 $ 16            
   irca7a  17               irca7a1 $ 18-47          irca7b  48            
   irca7b1 $ 49-78          irca7c  79               irca7c1 $ 80-109      
   irca7d  110              irca7d1 $ 111-140        irca7e  141           
   irca7e1 $ 142-171        irca7f  172              irca7f1 $ 173-202     
   irca7g  203              irca7g1 $ 204-233        irca8 $ 234-236       
   irca9 DATE11.          ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   irca1 = "neatness of child"
   irca2 = "restedness of child"
   irca3 = "attractiveness of child"
   irca4 = "child understood directions"
   irca5 = "child attends to tasks-questions"
   irca6 = "privacy conditions during interview"
   irca7a = "validity of press"
   irca7a1 = "reason for validity of press"
   irca7b = "validity of block design"
   irca7b1 = "reason for validity of block design"
   irca7c = "validity of vocabulary"
   irca7c1 = "reason for validity of vocabulary"
   irca7d = "validity of cev16"
   irca7d1 = "reason for validity of cev16"
   irca7e = "validity of pcs16-pcka"
   irca7e1 = "reason for validity of pcs16-pcka"
   irca7f = "validity of lsd16"
   irca7f1 = "reason for validity of lsd16"
   irca7g = "validity of isf10"
   irca7g1 = "reason for validity of isf10"
   irca8 = "interviewer initials"
   irca9 = "date of interview" ;

FORMAT
   irca9 DATE9. ;
      

LENGTH
   visit 3                  irca1 3                  irca2 3               
   irca3 3                  irca4 3                  irca5 3               
   irca7a 3                 irca7b 3                 irca7c 3              
   irca7d 3                 irca7e 3                 irca7f 3              
   irca7g 3 ;

        

RUN ;
