/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\irce1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = irce1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=84;
INPUT
   CENTER $ 1-2             ID $ 3-9                 IRCE14 $ 10-12        
   VISIT  13-14             IRCE1  15                IRCE2  16             
   IRCE4  17                IRCE5  18                IRCE6  19             
   IRCE8  20                IRCE9  21                IRCE10  22            
   IRCE11  23-25            IRCE12  26               IRCE13  27            
   IRCE10A  28              IRCE3A  29               IRCE3B  30            
   IRCE3C  31               IRCE3D  32               IRCE3E  33            
   IRCE3F  34               IRCE3G  35               IRCE7A  36            
   IRCE7B  37               IRCE7C  38               IRCE7D  39            
   IRCE9A1  40              IRCE9A2  41              IRCE9A3  42           
   IRCE9A4  43              IRCE9A5  44              IRCE9A6  45           
   IRCE9A7  46              IRCE9A8  47              IRCE9A9  48           
   IRCE9A10  49             IRCE9A11  50             IRCE9A12  51          
   IRCE9A13  52             IRCE9A14  53             IRCE9A15  54          
   IRCE9A16  55             IRCE9A17  56             IRCE9A18  57          
   IRCE9A19  58             IRCE9A20  59             IRCE9A21  60          
   IRCE9A22  61             IRCE9A23  62             IRCE9A24  63          
   IRCE9A25  64             IRCE9A26  65             IRCE9A27  66          
   IRCE9A28  67             IRCE9A29  68             IRCE9A30  69          
   IRCE9A31  70             IRCE9A32  71             IRCE9A33  72          
   IRCE9A34  73             IRCE15 DATE11.         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   IRCE14 = "Interviewer initials"
   VISIT = "VISIT NUMBER"
   IRCE1 = "How was the interview administered"
   IRCE2 = "Why was full A-CASI not administered"
   IRCE4 = "How comfortable youth seem with computer"
   IRCE5 = "How well youth seem to read"
   IRCE6 = "Interview environment:conducted..."
   IRCE8 = "Concerns about interview validity"
   IRCE9 = "Concerns - specific interview validity"
   IRCE10 = "Was interview completed  on...(session)"
   IRCE11 = "How long did te interview take-mins"
   IRCE12 = "How many breaks were taken"
   IRCE13 = "Do you have additional comments"
   IRCE10A = "If interview not completed-why"
   IRCE3A = "Obser./youth:not/very attentive"
   IRCE3B = "Obser./youth:anxious-relaxed"
   IRCE3C = "Obser./youth:very tired-fresh & rested"
   IRCE3D = "Obser./youth:poorly/well groomed"
   IRCE3E = "Obser./youth:resistant-cooperative"
   IRCE3F = "Obser./youth:underweight-overweight"
   IRCE3G = "Obser./youth:depressed-cheerful"
   IRCE7A = "Privacy of interview-Interviewer"
   IRCE7B = "Privacy of interview-partner/friend"
   IRCE7C = "Privacy of interview-parent/c-giver"
   IRCE7D = "Privacy of interview-other"
   IRCE9A1 = "Code Mimor/Major for concerns-YDEB"
   IRCE9A2 = "Code Mimor/Major for concerns-YHCA"
   IRCE9A3 = "Code Mimor/Major for concerns-NRIB"
   IRCE9A4 = "Code Mimor/Major for concerns-MPRA"
   IRCE9A5 = "Code Mimor/Major for concerns-AWHA"
   IRCE9A6 = "Code Mimor/Major for concerns-YSCA"
   IRCE9A7 = "Code Mimor/Major for concerns-YBPA"
   IRCE9A8 = "Code Mimor/Major for concerns-APIA"
   IRCE9A9 = "Code Mimor/Major for concerns-STBA"
   IRCE9A10 = "Code Mimor/Major for concerns-AHSB"
   IRCE9A11 = "Code Mimor/Major for concerns-HRBA"
   IRCE9A12 = "Code Mimor/Major for concerns-TSIA"
   IRCE9A13 = "Code Mimor/Major for concerns-YSUA"
   IRCE9A14 = "Code Mimor/Major for concerns-AWRA"
   IRCE9A15 = "Code Mimor/Major for concerns-ASEC"
   IRCE9A16 = "Code Mimor/Major for concerns-FAPA"
   IRCE9A17 = "Code Mimor/Major for concerns-AFFA"
   IRCE9A18 = "Code Mimor/Major for concerns-PAFA"
   IRCE9A19 = "Code Mimor/Major for concerns-YNEA"
   IRCE9A20 = "Code Mimor/Major for concerns-YRNA"
   IRCE9A21 = "Code Mimor/Major for concerns-LPAA"
   IRCE9A22 = "Code Mimor/Major for concerns-PALA"
   IRCE9A23 = "Code Mimor/Major for concerns-SALA"
   IRCE9A24 = "Code Mimor/Major for concerns-JVQA"
   IRCE9A25 = "Code Mimor/Major for concerns-DELA"
   IRCE9A26 = "Code Mimor/Major for concerns-CJIA"
   IRCE9A27 = "Code Mimor/Major for concerns-TADA"
   IRCE9A28 = "Code Mimor/Major for concerns-SKIA"
   IRCE9A29 = "Code Mimor/Major for concerns-QRPB"
   IRCE9A30 = "Code Mimor/Major for concerns-YSSB"
   IRCE9A31 = "Code Mimor/Major for concerns-RCIA"
   IRCE9A32 = "Code Mimor/Major for concerns-SEMA"
   IRCE9A33 = "Code Mimor/Major for concerns-COPA"
   IRCE9A34 = "Code Mimor/Major for concerns-DEQA"
   IRCE15 = "Date of YA-DISC interview" ;

FORMAT
   IRCE15 DATE9. ;
     

LENGTH
   VISIT 3                  IRCE1 3                  IRCE2 3               
   IRCE4 3                  IRCE5 3                  IRCE6 3               
   IRCE8 3                  IRCE9 3                  IRCE10 3              
   IRCE11 4                 IRCE12 3                 IRCE13 3              
   IRCE10A 3                IRCE3A 3                 IRCE3B 3              
   IRCE3C 3                 IRCE3D 3                 IRCE3E 3              
   IRCE3F 3                 IRCE3G 3                 IRCE7A 3              
   IRCE7B 3                 IRCE7C 3                 IRCE7D 3              
   IRCE9A1 3                IRCE9A2 3                IRCE9A3 3             
   IRCE9A4 3                IRCE9A5 3                IRCE9A6 3             
   IRCE9A7 3                IRCE9A8 3                IRCE9A9 3             
   IRCE9A10 3               IRCE9A11 3               IRCE9A12 3            
   IRCE9A13 3               IRCE9A14 3               IRCE9A15 3            
   IRCE9A16 3               IRCE9A17 3               IRCE9A18 3            
   IRCE9A19 3               IRCE9A20 3               IRCE9A21 3            
   IRCE9A22 3               IRCE9A23 3               IRCE9A24 3            
   IRCE9A25 3               IRCE9A26 3               IRCE9A27 3            
   IRCE9A28 3               IRCE9A29 3               IRCE9A30 3            
   IRCE9A31 3               IRCE9A32 3               IRCE9A33 3            
   IRCE9A34 3 ;

      

RUN ;
