/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\irrb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = irrb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=36;
INPUT
   CENTER $ 1-2             ID $ 3-9                 IRRB12 $ 10-12        
   VISIT  13-14             IRRB1  15                IRRB2  16             
   IRRB3  17                IRRB4  18                IRRB5  19             
   IRRB6  20                IRRB7  21                IRRB8  22             
   IRRB9  23                IRRB10  24               IRRB11  25            
   IRRB13 DATE11.         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   IRRB12 = "Interviewer initials"
   VISIT = "VISIT NUMBER"
   IRRB1 = "Cooperative/uncooperative"
   IRRB2 = "Truthful/dishonest"
   IRRB3 = "Open/guarded"
   IRRB4 = "Comprehending/not comprehending"
   IRRB5 = "Clean residence/dirty residence"
   IRRB6 = "Safe residence/unsafe residence"
   IRRB7 = "Well maintained/dilapidated residence"
   IRRB8 = "Safe neighborhood/unsafe neighborhood"
   IRRB9 = "The interview was conducted..."
   IRRB10 = "Response to ACASI portion of interview"
   IRRB11 = "Success in learning/using ACASI system"
   IRRB13 = "Date of interview" ;

FORMAT
   IRRB13 DATE9. ;
     

LENGTH
   VISIT 3                  IRRB1 3                  IRRB2 3               
   IRRB3 3                  IRRB4 3                  IRRB5 3               
   IRRB6 3                  IRRB7 3                  IRRB8 3               
   IRRB9 3                  IRRB10 3                 IRRB11 3 ;

        

RUN ;
