/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\kga0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = kga0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=560;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   kga1 $ 11-86             kga2a $ 87-162           kga3a $ 163-238       
   kga4a $ 239-314          kga5 $ 315-390           kga6 $ 391-466        
   kga7 $ 467-542           kga8 $ 543-545           kga0  546             
   kga2  547                kga3  548                kga4  549             
   kga9 DATE11.           ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   kga1 = "what does child do when not in school"
   kga2a = "describe pretend or make-believe games"
   kga3a = "describe the imaginary friend"
   kga4a = "how is imaginary friend real to child"
   kga5 = "what are you most proud of about child"
   kga6 = "what do you like most about your child"
   kga7 = "what is your child best at"
   kga8 = "interviewer initials"
   kga0 = "kga administered y/n"
   kga2 = "does s/he play pretend game/make-believe"
   kga3 = "does s/he have an imaginary friend"
   kga4 = "is imaginary friend real to child"
   kga9 = "date of interview" ;

FORMAT
   kga9 DATE9. ;
       

LENGTH
   visit 3                  kga0 3                   kga2 3                
   kga3 3                   kga4 3 ;

          

RUN ;
