/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\manb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = manb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=203;
INPUT
   CENTER $ 1-2             ID $ 3-9                 MANB1E $ 10-29        
   MANB14A $ 30-68          MANB23A $ 69-85          MANB24 $ 86           
   VISIT  87-88             MANB1  89                MANB2  90             
   MANB3  91                MANB4  92                MANB5  93             
   MANB6  94                MANB7  95                MANB8  96             
   MANB9  97                MANB10  98               MANB11  99            
   MANB12  100              MANB13  101              MANB14  102           
   MANB15  103-104          MANB16  105              MANB17  106           
   MANB18  107              MANB19  108              MANB20  109           
   MANB21  110              MANB22  111              MANB10A  112          
   MANB10B  113             MANB10C  114             MANB10D  115          
   MANB11A  116             MANB11B  117             MANB11C  118          
   MANB11D  119             MANB12A  120             MANB12B  121          
   MANB12C  122             MANB12D  123             MANB13A  124          
   MANB13B  125             MANB13C  126             MANB13D  127          
   MANB13E  128             MANB13F  129             MANB13G  130          
   MANB13H  131             MANB14B  132             MANB15A  133          
   MANB15B  134             MANB15C  135             MANB15D  136-137      
   MANB15DGR  138           MANB15E  139-140         MANB15GR  141         
   MANB16A  142             MANB17A  143             MANB18A  144          
   MANB19A  145             MANB1A  146              MANB1B  147           
   MANB1C  148              MANB1D  149              MANB1F  150           
   MANB1G  151              MANB1H  152              MANB1I  153           
   MANB1J  154              MANB20A  155             MANB20AYA  156        
   MANB20YA  157            MANB21A  158             MANB22A  159          
   MANB24A  160-161         MANB2A  162              MANB2B  163           
   MANB2C  164              MANB2D  165              MANB2E  166           
   MANB2F  167              MANB2G  168              MANB3A  169           
   MANB3B  170              MANB3C  171              MANB3D  172           
   MANB3E  173              MANB4A  174              MANB4B  175           
   MANB4C  176              MANB4D  177              MANB4E  178           
   MANB5A  179              MANB5B  180              MANB5C  181           
   MANB5D  182              MANB6A  183              MANB6B  184           
   MANB6C  185              MANB6D  186              MANB7A  187           
   MANB7B  188              MANB7C  189              MANB7D  190           
   MANB8A  191              MANB8B  192              MANB8C  193           
   MANB8D  194              MANB8E  195              MANB8F  196           
   MANB9A  197              MANB9B  198              MANB9C  199           
   MANB9D  200              MANB9E  201              MANBX1  202           
   MANB23AGR  203         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   MANB1E = "What happened/was about to happen"
   MANB14A = "Last yr-what did you do when got in trbl"
   MANB23A = "What person you saw say the matter was"
   MANB24 = "Since 5yrs-ever more excited/problems"
   VISIT = "VISIT NUMBER"
   MANB1 = "Last yr: have you felt excited"
   MANB2 = "Last yr: have you been grouchy/angry"
   MANB3 = "Last yr: thought you were vry special"
   MANB4 = "Thought you have special abilities"
   MANB5 = "Time when slept less than usual"
   MANB6 = "Last yr: talked too much/quickly"
   MANB7 = "Time when mind was racing too quickly"
   MANB8 = "Time when hard to keep mind on things"
   MANB9 = "Last yr:have you felt very restless"
   MANB10 = "Time when felt more friendly than usual"
   MANB11 = "Last yr: gotten thru schl work faster"
   MANB12 = "Last yr:felt more interest in sex"
   MANB13 = "Last yr: wished you hadn't done thngs"
   MANB14 = "Trouble for doing things when excited"
   MANB15 = "Age first time you ever felt excited"
   MANB16 = "Last yr:being excited upset family/frnds"
   MANB17 = "Feeling excited prevent family things"
   MANB18 = "Feeling excited prevent other things"
   MANB19 = "Whn prblms worst- how diffcul schl prblm"
   MANB20 = "Last time:xcited feeling upset boss/tchr"
   MANB21 = "When prblms worst-excited make u upset"
   MANB22 = "Seen someone in hospital in last year"
   MANB10A = "Tried makng frnds with whom you wouldn't"
   MANB10B = "Friendless problem worried others"
   MANB10C = "Last yr: very friendly when excited"
   MANB10D = "Last 4 wks:felt mor efrindly than usual"
   MANB11A = "Take on lots of things than before"
   MANB11B = "Prblm of taking on things worried others"
   MANB11C = "Last yr: did schlwrk fastr whn excitd"
   MANB11D = "Last 4 wks:did schlwrk faster"
   MANB12A = "Think much sex prevent other thinking"
   MANB12B = "Problem of sex interest worried others"
   MANB12C = "Last yr: more sex intrest whn excited"
   MANB12D = "Last 4 wks: felt more interest in sex"
   MANB13A = "Done things you usually wouldn't do"
   MANB13B = "Bought things that you couldn't afford"
   MANB13C = "Othrs worried get self/them into debt"
   MANB13D = "Done reckless or dangerous things"
   MANB13E = "Others worried you took these risks"
   MANB13F = "Done somthng sexual normally wouldn't do"
   MANB13G = "Done things wish you hadn't when excited"
   MANB13H = "Last 4 wks- wished u hadn't done thngs"
   MANB14B = "Last 4 wks- got into serious trouble"
   MANB15A = "Were you excited > 1 yr ago"
   MANB15B = "Ever a time when not feeling excited"
   MANB15C = "Stopped feeling excited for 2 mths/longr"
   MANB15D = "Age when feeling excited began this time"
   MANB15DGR = "Grade when feelng xcited began this time"
   MANB15E = "Start feelind excited again> 1 yr ago"
   MANB15GR = "Grade first time you ever felt excited"
   MANB16A = "How often being xcited upset famly/frnds"
   MANB17A = "Often feelng excited prevent famly thngs"
   MANB18A = "Often feelng excited prvent othr thngs"
   MANB19A = "Whn prblms worst-how bad schl/wrk prblms"
   MANB1A = "Excited feeling very diffrent from usual"
   MANB1B = "Excited a lot for as long as 4 days"
   MANB1C = "Have you been excited for 1 wk"
   MANB1D = "Felt excited because of something good"
   MANB1F = "Excited for nothing special"
   MANB1G = "Get into trbl because of being excited"
   MANB1H = "Doctor thght somethng was wrong with you"
   MANB1I = "Been to hospital becaus you were excited"
   MANB1J = "Last 4 wks:felt excited & full of energy"
   MANB20A = "How xcited feeling upset boss/tchr"
   MANB20AYA = "When prblms worst-how bad were prblms"
   MANB20YA = "Whn prblms worst-excited make thngs hard"
   MANB21A = "How bad feeling excited make u feel"
   MANB22A = "Have appointment because you excited"
   MANB24A = "Age when being excited was worst"
   MANB2A = "Was being grouchy vry diffrnt from usual"
   MANB2B = "Been very grouchy for as long as 4 days"
   MANB2C = "Have you been grouchy for 1 wk"
   MANB2D = "Got into troubl because of being grouchy"
   MANB2E = "Doctor thght somethng was wrong with you"
   MANB2F = "Been to hospital becaus you were grouchy"
   MANB2G = "Last 4 wks:felt grouchy/angry"
   MANB3A = "Thinking vry special diffrent from usual"
   MANB3B = "Others thought something wrong with you"
   MANB3C = "Argued with othrs who don't believe you"
   MANB3D = "Last yr:thght u were special whn excited"
   MANB3E = "Last 4wks:thght u were specal-whn xcited"
   MANB4A = "Thinking had special abilities different"
   MANB4B = "Others thought something wrong with you"
   MANB4C = "Thght had sp abilities and can do anytng"
   MANB4D = "Last yr: excited and can do anything"
   MANB4E = "Last 4 wks:thght u had special abilities"
   MANB5A = "Though slept less woke up full of energy"
   MANB5B = "You/othr felt you not getting engh sleep"
   MANB5C = "Last yr:sleep less when excited"
   MANB5D = "Last 4 wks:slept a lot less than usual"
   MANB6A = "When talked too much diffrent from usual"
   MANB6B = "Othrs anoyed becaus you wldn't stop talk"
   MANB6C = "Last yr:talked too much when excited"
   MANB6D = "Last 4 wks: talked too much/quickly"
   MANB7A = "When mind raced was different from usual"
   MANB7B = "Othrs have trbl following what you say"
   MANB7C = "Last yr: mind racing when excited"
   MANB7D = "Last 4 wks: mind racing"
   MANB8A = "Mind prblm was different from usual"
   MANB8B = "Mind problem annoyed others"
   MANB8C = "Mind problem because you notice things"
   MANB8D = "Prblm so much couldn't finish anything"
   MANB8E = "Last yr: hard to keep mind on things"
   MANB8F = "Last 4 wks:how oftn hard-keep mind/thngs"
   MANB9A = "When felt restless was diffrnt frm usual"
   MANB9B = "Inability to keep still annoyed others"
   MANB9C = "Been so restless hard to settle down"
   MANB9D = "Last yr: very restless when excited"
   MANB9E = "Last 4 wks:felt very restless"
   MANBX1 = "Were 2/>2 responses coded in Q3-14"
   MANB23AGR = "Grade when being excited was worst" ;

LENGTH
   VISIT 3                  MANB1 3                  MANB2 3               
   MANB3 3                  MANB4 3                  MANB5 3               
   MANB6 3                  MANB7 3                  MANB8 3               
   MANB9 3                  MANB10 3                 MANB11 3              
   MANB12 3                 MANB13 3                 MANB14 3              
   MANB15 3                 MANB16 3                 MANB17 3              
   MANB18 3                 MANB19 3                 MANB20 3              
   MANB21 3                 MANB22 3                 MANB10A 3             
   MANB10B 3                MANB10C 3                MANB10D 3             
   MANB11A 3                MANB11B 3                MANB11C 3             
   MANB11D 3                MANB12A 3                MANB12B 3             
   MANB12C 3                MANB12D 3                MANB13A 3             
   MANB13B 3                MANB13C 3                MANB13D 3             
   MANB13E 3                MANB13F 3                MANB13G 3             
   MANB13H 3                MANB14B 3                MANB15A 3             
   MANB15B 3                MANB15C 3                MANB15D 3             
   MANB15DGR 3              MANB15E 3                MANB15GR 3            
   MANB16A 3                MANB17A 3                MANB18A 3             
   MANB19A 3                MANB1A 3                 MANB1B 3              
   MANB1C 3                 MANB1D 3                 MANB1F 3              
   MANB1G 3                 MANB1H 3                 MANB1I 3              
   MANB1J 3                 MANB20A 3                MANB20AYA 3           
   MANB20YA 3               MANB21A 3                MANB22A 3             
   MANB24A 3                MANB2A 3                 MANB2B 3              
   MANB2C 3                 MANB2D 3                 MANB2E 3              
   MANB2F 3                 MANB2G 3                 MANB3A 3              
   MANB3B 3                 MANB3C 3                 MANB3D 3              
   MANB3E 3                 MANB4A 3                 MANB4B 3              
   MANB4C 3                 MANB4D 3                 MANB4E 3              
   MANB5A 3                 MANB5B 3                 MANB5C 3              
   MANB5D 3                 MANB6A 3                 MANB6B 3              
   MANB6C 3                 MANB6D 3                 MANB7A 3              
   MANB7B 3                 MANB7C 3                 MANB7D 3              
   MANB8A 3                 MANB8B 3                 MANB8C 3              
   MANB8D 3                 MANB8E 3                 MANB8F 3              
   MANB9A 3                 MANB9B 3                 MANB9C 3              
   MANB9D 3                 MANB9E 3                 MANBX1 3              
   MANB23AGR 3 ;

     

RUN ;
