/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\mddm1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = mddm1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=232;
INPUT
   CENTER $ 1-2             ID $ 3-9                 YMD023B $ 10-11       
   YMD023E $ 12-13          YMD023J $ 14-15          YMD024B $ 16-19       
   YMD001  20               YMD001A  21              YMD001B  22           
   YMD001C  23              YMD001D  24              YMD001E  25           
   YMD002  26               YMD002A  27              YMD002B  28           
   YMD003  29               YMD003A  30              YMD003B  31           
   YMD003C  32              YMD003D  33              YMD004  34            
   YMD004A  35              YMD004B  36              YMD004C  37           
   YMD005  38               YMD005B  39              YMD006  40            
   YMD006A  41              YMD007  42               YMD007B  43           
   YMD008  44               YMD008A  45              YMD008C  46           
   YMD009  47               YMD009B  48              YMD010  49            
   YMD010A  50              YMD010C  51              YMD011  52            
   YMD011A  53              YMD011B  54              YMD011D  55           
   YMD012  56               YMD012B  57              YMD013  58            
   YMD013A  59              YMD013C  60              YMD014  61            
   YMD014B  62              YMD015  63               YMD015A  64           
   YMD015C  65              YMD016  66               YMD016A  67           
   YMD016C  68              YMD017  69               YMD017B  70           
   YMD018  71               YMD018A  72              YMD018C  73           
   YMD019A  74              YMD019C  75              YMD020  76            
   YMD020A  77              YMD020C  78              YMD021  79            
   YMD021E  80              YMD021F  81              YMD022  82            
   YMD022A  83-84           YMD022B  85              YMD022C  86           
   YMD022E  87              YMD023Y  88-89           YMD023Z  90           
   YMD023A  91              YMD023C  92              YMD023D  93           
   YMD023F  94              YMD023G  95              YMD023HY  96-97       
   YMD023HZ  98             YMD023I  99              YMD024  100           
   YMD024C  101             YMD024D  102             YMD024E  103          
   YMD024F  104             YMD025  105              YMD025A  106          
   YMD025B  107             YMD025C  108             YMD025D  109          
   YMD025E  110             YMD025F  111             YMD025G  112          
   YMD025H  113             YMD025I  114             YMD025J  115          
   YMD025K  116             YMD025L  117             YMD025M  118          
   YMD026  119              YMD026A  120             YMD027  121           
   YMD027A  122             YMD028  123              YMD028A  124          
   YMD029  125              YMD029A  126             YMD030  127           
   YMD030A  128             YMD031  129              YMD031A  130          
   YMD032  131              YMD032A  132             YMD034  133           
   YMD034A  134             YMD034B  135             YMD034C  136          
   YMD034D  137             YMD034E  138             YMD034F  139          
   YMD035  140              YMD035A  141             YMD035B  142          
   YMD035C  143             YMD035D  144             YMD035E  145          
   YMD036  146              YMD036A  147             YMD037  148           
   YMD037A  149             YMD038  150              YMD039  151           
   YMD040  152              YMD040A  153             YMD041  154           
   YMD041A  155             YMD042  156              YMD043  157           
   YMD044  158              YMD045  159              YMD046  160           
   YMD047  161              YMD048  162              YMD049  163           
   YMD049A  164             YMD050Y  165-166         YMD050Z  167          
   YMD050A  168             YMD050B  169             YMD050C  170          
   YMD050DY  171            YMD050DZ  172            YMD050E  173          
   VISIT  174-175           YMD019  176              YMD022D  177          
   YMD024A  178             YMD051  179              YMD051A  180          
   YMD052  181              YMD052A  182             YMD053  183           
   YMD053A  184             YMD054  185              YMD054A  186          
   YMD055  187              YMD055A  188             YMD056  189           
   YMD056A  190             YMD057  191              YMD057A  192          
   YMD059  193              YMD059A  194             YMD059B  195          
   YMD059C  196             YMD058  197              YMD058A  198          
   YMDA1M  199              YMDA2M  200              YMDA3M  201           
   YMDA4M  202              YMDA5M  203              YMDA6M  204           
   YMDA7M  205              YMDA8M  206              YMDA9M  207           
   YMDEM  208               YMDM  209                YDYAM  210            
   YDYB1  211               YDYB2  212               YDYB3  213            
   YDYB4  214               YDYB5  215               YDYB6  216            
   YDYB  217                YDYC  218                YDYDM  219            
   YDYM  220                YMDMIMA  221             YMDMIMB  222          
   YMDMIMC  223             YMDMIMD  224             YDYMIMA  225          
   YDYMIMB  226             YDYMIMC  227             YDYMIMD  228          
   YMDCRITM  229            YMDSYMP  230-231         YDYCRITM  232         
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   YMD023B = "Month you began to feel sad >1yr ago"
   YMD023E = "Month began to feel sad etc. again"
   YMD023J = "Month you began to fee; sad etc"
   YMD024B = "When did s/he die"
   YMD001 = "Last 4 wks: often felt sad/depressed"
   YMD001A = "Last 4 wks: sad/deprsd long tm each day"
   YMD001B = "Feel sad/depressed most of the day"
   YMD001C = "Last 4 wks: sad/deprsd almost every day"
   YMD001D = "Felt sad/depressed every day 2 wks/lngr"
   YMD001E = "Feel better if something good happens"
   YMD002 = "Last 4 wks: time when nothing was fun"
   YMD002A = "Felt nothing was fun almost every day"
   YMD002B = "Felt nothing was fun every day 2 wk/lngr"
   YMD003 = "Last 4 wks: felt grouchy/irritable"
   YMD003A = "Last 4 wks: grouchy long time each day"
   YMD003B = "Feel grouchy most of the day"
   YMD003C = "Time felt grouchy almost every day"
   YMD003D = "Felt grouchy every day for 2 wks/lngr"
   YMD004 = "Last 4 wks: have you lost weight"
   YMD004A = "Have you been trying to lose weight"
   YMD004B = "Last 4 wks: lost weight when not trying"
   YMD004C = "Lost so much weight that people noticed"
   YMD005 = "Last 4 wks: have you lost your appetite"
   YMD005B = "Lost appetite every day for 2 wks/longer"
   YMD006 = "Have you gained weight"
   YMD006A = "Gained so much weight tht people noticed"
   YMD007 = "Feel much hungrier than usual"
   YMD007B = "Felt hungrier every day for 2 wks/longr"
   YMD008 = "Last 4 wks: had trouble sleeping"
   YMD008A = "Disc generated field"
   YMD008C = "Trouble sleeping evry night 2 wks/ longr"
   YMD009 = "Sleep more during the day than usual"
   YMD009B = "Slept more durng day evry dy 2 wks/longr"
   YMD010 = "Do you often feel slowed down"
   YMD010A = "Other people notice you are slowed down"
   YMD010C = "Felt slowed down every day 2 wks/longr"
   YMD011 = "Last 4 wks: often felt restless"
   YMD011A = "When felt restless different from usual"
   YMD011B = "Other people notice you are restless"
   YMD011D = "Felt restless every day 2 wks/ longr"
   YMD012 = "Do you have less energy than you usual"
   YMD012B = "Had less energy evry day for 2 wks/longr"
   YMD013 = "Doing little things make you feel tired"
   YMD013A = "Disc generated field"
   YMD013C = "Felt tired every day for 2 wks/longr"
   YMD014 = "Last 4 wks: arms and legs felt heavy"
   YMD014B = "Arms/legs felt heavy evry day 2 wks/lngr"
   YMD015 = "Blame yourself for bad thngs that happen"
   YMD015A = "Is blaming yourself different from usual"
   YMD015C = "Blamed yourself evry day for 2 wks/longr"
   YMD016 = "Can't do things well/not smart as others"
   YMD016A = "Feelng bad about self diffrent frm usual"
   YMD016C = "Felt bad about self every day 2 wks/lngr"
   YMD017 = "Last 4 wks: couldn't think clearly/fast"
   YMD017B = "Couldn't think clearly evry dy 2wks/lngr"
   YMD018 = "Have trouble keeping mind on schl/work"
   YMD018A = "Mind trbl re: work different from usual"
   YMD018C = "Have mind trbl evry day for 2 wks/longer"
   YMD019A = "Hard making up mind different to usual"
   YMD019C = "Hard to make up mind evry dy 2 wks/longr"
   YMD020 = "Last 4 wks: often thought about death"
   YMD020A = "Do you think about death more than usual"
   YMD020C = "Thought about death every dy 2 wks/longr"
   YMD021 = "Think seriously about killing yourself"
   YMD021E = "Last 4 wks: thought about killing self"
   YMD021F = "Plan exactly how you will kill yourself"
   YMD022 = "Have you ever tried to kill yourself"
   YMD022A = "No. of  times tried to kill yourself"
   YMD022B = "Last 4 wks: tried to kill yourself"
   YMD022C = "Last 4 wks: # times tried to kill self"
   YMD022E = "Did you go to see a doctor"
   YMD023Y = "Age 1st time felt sad etc"
   YMD023Z = "Grade 1st time felt sad etc"
   YMD023A = "Were you sad etc. more than 1 year ago"
   YMD023C = "Ever stopped feeling sad since started"
   YMD023D = "Felt sad etc for 2 mths/longer"
   YMD023F = "Time stopped feeling sad since 1st time"
   YMD023G = "Stopped feeling sad for 2 mths/longr"
   YMD023HY = "Last mth: age feeling sad etc. started"
   YMD023HZ = "Last mth: grade feeling sad etc. started"
   YMD023I = "Started feeling sad etc. > 1yr ago"
   YMD024 = "Sad feeling started aftr someone's death"
   YMD024C = "Sad etc. 2mths/longr after person died"
   YMD024D = "Felt sad etc. before person died"
   YMD024E = "Was that in the last year"
   YMD024F = "Sad etc. 2 wks/longr when person died"
   YMD025 = "Last 2 yrs: felt sad, better, sad again"
   YMD025A = "Start to become sad same time each yr"
   YMD025B = "Was this in Winter or Fall"
   YMD025C = "Stayed sad until Spring or Summer"
   YMD025D = "Got better in Spring or Summer"
   YMD025E = "Got hyper/excited in Spring or Summer"
   YMD025F = "Last 2 yrs: become sad other times of yr"
   YMD025G = "Times lasted 2 wks/more"
   YMD025H = "Sad feeling in Spring and Summer"
   YMD025I = "Stayed sad until Fall/Winter"
   YMD025J = "Started to get better in Fall or Winter"
   YMD025K = "Got hyper in Fall or Winter"
   YMD025L = "Last 2 yrs: became sad in Fall or Winter"
   YMD025M = "Last 2 yrs: sad times lasted 2 wks/more"
   YMD026 = "Last 4 wks: feeling sad upset caretakers"
   YMD026A = "How often sad feeling upset caretakers"
   YMD027 = "Sad feeling prevent family things"
   YMD027A = "Often sad feeling prevent family things"
   YMD028 = "Sad feeling prevent family things"
   YMD028A = "Often sad feeling prevent family things"
   YMD029 = "Does feeling sad make you feel bad"
   YMD029A = "How sad feeling sad make you feel"
   YMD030 = "Last 4 wks: sad feelng make wrk difficlt"
   YMD030A = "How bad schl/wrk prblm due to sad feelng"
   YMD031 = "Sad feeling upset teacher/boss"
   YMD031A = "How often sad feeling upset teacher/boss"
   YMD032 = "Seen someone in hospital in last year"
   YMD032A = "Have appointment because of feeling sad"
   YMD034 = "Last yr: felt sad a lot of the time"
   YMD034A = "Last yr: felt sad more days than felt ok"
   YMD034B = "Felt sad for as long as 1 yr"
   YMD034C = "Felt sad for as long as 2 yrs"
   YMD034D = "Felt sad most of day when feeling sad"
   YMD034E = "Felt better when something good happened"
   YMD034F = "Last 4 wks: felt sad /depressed"
   YMD035 = "Last yr: felt grouchy a lot of the time"
   YMD035A = "Last yr: felt grouchy more days than ok"
   YMD035B = "Felt grouchy as long as 1 yr"
   YMD035C = "Felt grouchy as long as 2 yrs"
   YMD035D = "Felt grouchy most of day when grouchy"
   YMD035E = "Last 4 wks: felt grouchy/irritable"
   YMD036 = "When sad etc: eat less/lose appetite"
   YMD036A = "When sad etc: feel hungry/eat too much"
   YMD037 = "When sad etc: trouble falling asleep"
   YMD037A = "When sad etc: sleep too much"
   YMD038 = "When sad etc: feel you don't have energy"
   YMD039 = "When sad etc: feel bad about self"
   YMD040 = "When sad etc: difficult to pay attention"
   YMD040A = "When sad etc: difficult to make up mind"
   YMD041 = "When sad etc: feel that life is hopeless"
   YMD041A = "When sad etc: feel nothng good will hppn"
   YMD042 = "When sad etc: feel you are about to cry"
   YMD043 = "When sad etc: seem like nothing is fun"
   YMD044 = "When sad etc: feel bored"
   YMD045 = "When sad etc: hard to do ordinary things"
   YMD046 = "When sad etc: think about bad things"
   YMD047 = "When sad: want to be alone"
   YMD048 = "When sad: talk a lot less"
   YMD049 = "Last year: felt better/like normal self"
   YMD049A = "Felt better/normal self for 2 mths/longr"
   YMD050Y = "Age 1st time you had 1 yr of feeling sad"
   YMD050Z = "Grd 1st time you had 1 yr of feeling sad"
   YMD050A = "Were you sad/depressed> 1yr ago"
   YMD050B = "Sad feelings ever went away completely"
   YMD050C = "Sad feelings went away for 2 mths/longr"
   YMD050DY = "Age sad feelings began again"
   YMD050DZ = "Grade sad feelings began again"
   YMD050E = "Started feeling sad again >1yr ago"
   VISIT = "VISIT NUMBER"
   YMD019 = "Hard to make up mind/make decisions"
   YMD022D = "How did you try to kill yourself"
   YMD024A = "Who died"
   YMD051 = "Last 4 wks: sad feelings upset caretaker"
   YMD051A = "How often sad feelings upset caretaker"
   YMD052 = "Does sad feeling prevent family things"
   YMD052A = "Often sad feelings prevent family things"
   YMD053 = "Does sad feeling prevent other things"
   YMD053A = "Often sad feeling prevent other things"
   YMD054 = "Does feeling sad make you feel bad"
   YMD054A = "How bad does feeling sad make you feel"
   YMD055 = "Last 4 wks: sad feelng make wrk difficlt"
   YMD055A = "How bad are/were schl/wrk problems"
   YMD056 = "Sad feelings upset teacher/boss"
   YMD056A = "How often sad feelings upset teachr/boss"
   YMD057 = "Seen someone in hospital in last year"
   YMD057A = "Have appointment because of sad feelings"
   YMD059 = "Feel bad/upset if left out of something"
   YMD059A = "Stay feeling bad/upset for > 1 day"
   YMD059B = "Dropped friend because they left you out"
   YMD059C = "Dropped > 2 friends because left you out"
   YMD058 = "Who did you/ are you going to see"
   YMD058A = "What person you saw say the matter was"
   YMDA1M = "Depressed mood or irritable mood"
   YMDA2M = "Diminished interest or pleasure"
   YMDA3M = "Weight loss or weight gain or appetite change"
   YMDA4M = "Insomnia or hypersomnia"
   YMDA5M = "Psychomotor agitation or retardation"
   YMDA6M = "Fatigue or loss of energy"
   YMDA7M = "Worthlessness or guilt"
   YMDA8M = "Thinking or concentration problems or indecisiveness"
   YMDA9M = "Thoughts of death, suicidal ideation, suicide attempt or plan"
   YMDEM = "Not due to Bereavement"
   YMDM = "Diagnosis for major depression disorder"
   YDYAM = "Depressed mood or irritable mood"
   YDYB1 = "Poor appetite or overeating"
   YDYB2 = "Insomnia or hypersomnia"
   YDYB3 = "Low energy or fatigue"
   YDYB4 = "Low self-esteem"
   YDYB5 = "Poor concentration or difficulty making decisions"
   YDYB6 = "Feelings of hopelessness"
   YDYB = "Two symptoms when depressed"
   YDYC = "Never without symptoms for more than 2 months"
   YDYDM = "Not major depression"
   YDYM = "Diagnosis for dysthymic disorder"
   YMDMIMA = "Impairment A: Major Depressive Episode"
   YMDMIMB = "Impairment B: Major Depressive Episode"
   YMDMIMC = "Impairment C: Major Depressive Episode"
   YMDMIMD = "Impairment D: Major Depressive Episode"
   YDYMIMA = "Impairment A: Dysthymic Disorder"
   YDYMIMB = "Impairment B: Dysthymic Disorder"
   YDYMIMC = "Impairment C: Dysthymic Disorder"
   YDYMIMD = "Impairment D: Dysthymic Disorder"
   YMDCRITM = "MDD Criterion Count"
   YMDSYMP = "MDD Symptom Count"
   YDYCRITM = "Dysthymic Disorder Criterion Count" ;

LENGTH
   YMD001 3                 YMD001A 3                YMD001B 3             
   YMD001C 3                YMD001D 3                YMD001E 3             
   YMD002 3                 YMD002A 3                YMD002B 3             
   YMD003 3                 YMD003A 3                YMD003B 3             
   YMD003C 3                YMD003D 3                YMD004 3              
   YMD004A 3                YMD004B 3                YMD004C 3             
   YMD005 3                 YMD005B 3                YMD006 3              
   YMD006A 3                YMD007 3                 YMD007B 3             
   YMD008 3                 YMD008A 3                YMD008C 3             
   YMD009 3                 YMD009B 3                YMD010 3              
   YMD010A 3                YMD010C 3                YMD011 3              
   YMD011A 3                YMD011B 3                YMD011D 3             
   YMD012 3                 YMD012B 3                YMD013 3              
   YMD013A 3                YMD013C 3                YMD014 3              
   YMD014B 3                YMD015 3                 YMD015A 3             
   YMD015C 3                YMD016 3                 YMD016A 3             
   YMD016C 3                YMD017 3                 YMD017B 3             
   YMD018 3                 YMD018A 3                YMD018C 3             
   YMD019A 3                YMD019C 3                YMD020 3              
   YMD020A 3                YMD020C 3                YMD021 3              
   YMD021E 3                YMD021F 3                YMD022 3              
   YMD022A 3                YMD022B 3                YMD022C 3             
   YMD022E 3                YMD023Y 3                YMD023Z 3             
   YMD023A 3                YMD023C 3                YMD023D 3             
   YMD023F 3                YMD023G 3                YMD023HY 3            
   YMD023HZ 3               YMD023I 3                YMD024 3              
   YMD024C 3                YMD024D 3                YMD024E 3             
   YMD024F 3                YMD025 3                 YMD025A 3             
   YMD025B 3                YMD025C 3                YMD025D 3             
   YMD025E 3                YMD025F 3                YMD025G 3             
   YMD025H 3                YMD025I 3                YMD025J 3             
   YMD025K 3                YMD025L 3                YMD025M 3             
   YMD026 3                 YMD026A 3                YMD027 3              
   YMD027A 3                YMD028 3                 YMD028A 3             
   YMD029 3                 YMD029A 3                YMD030 3              
   YMD030A 3                YMD031 3                 YMD031A 3             
   YMD032 3                 YMD032A 3                YMD034 3              
   YMD034A 3                YMD034B 3                YMD034C 3             
   YMD034D 3                YMD034E 3                YMD034F 3             
   YMD035 3                 YMD035A 3                YMD035B 3             
   YMD035C 3                YMD035D 3                YMD035E 3             
   YMD036 3                 YMD036A 3                YMD037 3              
   YMD037A 3                YMD038 3                 YMD039 3              
   YMD040 3                 YMD040A 3                YMD041 3              
   YMD041A 3                YMD042 3                 YMD043 3              
   YMD044 3                 YMD045 3                 YMD046 3              
   YMD047 3                 YMD048 3                 YMD049 3              
   YMD049A 3                YMD050Y 3                YMD050Z 3             
   YMD050A 3                YMD050B 3                YMD050C 3             
   YMD050DY 3               YMD050DZ 3               YMD050E 3             
   VISIT 3                  YMD019 3                 YMD022D 3             
   YMD024A 3                YMD051 3                 YMD051A 3             
   YMD052 3                 YMD052A 3                YMD053 3              
   YMD053A 3                YMD054 3                 YMD054A 3             
   YMD055 3                 YMD055A 3                YMD056 3              
   YMD056A 3                YMD057 3                 YMD057A 3             
   YMD059 3                 YMD059A 3                YMD059B 3             
   YMD059C 3                YMD058 3                 YMD058A 3             
   YMDA1M 3                 YMDA2M 3                 YMDA3M 3              
   YMDA4M 3                 YMDA5M 3                 YMDA6M 3              
   YMDA7M 3                 YMDA8M 3                 YMDA9M 3              
   YMDEM 3                  YMDM 3                   YDYAM 3               
   YDYB1 3                  YDYB2 3                  YDYB3 3               
   YDYB4 3                  YDYB5 3                  YDYB6 3               
   YDYB 3                   YDYC 3                   YDYDM 3               
   YDYM 3                   YMDMIMA 3                YMDMIMB 3             
   YMDMIMC 3                YMDMIMD 3                YDYMIMA 3             
   YDYMIMB 3                YDYMIMC 3                YDYMIMD 3             
   YMDCRITM 3               YMDSYMP 3                YDYCRITM 3 ;

      

RUN ;
