/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\mffm0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = mffm0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=1140;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   mff1b1 $ 11-13           mff1b1a $ 14             mff1b2 $ 15-17        
   mff1b2a $ 18             mff1b3 $ 19-21           mff1b3a $ 22          
   mff1b4 $ 23-25           mff1b4a $ 26             mff1b5 $ 27-29        
   mff1b5a $ 30             mff1b6 $ 31-33           mff1b6a $ 34          
   mff1b7 $ 35-37           mff1b7a $ 38             mff1b8 $ 39-41        
   mff1b8a $ 42             mff1b9 $ 43-45           mff1b9a $ 46          
   mff1b10 $ 47-49          mff1b10a $ 50            mff1b11 $ 51-53       
   mff1b11a $ 54            mff1b12 $ 55-57          mff1b12a $ 58         
   mff1b1n $ 59-61          mff1b1na $ 62            mff1b2n $ 63-65       
   mff1b2na $ 66            mff1b3n $ 67-69          mff1b3na $ 70         
   mff1b4n $ 71-73          mff1b4na $ 74            mff1b5n $ 75-77       
   mff1b5na $ 78            mff1b6n $ 79-81          mff1b6na $ 82         
   mff1b1b  83              mff1b2b  84              mff1b3b  85           
   mff1b4b  86              mff1b5b  87              mff1b6b  88           
   mff1b7b  89              mff1b8b  90              mff1b9b  91           
   mff1b10b  92             mff1b11b  93             mff1b12b  94          
   mff1a12d  95             mff1b1nb  96             mff1b2nb  97          
   mff1b3nb  98             mff1b4nb  99             mff1b5nb  100         
   mff1b6nb  101            mff1c1  102-103          mff1c2  104-105       
   mff1c3  106-107          mff1c4  108-109          mff1c5  110-111       
   mff1c6  112-113          mff1c7  114-115          mff1c8  116-117       
   mff1c9  118-119          mff1c10  120-121         mff1c11  122-123      
   mff1c12  124-125         mff2b1 $ 126-128         mff2b1a $ 129         
   mff2b2 $ 130-132         mff2b2a $ 133            mff2b3 $ 134-136      
   mff2b3a $ 137            mff2b4 $ 138-140         mff2b4a $ 141         
   mff2b5 $ 142-144         mff2b5a $ 145            mff2b6 $ 146-148      
   mff2b6a $ 149            mff2b7 $ 150-152         mff2b7a $ 153         
   mff2b8 $ 154-156         mff2b8a $ 157            mff2b9 $ 158-160      
   mff2b9a $ 161            mff2b10 $ 162-164        mff2b10a $ 165        
   mff2b11 $ 166-168        mff2b11a $ 169           mff2b12 $ 170-172     
   mff2b12a $ 173           mff2b1n $ 174-176        mff2b1na $ 177        
   mff2b2n $ 178-180        mff2b2na $ 181           mff2b3n $ 182-184     
   mff2b3na $ 185           mff2b4n $ 186-188        mff2b4na $ 189        
   mff2b5n $ 190-192        mff2b5na $ 193           mff2b6n $ 194-196     
   mff2b6na $ 197           mff2b1b  198             mff2b2b  199          
   mff2b3b  200             mff2b4b  201             mff2b5b  202          
   mff2b6b  203             mff2b7b  204             mff2b8b  205          
   mff2b9b  206             mff2b10b  207            mff2b11b  208         
   mff2b12b  209            mff2a12d  210            mff2b1nb  211         
   mff2b2nb  212            mff2b3nb  213            mff2b4nb  214         
   mff2b5nb  215            mff2b6nb  216            mff2c1  217-218       
   mff2c2  219-220          mff2c3  221-222          mff2c4  223-224       
   mff2c5  225-226          mff2c6  227-228          mff2c7  229-230       
   mff2c8  231-232          mff2c9  233-234          mff2c10  235-236      
   mff2c11  237-238         mff2c12  239-240         mff3b1 $ 241-243      
   mff3b1a $ 244            mff3b2 $ 245-247         mff3b2a $ 248         
   mff3b3 $ 249-251         mff3b3a $ 252            mff3b4 $ 253-255      
   mff3b4a $ 256            mff3b5 $ 257-259         mff3b5a $ 260         
   mff3b6 $ 261-263         mff3b6a $ 264            mff3b7 $ 265-267      
   mff3b7a $ 268            mff3b8 $ 269-271         mff3b8a $ 272         
   mff3b9 $ 273-275         mff3b9a $ 276            mff3b10 $ 277-279     
   mff3b10a $ 280           mff3b11 $ 281-283        mff3b11a $ 284        
   mff3b12 $ 285-287        mff3b12a $ 288           mff3b1n $ 289-291     
   mff3b1na $ 292           mff3b2n $ 293-295        mff3b2na $ 296        
   mff3b3n $ 297-299        mff3b3na $ 300           mff3b4n $ 301-303     
   mff3b4na $ 304           mff3b5n $ 305-307        mff3b5na $ 308        
   mff3b6n $ 309-311        mff3b6na $ 312           mff3b1b  313          
   mff3b2b  314             mff3b3b  315             mff3b4b  316          
   mff3b5b  317             mff3b6b  318             mff3b7b  319          
   mff3b8b  320             mff3b9b  321             mff3b10b  322         
   mff3b11b  323            mff3b12b  324            mff3a12d  325         
   mff3b1nb  326            mff3b2nb  327            mff3b3nb  328         
   mff3b4nb  329            mff3b5nb  330            mff3b6nb  331         
   mff3c1  332-333          mff3c2  334-335          mff3c3  336-337       
   mff3c4  338-339          mff3c5  340-341          mff3c6  342-343       
   mff3c7  344-345          mff3c8  346-347          mff3c9  348-349       
   mff3c10  350-351         mff3c11  352-353         mff3c12  354-355      
   mff4b1 $ 356-358         mff4b1a $ 359            mff4b2 $ 360-362      
   mff4b2a $ 363            mff4b3 $ 364-366         mff4b3a $ 367         
   mff4b4 $ 368-370         mff4b4a $ 371            mff4b5 $ 372-374      
   mff4b5a $ 375            mff4b6 $ 376-378         mff4b6a $ 379         
   mff4b7 $ 380-382         mff4b7a $ 383            mff4b8 $ 384-386      
   mff4b8a $ 387            mff4b9 $ 388-390         mff4b9a $ 391         
   mff4b10 $ 392-394        mff4b10a $ 395           mff4b11 $ 396-398     
   mff4b11a $ 399           mff4b12 $ 400-402        mff4b12a $ 403        
   mff4b1n $ 404-406        mff4b1na $ 407           mff4b2n $ 408-410     
   mff4b2na $ 411           mff4b3n $ 412-414        mff4b3na $ 415        
   mff4b4n $ 416-418        mff4b4na $ 419           mff4b5n $ 420-422     
   mff4b5na $ 423           mff4b6n $ 424-426        mff4b6na $ 427        
   mff4b1b  428             mff4b2b  429             mff4b3b  430          
   mff4b4b  431             mff4b5b  432             mff4b6b  433          
   mff4b7b  434             mff4b8b  435             mff4b9b  436          
   mff4b10b  437            mff4b11b  438            mff4b12b  439         
   mff4a12d  440            mff4b1nb  441            mff4b2nb  442         
   mff4b3nb  443            mff4b4nb  444            mff4b5nb  445         
   mff4b6nb  446            mff4c1  447-448          mff4c2  449-450       
   mff4c3  451-452          mff4c4  453-454          mff4c5  455-456       
   mff4c6  457-458          mff4c7  459-460          mff4c8  461-462       
   mff4c9  463-464          mff4c10  465-466         mff4c11  467-468      
   mff4c12  469-470         mff5b1 $ 471-473         mff5b1a $ 474         
   mff5b2 $ 475-477         mff5b2a $ 478            mff5b3 $ 479-481      
   mff5b3a $ 482            mff5b4 $ 483-485         mff5b4a $ 486         
   mff5b5 $ 487-489         mff5b5a $ 490            mff5b6 $ 491-493      
   mff5b6a $ 494            mff5b7 $ 495-497         mff5b7a $ 498         
   mff5b8 $ 499-501         mff5b8a $ 502            mff5b9 $ 503-505      
   mff5b9a $ 506            mff5b10 $ 507-509        mff5b10a $ 510        
   mff5b11 $ 511-513        mff5b11a $ 514           mff5b12 $ 515-517     
   mff5b12a $ 518           mff5b1n $ 519-521        mff5b1na $ 522        
   mff5b2n $ 523-525        mff5b2na $ 526           mff5b3n $ 527-529     
   mff5b3na $ 530           mff5b4n $ 531-533        mff5b4na $ 534        
   mff5b5n $ 535-537        mff5b5na $ 538           mff5b6n $ 539-541     
   mff5b6na $ 542           mff5b1b  543             mff5b2b  544          
   mff5b3b  545             mff5b4b  546             mff5b5b  547          
   mff5b6b  548             mff5b7b  549             mff5b8b  550          
   mff5b9b  551             mff5b10b  552            mff5b11b  553         
   mff5b12b  554            mff5a12d  555            mff5b1nb  556         
   mff5b2nb  557            mff5b3nb  558            mff5b4nb  559         
   mff5b5nb  560            mff5b6nb  561            mff5c1  562-563       
   mff5c2  564-565          mff5c3  566-567          mff5c4  568-569       
   mff5c5  570-571          mff5c6  572-573          mff5c7  574-575       
   mff5c8  576-577          mff5c9  578-579          mff5c10  580-581      
   mff5c11  582-583         mff5c12  584-585         mff6b1 $ 586-588      
   mff6b1a $ 589            mff6b2 $ 590-592         mff6b2a $ 593         
   mff6b3 $ 594-596         mff6b3a $ 597            mff6b4 $ 598-600      
   mff6b4a $ 601            mff6b5 $ 602-604         mff6b5a $ 605         
   mff6b6 $ 606-608         mff6b6a $ 609            mff6b7 $ 610-612      
   mff6b7a $ 613            mff6b8 $ 614-616         mff6b8a $ 617         
   mff6b9 $ 618-620         mff6b9a $ 621            mff6b10 $ 622-624     
   mff6b10a $ 625           mff6b11 $ 626-628        mff6b11a $ 629        
   mff6b12 $ 630-632        mff6b12a $ 633           mff6b1n $ 634-636     
   mff6b1na $ 637           mff6b2n $ 638-640        mff6b2na $ 641        
   mff6b3n $ 642-644        mff6b3na $ 645           mff6b4n $ 646-648     
   mff6b4na $ 649           mff6b5n $ 650-652        mff6b5na $ 653        
   mff6b6n $ 654-656        mff6b6na $ 657           mff7 $ 658-660        
   mff6b1b  661             mff6b2b  662             mff6b3b  663          
   mff6b4b  664             mff6b5b  665             mff6b6b  666          
   mff6b7b  667             mff6b8b  668             mff6b9b  669          
   mff6b10b  670            mff6b11b  671            mff6b12b  672         
   mff6a12d  673            mff6b1nb  674            mff6b2nb  675         
   mff6b3nb  676            mff6b4nb  677            mff6b5nb  678         
   mff6b6nb  679            mff6c1  680-681          mff6c2  682-683       
   mff6c3  684-685          mff6c4  686-687          mff6c5  688-689       
   mff6c6  690-691          mff6c7  692-693          mff6c8  694-695       
   mff6c9  696-697          mff6c10  698-699         mff6c11  700-701      
   mff6c12  702-703         mff8 DATE11.             mff1aa $ 715          
   mff6aa $ 716             mffemot1  717-732        mffconfl  733-748     
   mffemot2  749-764        mffemot3  765-780        mffemot4  781-796     
   mffemot5  797-812        n_emot1  813-814         n_confl  815-816      
   n_emot2  817-818         n_emot3  819-820         n_emot4  821-822      
   n_emot5  823-824         mffme1  825-826          mffme2  827-828       
   mffme3  829-830          mffme4  831-832          mffme5  833-834       
   mffmc  835-836           mfffe1  837-838          mfffe2  839-840       
   mfffe3  841-842          mfffe4  843-844          mfffe5  845-846       
   mfffc  847-848           mffgme1  849-850         mffgme2  851-852      
   mffgme3  853-854         mffgme4  855-856         mffgme5  857-858      
   mffgmc  859-860          mffgfe1  861-862         mffgfe2  863-864      
   mffgfe3  865-866         mffgfe4  867-868         mffgfe5  869-870      
   mffgfc  871-872          mffbe1  873-874          mffbe2  875-876       
   mffbe3  877-878          mffbe4  879-880          mffbe5  881-882       
   mffbc  883-884           mffse1  885-886          mffse2  887-888       
   mffse3  889-890          mffse4  891-892          mffse5  893-894       
   mffsc  895-896           mffore1  897-898         mffore2  899-900      
   mffore3  901-902         mffore4  903-904         mffore5  905-906      
   mfforc  907-908          mffoae1  909-910         mffoae2  911-912      
   mffoae3  913-914         mffoae4  915-916         mffoae5  917-918      
   mffoac  919-920          mffoce1  921-922         mffoce2  923-924      
   mffoce3  925-926         mffoce4  927-928         mffoce5  929-930      
   mffocc  931-932          mffte1  933-934          mffte2  935-936       
   mffte3  937-938          mffte4  939-940          mffte5  941-942       
   mfftc  943-944           mffmemt  945-960         mfffemt  961-976      
   mffgmemt  977-992        mffgfemt  993-1008       mffbemt  1009-1024    
   mffsemt  1025-1041       mfforemt  1042-1057      mffoaemt  1058-1073   
   mffocemt  1074-1090      mfftemt  1091-1107       rca7b2 $ 1108-1139    
   rca7b1  1140           ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   mff1b1 = "talk about feelings/role code #1"
   mff1b1a = "talk about feelings/relationship code #1"
   mff1b2 = "talk about feelings/role code #2"
   mff1b2a = "talk about feelings/relationship code #2"
   mff1b3 = "talk about feelings/role code #3"
   mff1b3a = "talk about feelings/relationship code #3"
   mff1b4 = "talk about feelings/role code #4"
   mff1b4a = "talk about feelings/relationship code #4"
   mff1b5 = "talk about feelings/role code #5"
   mff1b5a = "talk about feelings/relationship code #5"
   mff1b6 = "talk about feelings/role code #6"
   mff1b6a = "talk about feelings/relationship code #6"
   mff1b7 = "talk about feelings/role code #7"
   mff1b7a = "talk about feelings/relationship code #7"
   mff1b8 = "talk about feelings/role code #8"
   mff1b8a = "talk about feelings/relationship code #8"
   mff1b9 = "talk about feelings/role code #9"
   mff1b9a = "talk about feelings/relationship code #9"
   mff1b10 = "talk about feelings/role code #10"
   mff1b10a = "talk about feelings/relationshp code #10"
   mff1b11 = "talk about feelings/role code #11"
   mff1b11a = "talk about feelings/relationshp code #11"
   mff1b12 = "talk about feelings/role code #12"
   mff1b12a = "talk about feelings/relationshp code #12"
   mff1b1n = "talk feelings/unranked role code #1"
   mff1b1na = "talk feelngs/unrank relationshp code #1"
   mff1b2n = "talk feelings/unranked role code #2"
   mff1b2na = "talk feelngs/unrank relationshp code #2"
   mff1b3n = "talk feelings/unranked role code #3"
   mff1b3na = "talk feelngs/unrank relationshp code #3"
   mff1b4n = "talk feelings/unranked role code #4"
   mff1b4na = "talk feelngs/unrank relationshp code #4"
   mff1b5n = "talk feelings/unranked role code #5"
   mff1b5na = "talk feelngs/unrank relationshp code #5"
   mff1b6n = "talk feelings/unranked role code #6"
   mff1b6na = "talk feelngs/unrank relationshp code #6"
   mff1b1b = "talk about feelings/order within role #1"
   mff1b2b = "talk about feelings/order within role #2"
   mff1b3b = "talk about feelings/order within role #3"
   mff1b4b = "talk about feelings/order within role #4"
   mff1b5b = "talk about feelings/order within role #5"
   mff1b6b = "talk about feelings/order within role #6"
   mff1b7b = "talk about feelings/order within role #7"
   mff1b8b = "talk about feelings/order within role #8"
   mff1b9b = "talk about feelings/order within role #9"
   mff1b10b = "talk about feelings/order within role 10"
   mff1b11b = "talk about feelings/order within role 11"
   mff1b12b = "talk about feelings/order within role 12"
   mff1a12d = "talk feelings/anyone child hasn^t ranked"
   mff1b1nb = "talk feelings/unrank order within role 1"
   mff1b2nb = "talk feelings/unrank order within role 2"
   mff1b3nb = "talk feelings/unrank order within role 3"
   mff1b4nb = "talk feelings/unrank order within role 4"
   mff1b5nb = "talk feelings/unrank order within role 5"
   mff1b6nb = "talk feelings/unrank order within role 6"
   mff1c1 = "talk about feelings/rating for person #1"
   mff1c2 = "talk about feelings/rating for person #2"
   mff1c3 = "talk about feelings/rating for person #3"
   mff1c4 = "talk about feelings/rating for person #4"
   mff1c5 = "talk about feelings/rating for person #5"
   mff1c6 = "talk about feelings/rating for person #6"
   mff1c7 = "talk about feelings/rating for person #7"
   mff1c8 = "talk about feelings/rating for person #8"
   mff1c9 = "talk about feelings/rating for person #9"
   mff1c10 = "talk about feelngs/rating for person #10"
   mff1c11 = "talk about feelngs/rating for person #11"
   mff1c12 = "talk about feelngs/rating for person #12"
   mff2b1 = "get upset with/role code #1"
   mff2b1a = "get upset with/relationship code #1"
   mff2b2 = "get upset with/role code #2"
   mff2b2a = "get upset with/relationship code #2"
   mff2b3 = "get upset with/role code #3"
   mff2b3a = "get upset with/relationship code #3"
   mff2b4 = "get upset with/role code #4"
   mff2b4a = "get upset with/relationship code #4"
   mff2b5 = "get upset with/role code #5"
   mff2b5a = "get upset with/relationship code #5"
   mff2b6 = "get upset with/role code #6"
   mff2b6a = "get upset with/relationship code #6"
   mff2b7 = "get upset with/role code #7"
   mff2b7a = "get upset with/relationship code #7"
   mff2b8 = "get upset with/role code #8"
   mff2b8a = "get upset with/relationship code #8"
   mff2b9 = "get upset with/role code #9"
   mff2b9a = "get upset with/relationship code #9"
   mff2b10 = "get upset with/role code #10"
   mff2b10a = "get upset with/relationship code #10"
   mff2b11 = "get upset with/role code #11"
   mff2b11a = "get upset with/relationship code #11"
   mff2b12 = "get upset with/role code #12"
   mff2b12a = "get upset with/relationship code #12"
   mff2b1n = "get upset with/unranked role code #1"
   mff2b1na = "get upset/unranked relationship code #1"
   mff2b2n = "get upset with/unranked role code #2"
   mff2b2na = "get upset/unranked relationship code #2"
   mff2b3n = "get upset with/unranked role code #3"
   mff2b3na = "get upset/unranked relationship code #3"
   mff2b4n = "get upset with/unranked role code #4"
   mff2b4na = "get upset/unranked relationship code #4"
   mff2b5n = "get upset with/unranked role code #5"
   mff2b5na = "get upset/unranked relationship code #5"
   mff2b6n = "get upset with/unranked role code #6"
   mff2b6na = "get upset/unranked relationship code #6"
   mff2b1b = "get upset with/order within role #1"
   mff2b2b = "get upset with/order within role #2"
   mff2b3b = "get upset with/order within role #3"
   mff2b4b = "get upset with/order within role #4"
   mff2b5b = "get upset with/order within role #5"
   mff2b6b = "get upset with/order within role #6"
   mff2b7b = "get upset with/order within role #7"
   mff2b8b = "get upset with/order within role #8"
   mff2b9b = "get upset with/order within role #9"
   mff2b10b = "get upset with/order within role #10"
   mff2b11b = "get upset with/order within role #11"
   mff2b12b = "get upset with/order within role #12"
   mff2a12d = "get upset/anyone not ranked by child"
   mff2b1nb = "get upset with/unrank order w/in role #1"
   mff2b2nb = "get upset with/unrank order w/in role #2"
   mff2b3nb = "get upset with/unrank order w/in role #3"
   mff2b4nb = "get upset with/unrank order w/in role #4"
   mff2b5nb = "get upset with/unrank order w/in role #5"
   mff2b6nb = "get upset with/unrank order w/in role #6"
   mff2c1 = "get upset with/rating for person #1"
   mff2c2 = "get upset with/rating for person #2"
   mff2c3 = "get upset with/rating for person #3"
   mff2c4 = "get upset with/rating for person #4"
   mff2c5 = "get upset with/rating for person #5"
   mff2c6 = "get upset with/rating for person #6"
   mff2c7 = "get upset with/rating for person #7"
   mff2c8 = "get upset with/rating for person #8"
   mff2c9 = "get upset with/rating for person #9"
   mff2c10 = "get upset with/rating for person #10"
   mff2c11 = "get upset with/rating for person #11"
   mff2c12 = "get upset with/rating for person #12"
   mff3b1 = "makes you happy/role code #1"
   mff3b1a = "makes you happy/relationship code #1"
   mff3b2 = "makes you happy/role code #2"
   mff3b2a = "makes you happy/relationship code #2"
   mff3b3 = "makes you happy/role code #3"
   mff3b3a = "makes you happy/relationship code #3"
   mff3b4 = "makes you happy/role code #4"
   mff3b4a = "makes you happy/relationship code #4"
   mff3b5 = "makes you happy/role code #5"
   mff3b5a = "makes you happy/relationship code #5"
   mff3b6 = "makes you happy/role code #6"
   mff3b6a = "makes you happy/relationship code #6"
   mff3b7 = "makes you happy/role code #7"
   mff3b7a = "makes you happy/relationship code #7"
   mff3b8 = "makes you happy/role code #8"
   mff3b8a = "makes you happy/relationship code #8"
   mff3b9 = "makes you happy/role code #9"
   mff3b9a = "makes you happy/relationship code #9"
   mff3b10 = "makes you happy/role code #10"
   mff3b10a = "makes you happy/relationship code #10"
   mff3b11 = "makes you happy/role code #11"
   mff3b11a = "makes you happy/relationship code #11"
   mff3b12 = "makes you happy/role code #12"
   mff3b12a = "makes you happy/relationship code #12"
   mff3b1n = "makes you happy/unranked role code #1"
   mff3b1na = "make you happy/unrank relationshp code#1"
   mff3b2n = "makes you happy/unranked role code #2"
   mff3b2na = "make you happy/unrank relationshp code#2"
   mff3b3n = "makes you happy/unranked role code #3"
   mff3b3na = "make you happy/unrank relationshp code#3"
   mff3b4n = "makes you happy/unranked role code #4"
   mff3b4na = "make you happy/unrank relationshp code#4"
   mff3b5n = "makes you happy/unranked role code #5"
   mff3b5na = "make you happy/unrank relationshp code#5"
   mff3b6n = "makes you happy/unranked role code #6"
   mff3b6na = "make you happy/unrank relationshp code#6"
   mff3b1b = "makes you happy/order within role #1"
   mff3b2b = "makes you happy/order within role #2"
   mff3b3b = "makes you happy/order within role #3"
   mff3b4b = "makes you happy/order within role #4"
   mff3b5b = "makes you happy/order within role #5"
   mff3b6b = "makes you happy/order within role #6"
   mff3b7b = "makes you happy/order within role #7"
   mff3b8b = "makes you happy/order within role #8"
   mff3b9b = "makes you happy/order within role #9"
   mff3b10b = "makes you happy/order within role #10"
   mff3b11b = "makes you happy/order within role #11"
   mff3b12b = "makes you happy/order within role #12"
   mff3a12d = "makes you happy/anyone not ranked"
   mff3b1nb = "make you happy/unrank order w/in role #1"
   mff3b2nb = "make you happy/unrank order w/in role #2"
   mff3b3nb = "make you happy/unrank order w/in role #3"
   mff3b4nb = "make you happy/unrank order w/in role #4"
   mff3b5nb = "make you happy/unrank order w/in role #5"
   mff3b6nb = "make you happy/unrank order w/in role #6"
   mff3c1 = "makes you happy/rating for person #1"
   mff3c2 = "makes you happy/rating for person #2"
   mff3c3 = "makes you happy/rating for person #3"
   mff3c4 = "makes you happy/rating for person #4"
   mff3c5 = "makes you happy/rating for person #5"
   mff3c6 = "makes you happy/rating for person #6"
   mff3c7 = "makes you happy/rating for person #7"
   mff3c8 = "makes you happy/rating for person #8"
   mff3c9 = "makes you happy/rating for person #9"
   mff3c10 = "makes you happy/rating for person #10"
   mff3c11 = "makes you happy/rating for person #11"
   mff3c12 = "makes you happy/rating for person #12"
   mff4b1 = "feel bad about/role code #1"
   mff4b1a = "feel bad about/relationship code #1"
   mff4b2 = "feel bad about/role code #2"
   mff4b2a = "feel bad about/relationship code #2"
   mff4b3 = "feel bad about/role code #3"
   mff4b3a = "feel bad about/relationship code #3"
   mff4b4 = "feel bad about/role code #4"
   mff4b4a = "feel bad about/relationship code #4"
   mff4b5 = "feel bad about/role code #5"
   mff4b5a = "feel bad about/relationship code #5"
   mff4b6 = "feel bad about/role code #6"
   mff4b6a = "feel bad about/relationship code #6"
   mff4b7 = "feel bad about/role code #7"
   mff4b7a = "feel bad about/relationship code #7"
   mff4b8 = "feel bad about/role code #8"
   mff4b8a = "feel bad about/relationship code #8"
   mff4b9 = "feel bad about/role code #9"
   mff4b9a = "feel bad about/relationship code #9"
   mff4b10 = "feel bad about/role code #10"
   mff4b10a = "feel bad about/relationship code #10"
   mff4b11 = "feel bad about/role code #11"
   mff4b11a = "feel bad about/relationship code #11"
   mff4b12 = "feel bad about/role code #12"
   mff4b12a = "feel bad about/relationship code #12"
   mff4b1n = "feel bad about/unranked role code #1"
   mff4b1na = "feel bad about/unrank relationshp code#1"
   mff4b2n = "feel bad about/unranked role code #2"
   mff4b2na = "feel bad about/unrank relationshp code#2"
   mff4b3n = "feel bad about/unranked role code #3"
   mff4b3na = "feel bad about/unrank relationshp code#3"
   mff4b4n = "feel bad about/unranked role code #4"
   mff4b4na = "feel bad about/unrank relationshp code#4"
   mff4b5n = "feel bad about/unranked role code #5"
   mff4b5na = "feel bad about/unrank relationshp code#5"
   mff4b6n = "feel bad about/unranked role code #6"
   mff4b6na = "feel bad about/unrank relationshp code#6"
   mff4b1b = "feel bad about/order within role #1"
   mff4b2b = "feel bad about/order within role #2"
   mff4b3b = "feel bad about/order within role #3"
   mff4b4b = "feel bad about/order within role #4"
   mff4b5b = "feel bad about/order within role #5"
   mff4b6b = "feel bad about/order within role #6"
   mff4b7b = "feel bad about/order within role #7"
   mff4b8b = "feel bad about/order within role #8"
   mff4b9b = "feel bad about/order within role #9"
   mff4b10b = "feel bad about/order within role #10"
   mff4b11b = "feel bad about/order within role #11"
   mff4b12b = "feel bad about/order within role #12"
   mff4a12d = "feel bad about/anyone unranked by child"
   mff4b1nb = "feel bad about/unrank order w/in role #1"
   mff4b2nb = "feel bad about/unrank order w/in role #2"
   mff4b3nb = "feel bad about/unrank order w/in role #3"
   mff4b4nb = "feel bad about/unrank order w/in role #4"
   mff4b5nb = "feel bad about/unrank order w/in role #5"
   mff4b6nb = "feel bad about/unrank order w/in role #6"
   mff4c1 = "feel bad about/rating for person #1"
   mff4c2 = "feel bad about/rating for person #2"
   mff4c3 = "feel bad about/rating for person #3"
   mff4c4 = "feel bad about/rating for person #4"
   mff4c5 = "feel bad about/rating for person #5"
   mff4c6 = "feel bad about/rating for person #6"
   mff4c7 = "feel bad about/rating for person #7"
   mff4c8 = "feel bad about/rating for person #8"
   mff4c9 = "feel bad about/rating for person #9"
   mff4c10 = "feel bad about/rating for person #10"
   mff4c11 = "feel bad about/rating for person #11"
   mff4c12 = "feel bad about/rating for person #12"
   mff5b1 = "knows you best/role code #1"
   mff5b1a = "knows you best/relationship code #1"
   mff5b2 = "knows you best/role code #2"
   mff5b2a = "knows you best/relationship code #2"
   mff5b3 = "knows you best/role code #3"
   mff5b3a = "knows you best/relationship code #3"
   mff5b4 = "knows you best/role code #4"
   mff5b4a = "knows you best/relationship code #4"
   mff5b5 = "knows you best/role code #5"
   mff5b5a = "knows you best/relationship code #5"
   mff5b6 = "knows you best/role code #6"
   mff5b6a = "knows you best/relationship code #6"
   mff5b7 = "knows you best/role code #7"
   mff5b7a = "knows you best/relationship code #7"
   mff5b8 = "knows you best/role code #8"
   mff5b8a = "knows you best/relationship code #8"
   mff5b9 = "knows you best/role code #9"
   mff5b9a = "knows you best/relationship code #9"
   mff5b10 = "knows you best/role code #10"
   mff5b10a = "knows you best/relationship code #10"
   mff5b11 = "knows you best/role code #11"
   mff5b11a = "knows you best/relationship code #11"
   mff5b12 = "knows you best/role code #12"
   mff5b12a = "knows you best/relationship code #12"
   mff5b1n = "knows you best/unranked role code #1"
   mff5b1na = "know you best/unrank relationshp code #1"
   mff5b2n = "knows you best/unranked role code #2"
   mff5b2na = "know you best/unrank relationshp code #2"
   mff5b3n = "knows you best/unranked role code #3"
   mff5b3na = "know you best/unrank relationshp code #3"
   mff5b4n = "knows you best/unranked role code #4"
   mff5b4na = "know you best/unrank relationshp code #4"
   mff5b5n = "knows you best/unranked role code #5"
   mff5b5na = "know you best/unrank relationshp code #5"
   mff5b6n = "knows you best/unranked role code #6"
   mff5b6na = "know you best/unrank relationshp code #6"
   mff5b1b = "knows you best/order within role #1"
   mff5b2b = "knows you best/order within role #2"
   mff5b3b = "knows you best/order within role #3"
   mff5b4b = "knows you best/order within role #4"
   mff5b5b = "knows you best/order within role #5"
   mff5b6b = "knows you best/order within role #6"
   mff5b7b = "knows you best/order within role #7"
   mff5b8b = "knows you best/order within role #8"
   mff5b9b = "knows you best/order within role #9"
   mff5b10b = "knows you best/order within role #10"
   mff5b11b = "knows you best/order within role #11"
   mff5b12b = "knows you best/order within role #12"
   mff5a12d = "knows you best/anyone unranked by child"
   mff5b1nb = "knows you best/unrank order w/in role #1"
   mff5b2nb = "knows you best/unrank order w/in role #2"
   mff5b3nb = "knows you best/unrank order w/in role #3"
   mff5b4nb = "knows you best/unrank order w/in role #4"
   mff5b5nb = "knows you best/unrank order w/in role #5"
   mff5b6nb = "knows you best/unrank order w/in role #6"
   mff5c1 = "knows you best/rating for person #1"
   mff5c2 = "knows you best/rating for person #2"
   mff5c3 = "knows you best/rating for person #3"
   mff5c4 = "knows you best/rating for person #4"
   mff5c5 = "knows you best/rating for person #5"
   mff5c6 = "knows you best/rating for person #6"
   mff5c7 = "knows you best/rating for person #7"
   mff5c8 = "knows you best/rating for person #8"
   mff5c9 = "knows you best/rating for person #9"
   mff5c10 = "knows you best/rating for person #10"
   mff5c11 = "knows you best/rating for person #11"
   mff5c12 = "knows you best/rating for person #12"
   mff6b1 = "make you feel good/role code #1"
   mff6b1a = "make you feel good/relationship code #1"
   mff6b2 = "make you feel good/role code #2"
   mff6b2a = "make you feel good/relationship code #2"
   mff6b3 = "make you feel good/role code #3"
   mff6b3a = "make you feel good/relationship code #3"
   mff6b4 = "make you feel good/role code #4"
   mff6b4a = "make you feel good/relationship code #4"
   mff6b5 = "make you feel good/role code #5"
   mff6b5a = "make you feel good/relationship code #5"
   mff6b6 = "make you feel good/role code #6"
   mff6b6a = "make you feel good/relationship code #6"
   mff6b7 = "make you feel good/role code #7"
   mff6b7a = "make you feel good/relationship code #7"
   mff6b8 = "make you feel good/role code #8"
   mff6b8a = "make you feel good/relationship code #8"
   mff6b9 = "make you feel good/role code #9"
   mff6b9a = "make you feel good/relationship code #9"
   mff6b10 = "make you feel good/role code #10"
   mff6b10a = "make you feel good/relationship code #10"
   mff6b11 = "make you feel good/role code #11"
   mff6b11a = "make you feel good/relationship code #11"
   mff6b12 = "make you feel good/role code #12"
   mff6b12a = "make you feel good/relationship code #12"
   mff6b1n = "make you feel good/unrank role code #1"
   mff6b1na = "makes feel good/unrank relatnshp code#1"
   mff6b2n = "make you feel good/unrank role code #2"
   mff6b2na = "makes feel good/unrank relatnshp code#2"
   mff6b3n = "make you feel good/unrank role code #3"
   mff6b3na = "makes feel good/unrank relatnshp code#3"
   mff6b4n = "make you feel good/unrank role code #4"
   mff6b4na = "makes feel good/unrank relatnshp code#4"
   mff6b5n = "make you feel good/unrank role code #5"
   mff6b5na = "makes feel good/unrank relatnshp code#5"
   mff6b6n = "make you feel good/unrank role code #6"
   mff6b6na = "makes feel good/unrank relatnshp code#6"
   mff7 = "interviewer initials"
   mff6b1b = "make you feel good/order within role #1"
   mff6b2b = "make you feel good/order within role #2"
   mff6b3b = "make you feel good/order within role #3"
   mff6b4b = "make you feel good/order within role #4"
   mff6b5b = "make you feel good/order within role #5"
   mff6b6b = "make you feel good/order within role #6"
   mff6b7b = "make you feel good/order within role #7"
   mff6b8b = "make you feel good/order within role #8"
   mff6b9b = "make you feel good/order within role #9"
   mff6b10b = "make you feel good/order within role #10"
   mff6b11b = "make you feel good/order within role #11"
   mff6b12b = "make you feel good/order within role #12"
   mff6a12d = "make you feel good/anyone unranked"
   mff6b1nb = "makes feel good/unrank order w/in role 1"
   mff6b2nb = "makes feel good/unrank order w/in role 2"
   mff6b3nb = "makes feel good/unrank order w/in role 3"
   mff6b4nb = "makes feel good/unrank order w/in role 4"
   mff6b5nb = "makes feel good/unrank order w/in role 5"
   mff6b6nb = "makes feel good/unrank order w/in role 6"
   mff6c1 = "makes you feel good/rating for person #1"
   mff6c2 = "makes you feel good/rating for person #2"
   mff6c3 = "makes you feel good/rating for person #3"
   mff6c4 = "makes you feel good/rating for person #4"
   mff6c5 = "makes you feel good/rating for person #5"
   mff6c6 = "makes you feel good/rating for person #6"
   mff6c7 = "makes you feel good/rating for person #7"
   mff6c8 = "makes you feel good/rating for person #8"
   mff6c9 = "makes you feel good/rating for person #9"
   mff6c10 = "make you feel good/rating for person #10"
   mff6c11 = "make you feel good/rating for person #11"
   mff6c12 = "make you feel good/rating for person #12"
   mff8 = "date of interview"
   mff1aa = "talk about feelings: stem administered?"
   mff6aa = "make you feel good: stem administered?"
   mffemot1 = "summary score: talk about feeling"
   mffconfl = "summary score: get upset or angry with"
   mffemot2 = "summary score: something good"
   mffemot3 = "summary score: something you felt bad"
   mffemot4 = "summary score: understands or knows"
   mffemot5 = "summary score: make you feel good"
   n_emot1 = "# ranked: talk about feeling"
   n_confl = "# ranked: get upset or angry with"
   n_emot2 = "# ranked: something good"
   n_emot3 = "# ranked: something you felt bad"
   n_emot4 = "# ranked: understands or knows"
   n_emot5 = "# ranked: make you feel good"
   mffme1 = "mother: talk about feeling"
   mffme2 = "mother: something good"
   mffme3 = "mother: something you felt bad"
   mffme4 = "mother: understands or knows"
   mffme5 = "mother: make you feel good"
   mffmc = "mother: get upset or angry with"
   mfffe1 = "father: talk about feeling"
   mfffe2 = "father: something good"
   mfffe3 = "father: something you felt bad"
   mfffe4 = "father: understands or knows"
   mfffe5 = "father: make you feel good"
   mfffc = "father: get upset or angry with"
   mffgme1 = "grandmother: talk about feeling"
   mffgme2 = "grandmother: something good"
   mffgme3 = "grandmother: something you felt bad"
   mffgme4 = "grandmother: understands or knows"
   mffgme5 = "grandmother: make you feel good"
   mffgmc = "grandmother: get upset or angry with"
   mffgfe1 = "grandfather: talk about feeling"
   mffgfe2 = "grandfather: something good"
   mffgfe3 = "grandfather: something you felt bad"
   mffgfe4 = "grandfather: understands or knows"
   mffgfe5 = "grandfather: make you feel good"
   mffgfc = "grandfather: get upset or angry with"
   mffbe1 = "brother: talk about feeling"
   mffbe2 = "brother: something good"
   mffbe3 = "brother: something you felt bad"
   mffbe4 = "brother: understands or knows"
   mffbe5 = "brother: make you feel good"
   mffbc = "brother: get upset or angry with"
   mffse1 = "sister: talk about feeling"
   mffse2 = "sister: something good"
   mffse3 = "sister: something you felt bad"
   mffse4 = "sister: understands or knows"
   mffse5 = "sister: make you feel good"
   mffsc = "sister: get upset or angry with"
   mffore1 = "relative: talk about feeling"
   mffore2 = "relative: something good"
   mffore3 = "relative: something you felt bad"
   mffore4 = "relative: understands or knows"
   mffore5 = "relative: make you feel good"
   mfforc = "relative: get upset or angry with"
   mffoae1 = "other adult: talk about feeling"
   mffoae2 = "other adult: something good"
   mffoae3 = "other adult: something you felt bad"
   mffoae4 = "other adult: understands or knows"
   mffoae5 = "other adult: make you feel good"
   mffoac = "other adult: get upset or angry with"
   mffoce1 = "other child: talk about feeling"
   mffoce2 = "other child: something good"
   mffoce3 = "other child: something you felt bad"
   mffoce4 = "other child: understands or knows"
   mffoce5 = "other child: make you feel good"
   mffocc = "other child: get upset or angry with"
   mffte1 = "teacher: talk about feeling"
   mffte2 = "teacher: something good"
   mffte3 = "teacher: something you felt bad"
   mffte4 = "teacher: understands or knows"
   mffte5 = "teacher: make you feel good"
   mfftc = "teacher: get upset or angry with"
   mffmemt = "mother: total emotional support"
   mfffemt = "father: total emotional support"
   mffgmemt = "grandmother: total emotional support"
   mffgfemt = "grandfather: total emotional support"
   mffbemt = "brother: total emotional support"
   mffsemt = "sister: total emotional support"
   mfforemt = "other relative: total emotional support"
   mffoaemt = "other adults: total emotional support"
   mffocemt = "other child: total emotional support"
   mfftemt = "teachers: total emotional support"
   rca7b2 = "describe why ffa not valid: line #1"
   rca7b1 = "ffa valid?" ;

FORMAT
   mff8 DATE9.            ;
                     

LENGTH
   visit 3                  mff1b1b 3                mff1b2b 3             
   mff1b3b 3                mff1b4b 3                mff1b5b 3             
   mff1b6b 3                mff1b7b 3                mff1b8b 3             
   mff1b9b 3                mff1b10b 3               mff1b11b 3            
   mff1b12b 3               mff1a12d 3               mff1b1nb 3            
   mff1b2nb 3               mff1b3nb 3               mff1b4nb 3            
   mff1b5nb 3               mff1b6nb 3               mff1c1 3              
   mff1c2 3                 mff1c3 3                 mff1c4 3              
   mff1c5 3                 mff1c6 3                 mff1c7 3              
   mff1c8 3                 mff1c9 3                 mff1c10 3             
   mff1c11 3                mff1c12 3                mff2b1b 3             
   mff2b2b 3                mff2b3b 3                mff2b4b 3             
   mff2b5b 3                mff2b6b 3                mff2b7b 3             
   mff2b8b 3                mff2b9b 3                mff2b10b 3            
   mff2b11b 3               mff2b12b 3               mff2a12d 3            
   mff2b1nb 3               mff2b2nb 3               mff2b3nb 3            
   mff2b4nb 3               mff2b5nb 3               mff2b6nb 3            
   mff2c1 3                 mff2c2 3                 mff2c3 3              
   mff2c4 3                 mff2c5 3                 mff2c6 3              
   mff2c7 3                 mff2c8 3                 mff2c9 3              
   mff2c10 3                mff2c11 3                mff2c12 3             
   mff3b1b 3                mff3b2b 3                mff3b3b 3             
   mff3b4b 3                mff3b5b 3                mff3b6b 3             
   mff3b7b 3                mff3b8b 3                mff3b9b 3             
   mff3b10b 3               mff3b11b 3               mff3b12b 3            
   mff3a12d 3               mff3b1nb 3               mff3b2nb 3            
   mff3b3nb 3               mff3b4nb 3               mff3b5nb 3            
   mff3b6nb 3               mff3c1 3                 mff3c2 3              
   mff3c3 3                 mff3c4 3                 mff3c5 3              
   mff3c6 3                 mff3c7 3                 mff3c8 3              
   mff3c9 3                 mff3c10 3                mff3c11 3             
   mff3c12 3                mff4b1b 3                mff4b2b 3             
   mff4b3b 3                mff4b4b 3                mff4b5b 3             
   mff4b6b 3                mff4b7b 3                mff4b8b 3             
   mff4b9b 3                mff4b10b 3               mff4b11b 3            
   mff4b12b 3               mff4a12d 3               mff4b1nb 3            
   mff4b2nb 3               mff4b3nb 3               mff4b4nb 3            
   mff4b5nb 3               mff4b6nb 3               mff4c1 3              
   mff4c2 3                 mff4c3 3                 mff4c4 3              
   mff4c5 3                 mff4c6 3                 mff4c7 3              
   mff4c8 3                 mff4c9 3                 mff4c10 3             
   mff4c11 3                mff4c12 3                mff5b1b 3             
   mff5b2b 3                mff5b3b 3                mff5b4b 3             
   mff5b5b 3                mff5b6b 3                mff5b7b 3             
   mff5b8b 3                mff5b9b 3                mff5b10b 3            
   mff5b11b 3               mff5b12b 3               mff5a12d 3            
   mff5b1nb 3               mff5b2nb 3               mff5b3nb 3            
   mff5b4nb 3               mff5b5nb 3               mff5b6nb 3            
   mff5c1 3                 mff5c2 3                 mff5c3 3              
   mff5c4 3                 mff5c5 3                 mff5c6 3              
   mff5c7 3                 mff5c8 3                 mff5c9 3              
   mff5c10 3                mff5c11 3                mff5c12 3             
   mff6b1b 3                mff6b2b 3                mff6b3b 3             
   mff6b4b 3                mff6b5b 3                mff6b6b 3             
   mff6b7b 3                mff6b8b 3                mff6b9b 3             
   mff6b10b 3               mff6b11b 3               mff6b12b 3            
   mff6a12d 3               mff6b1nb 3               mff6b2nb 3            
   mff6b3nb 3               mff6b4nb 3               mff6b5nb 3            
   mff6b6nb 3               mff6c1 3                 mff6c2 3              
   mff6c3 3                 mff6c4 3                 mff6c5 3              
   mff6c6 3                 mff6c7 3                 mff6c8 3              
   mff6c9 3                 mff6c10 3                mff6c11 3             
   mff6c12 3                n_emot1 3                n_confl 3             
   n_emot2 3                n_emot3 3                n_emot4 3             
   n_emot5 3                mffme1 3                 mffme2 3              
   mffme3 3                 mffme4 3                 mffme5 3              
   mffmc 3                  mfffe1 3                 mfffe2 3              
   mfffe3 3                 mfffe4 3                 mfffe5 3              
   mfffc 3                  mffgme1 3                mffgme2 3             
   mffgme3 3                mffgme4 3                mffgme5 3             
   mffgmc 3                 mffgfe1 3                mffgfe2 3             
   mffgfe3 3                mffgfe4 3                mffgfe5 3             
   mffgfc 3                 mffbe1 3                 mffbe2 3              
   mffbe3 3                 mffbe4 3                 mffbe5 3              
   mffbc 3                  mffse1 3                 mffse2 3              
   mffse3 3                 mffse4 3                 mffse5 3              
   mffsc 3                  mffore1 3                mffore2 3             
   mffore3 3                mffore4 3                mffore5 3             
   mfforc 3                 mffoae1 3                mffoae2 3             
   mffoae3 3                mffoae4 3                mffoae5 3             
   mffoac 3                 mffoce1 3                mffoce2 3             
   mffoce3 3                mffoce4 3                mffoce5 3             
   mffocc 3                 mffte1 3                 mffte2 3              
   mffte3 3                 mffte4 3                 mffte5 3              
   mfftc 3                  rca7b1 3 ;

        

RUN ;
