/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\nea0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = nea0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=33;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   nea1  11                 nea2  12                 nea3  13              
   nea4  14                 nea5  15                 nea6  16              
   nea7  17                 nea8  18                 nea9  19              
   nea10 $ 20-22            nea11 DATE11.          ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   nea1 = "people in neighborhood help each other"
   nea2 = "most people in neighborhood use welfare"
   nea3 = "lot of drug abuse in neighborhood"
   nea4 = "adults watch out for ea/other^s children"
   nea5 = "i am proud to live in this neighborhood"
   nea6 = "it is dangerous in neighborhood"
   nea7 = "there are people in neighbrhd i can rely"
   nea8 = "buildings and yards are run down"
   nea9 = "some people may be bad influence on kids"
   nea10 = "interviewer initials"
   nea11 = "date of interview" ;

FORMAT
   nea11 DATE9. ;
      

LENGTH
   visit 3                  nea1 3                   nea2 3                
   nea3 3                   nea4 3                   nea5 3                
   nea6 3                   nea7 3                   nea8 3                
   nea9 3 ;

          

RUN ;
