/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\nrfa0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = nrfa0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=147;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   nrfa1a  11-12            nrfa1b  13-14            nrfa2  15             
   nrfa2a $ 16-44           nrfa3  45                nrfa4a $ 46           
   nrfa4a1 $ 47-74          nrfa4b $ 75              nrfa5  76             
   nrfa5a $ 77-106          nrfa6  107               nrfa7  108            
   nrfa8  109               nrfa9  110               nrfa10  111           
   nrfa11  112              nrfa12  113              nrfa13  114           
   nrfa14  115              nrfa15  116              nrfa16  117           
   nrfa17  118              nrfa18  119              nrfa19  120           
   nrfa20  121              nrfa21  122              nrfa22  123           
   nrfa23  124              nrfa24  125              nrfa25  126           
   nrfa26  127              nrfa27  128              nrfa28  129           
   nrfa29  130              nrfa30  131              nrfa31  132           
   nrfa32  133              nrfa33 $ 134-136         nrfa34 DATE11.        
 ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   nrfa1a = "years lived in neighborhood"
   nrfa1b = "months lived in neighborhood"
   nrfa2 = "description of neighborhood"
   nrfa2a = "other description of neighborhood"
   nrfa3 = "proximity of nearest neighbor"
   nrfa4a = "description of residence"
   nrfa4a1 = "other description of residence"
   nrfa4b = "type of housing--public, section 8, etc."
   nrfa5 = "own-rent-share residence"
   nrfa5a = "other living arrangement in residence"
   nrfa6 = "comf. borrowing money-food from neighbor"
   nrfa7 = "neighbors can ask me to lend money-food"
   nrfa8 = "ability to get help from neighbor"
   nrfa9 = "neighbors can get help from me"
   nrfa10 = "adult who can stay if child is sick"
   nrfa11 = "greet neighbors"
   nrfa12 = "neighbors watch each others' children"
   nrfa13 = "neighbors who are parents to talk to"
   nrfa14 = "child plays w othr children in neighbor."
   nrfa15 = "people trust each other in neighborhood"
   nrfa16 = "sense of belonging in neighborhood"
   nrfa17 = "care about neighbors' opinions"
   nrfa18 = "neighborhood is good place to live"
   nrfa19 = "would move from nghbrhd if possible"
   nrfa20 = "good place for chldrn to play in neighb."
   nrfa21 = "neighborhood good place to raise family"
   nrfa22 = "safe for children to play outside"
   nrfa23 = "don't want chldrn play with some"
   nrfa24 = "drug abuse-dealing in neighborhood"
   nrfa25 = "safe to walk alone during day"
   nrfa26 = "people get along well with police"
   nrfa27 = "homes-businesses broken into"
   nrfa28 = "vandalism in neighborhood"
   nrfa29 = "people=victims of bodily crime in neigh."
   nrfa30 = "keep to myself in neighborhood"
   nrfa31 = "what liked least about neighborhood"
   nrfa32 = "what liked most about neighborhood"
   nrfa33 = "interviewer initials"
   nrfa34 = "date of interview" ;

FORMAT
   nrfa34 DATE9. ;
     

LENGTH
   visit 3                  nrfa1a 3                 nrfa1b 3              
   nrfa2 3                  nrfa3 3                  nrfa5 3               
   nrfa6 3                  nrfa7 3                  nrfa8 3               
   nrfa9 3                  nrfa10 3                 nrfa11 3              
   nrfa12 3                 nrfa13 3                 nrfa14 3              
   nrfa15 3                 nrfa16 3                 nrfa17 3              
   nrfa18 3                 nrfa19 3                 nrfa20 3              
   nrfa21 3                 nrfa22 3                 nrfa23 3              
   nrfa24 3                 nrfa25 3                 nrfa26 3              
   nrfa27 3                 nrfa28 3                 nrfa29 3              
   nrfa30 3                 nrfa31 3                 nrfa32 3 ;

        

RUN ;
