/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\nrib1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = nrib1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=94;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   NRIB3  12                NRIB10A  13              NRIB10B  14           
   NRIB10C  15              NRIB10D  16              NRIB10E  17           
   NRIB10F  18              NRIB11A  19              NRIB11B  20           
   NRIB11C  21              NRIB11D  22              NRIB11E  23           
   NRIB11F  24              NRIB12A  25              NRIB12B  26           
   NRIB12C  27              NRIB12D  28              NRIB12E  29           
   NRIB12F  30              NRIB13A  31              NRIB13B  32           
   NRIB13C  33              NRIB13D  34              NRIB13E  35           
   NRIB13F  36              NRIB14A  37              NRIB14B  38           
   NRIB14C  39              NRIB14D  40              NRIB14E  41           
   NRIB14F  42              NRIB15A  43              NRIB15B  44           
   NRIB15C  45              NRIB15D  46              NRIB15E  47           
   NRIB15F  48              NRIB1A  49               NRIB1B  50            
   NRIB1C  51               NRIB2A  52               NRIB2B  53            
   NRIB2C  54               NRIB3A  55               NRIB3B  56            
   NRIB3C  57               NRIB3D  58               NRIB4A  59            
   NRIB4B  60               NRIB4C  61               NRIB4D  62            
   NRIB4E  63               NRIB4F  64               NRIB5A  65            
   NRIB5B  66               NRIB5C  67               NRIB5D  68            
   NRIB5E  69               NRIB5F  70               NRIB6A  71            
   NRIB6B  72               NRIB6C  73               NRIB6D  74            
   NRIB6E  75               NRIB6F  76               NRIB7A  77            
   NRIB7B  78               NRIB7C  79               NRIB7D  80            
   NRIB7E  81               NRIB7F  82               NRIB8A  83            
   NRIB8B  84               NRIB8C  85               NRIB8D  86            
   NRIB8E  87               NRIB8F  88               NRIB9A  89            
   NRIB9B  90               NRIB9C  91               NRIB9D  92            
   NRIB9E  93               NRIB9F  94             ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   NRIB3 = "Do you have boy/girl friend"
   NRIB10A = "G: how much share secrets/female friend"
   NRIB10B = "B: how much share secrets/male friend"
   NRIB10C = "G: how much share secrets/male friend"
   NRIB10D = "B: how much share secrets/female friend"
   NRIB10E = "How much share secrets/your boyfriend"
   NRIB10F = "How much share secrets/your girlfriend"
   NRIB11A = "G: how happy with female friend"
   NRIB11B = "B: how happy with male friend"
   NRIB11C = "G: how happy with male friend"
   NRIB11D = "B: how happy with female friend"
   NRIB11E = "How happy are you with your boyfriend"
   NRIB11F = "How happy are you with your girlfriend"
   NRIB12A = "G: how often go places wth female friend"
   NRIB12B = "B: how often go places with male friend"
   NRIB12C = "G: how often go places with male friend"
   NRIB12D = "B: how often go places wth female friend"
   NRIB12E = "How often go places/your boyfriend"
   NRIB12F = "How often go places/your girlfriend"
   NRIB13A = "G: how much argue with female friend"
   NRIB13B = "B: how much argue with male friend"
   NRIB13C = "G: how much argue with male friend"
   NRIB13D = "B: how much argue with female friend"
   NRIB13E = "How much argue with your boyfriend"
   NRIB13F = "How much argue with your girlfriend"
   NRIB14A = "G: how good relationship/female friend"
   NRIB14B = "B: how good relationship/male friend"
   NRIB14C = "G: how good relationship/ male friend"
   NRIB14D = "B: how good relationship/female friend"
   NRIB14E = "How good relationship/your boyfriend"
   NRIB14F = "How good relationship/your girlfriend"
   NRIB15A = "G: how much talk things/female friend"
   NRIB15B = "B: how much talk things/male friend"
   NRIB15C = "G: how much talk things/male friend"
   NRIB15D = "B: how much talk things/female friend"
   NRIB15E = "How much talk about things/boyfriend"
   NRIB15F = "How much talk things/girlfriend"
   NRIB1A = "Best friend/how old"
   NRIB1B = "Best friend/how long"
   NRIB1C = "Best friend/go to same school/work"
   NRIB2A = "Best friend/how old"
   NRIB2B = "Best friend/how long"
   NRIB2C = "Best friend/go to same school/work"
   NRIB3A = "Is this person boy or girl"
   NRIB3B = "How old is this person"
   NRIB3C = "Best friend/how long"
   NRIB3D = "Best friend/go to same school/work"
   NRIB4A = "G:time spend with female friend"
   NRIB4B = "B:time spend with male friend"
   NRIB4C = "G: time spend with male friend"
   NRIB4D = "Time spend with female friend"
   NRIB4E = "Time spend with boyfriend"
   NRIB4F = "Time spend with girlfriend"
   NRIB5A = "G: how upset/mad with female friend"
   NRIB5B = "B: how upset/mad with male friend"
   NRIB5C = "G: how upset with male friend/not br"
   NRIB5D = "B: how upset with female friend/not sr"
   NRIB5E = "How upset/mad with your boyfriend"
   NRIB5F = "How upset/mad with your girlfriend"
   NRIB6A = "G: how satisfied with female friend"
   NRIB6B = "B: how satisfied with male friend"
   NRIB6C = "G: how satisfied with male friend"
   NRIB6D = "B: how satisfied with female friend"
   NRIB6E = "How satisfied with your boyfriend"
   NRIB6F = "How satisfied with your girlfriend"
   NRIB7A = "G: How much do you tell female friend"
   NRIB7B = "B: How much do you tell male friend"
   NRIB7C = "G: How much do you tell male friend"
   NRIB7D = "B: How much do you tell female friend"
   NRIB7E = "How much do you tell your boyfriend"
   NRIB7F = "How much do you tell your girlfriend"
   NRIB8A = "G: how much play around female friend"
   NRIB8B = "B: how much play around male friend"
   NRIB8C = "G: how much play around male friend"
   NRIB8D = "B: how much play around female friend"
   NRIB8E = "How much play around wth your boyfriend"
   NRIB8F = "How much play around wth your girlfriend"
   NRIB9A = "G: how much disagree with female friend"
   NRIB9B = "B: how much disagree with male friend"
   NRIB9C = "G: how much disagree with male friend"
   NRIB9D = "B: how much disagree with female friend"
   NRIB9E = "How much disagree with your boyfriend"
   NRIB9F = "How much disagree with your girlfriend" ;

LENGTH
   VISIT 3                  NRIB3 3                  NRIB10A 3             
   NRIB10B 3                NRIB10C 3                NRIB10D 3             
   NRIB10E 3                NRIB10F 3                NRIB11A 3             
   NRIB11B 3                NRIB11C 3                NRIB11D 3             
   NRIB11E 3                NRIB11F 3                NRIB12A 3             
   NRIB12B 3                NRIB12C 3                NRIB12D 3             
   NRIB12E 3                NRIB12F 3                NRIB13A 3             
   NRIB13B 3                NRIB13C 3                NRIB13D 3             
   NRIB13E 3                NRIB13F 3                NRIB14A 3             
   NRIB14B 3                NRIB14C 3                NRIB14D 3             
   NRIB14E 3                NRIB14F 3                NRIB15A 3             
   NRIB15B 3                NRIB15C 3                NRIB15D 3             
   NRIB15E 3                NRIB15F 3                NRIB1A 3              
   NRIB1B 3                 NRIB1C 3                 NRIB2A 3              
   NRIB2B 3                 NRIB2C 3                 NRIB3A 3              
   NRIB3B 3                 NRIB3C 3                 NRIB3D 3              
   NRIB4A 3                 NRIB4B 3                 NRIB4C 3              
   NRIB4D 3                 NRIB4E 3                 NRIB4F 3              
   NRIB5A 3                 NRIB5B 3                 NRIB5C 3              
   NRIB5D 3                 NRIB5E 3                 NRIB5F 3              
   NRIB6A 3                 NRIB6B 3                 NRIB6C 3              
   NRIB6D 3                 NRIB6E 3                 NRIB6F 3              
   NRIB7A 3                 NRIB7B 3                 NRIB7C 3              
   NRIB7D 3                 NRIB7E 3                 NRIB7F 3              
   NRIB8A 3                 NRIB8B 3                 NRIB8C 3              
   NRIB8D 3                 NRIB8E 3                 NRIB8F 3              
   NRIB9A 3                 NRIB9B 3                 NRIB9C 3              
   NRIB9D 3                 NRIB9E 3                 NRIB9F 3 ;

        

RUN ;
