/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ocdb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ocdb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=131;
INPUT
   CENTER $ 1-2             ID $ 3-9                 OCDB7G $ 10           
   OCDB12B $ 11-30          VISIT  31-32             OCDB1  33             
   OCDB2  34                OCDB3  35                OCDB4  36             
   OCDB5  37                OCDB6  38                OCDB7  39             
   OCDB8  40                OCDB9  41                OCDB10  42            
   OCDB11  43-44            OCDB12  45               OCDB13  46            
   OCDB14  47               OCDB15  48               OCDB16  49            
   OCDB17  50               OCDB18  51               OCDB19  52            
   OCDB20  53               OCDB21  54               OCDB11A  55           
   OCDB11B  56              OCDB11C  57              OCDB11D  58-59        
   OCDB11DGR  60            OCDB11E  61              OCDB11GR  62          
   OCDB12A  63              OCDB13A  64              OCDB14A  65           
   OCDB15A  66              OCDB16A  67              OCDB17A  68           
   OCDB17AYA  69            OCDB17YA  70             OCDB18A  71           
   OCDB19A  72              OCDB1A  73               OCDB1B  74            
   OCDB1C  75               OCDB1D  76               OCDB1E  77            
   OCDB1F  78               OCDB20A  79              OCDB21AGR  80         
   OCDB2A  81               OCDB2B  82               OCDB2C  83            
   OCDB2D  84               OCDB2E  85               OCDB2F  86            
   OCDB3A  87               OCDB3B  88               OCDB3C  89            
   OCDB3D  90               OCDB3E  91               OCDB3F  92            
   OCDB5A  93               OCDB5B  94               OCDB5C  95            
   OCDB5D  96               OCDB5E  97               OCDB5F  98            
   OCDB5G  99               OCDB6A  100              OCDB6B  101           
   OCDB6C  102              OCDB6D  103              OCDB6E  104           
   OCDB6F  105              OCDB6G  106              OCDB6H  107           
   OCDB6I  108              OCDB7A  109              OCDB7B  110           
   OCDB7C  111              OCDB7D  112              OCDB7E  113           
   OCDB7F  114              OCDB8A  115              OCDB8B  116           
   OCDB8C  117              OCDB8D  118              OCDB8E  119           
   OCDB8F  120              OCDB8G  121              OCDB8H  122           
   OCDBX1  123              OCDBX2  124              OCDBX3  125           
   OCDBX4  126              OCDBX5  127              OCDBX6  128           
   OCDBX7  129              OCDB21A  130-131       ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   OCDB7G = "Last 4 wks: often counted things"
   OCDB12B = "What was wrong with you"
   VISIT = "VISIT NUMBER"
   OCDB1 = "Last yr: worried things have germs"
   OCDB2 = "Last yr: thoughts about doing bad thing"
   OCDB3 = "Last yr:othr thghts/couldn't get rid of"
   OCDB4 = "Some one/power put thoughts in your head"
   OCDB5 = "Last yr: washed hands etc. daily"
   OCDB6 = "Check on things over and over again"
   OCDB7 = "Had to count/do things over and over"
   OCDB8 = "Last yr:do other thing over and over"
   OCDB9 = "Time spent worrying etc. add up to 1hr"
   OCDB10 = "Had thoughts etc. most days for 2 wks"
   OCDB11 = "Age when 1st began to have thoughts etc"
   OCDB12 = "Did worrying etc start suddenly"
   OCDB13 = "Last yr/thoughts:family/friends upset"
   OCDB14 = "Having thoughts etc. prevent famly thngs"
   OCDB15 = "Having thoughts etc. prevent other thngs"
   OCDB16 = "Worst prblms: make schl/work difficult"
   OCDB17 = "Having thoughts etc.upset teacher/boss"
   OCDB18 = "Worst prblms: make you feel upset"
   OCDB19 = "Seen someone in hospital in lat year"
   OCDB20 = "Who did you see/are seeing"
   OCDB21 = "Whole life:thghts evr worse than last yr"
   OCDB11A = "Had thoughts etc. more than 1 yr ago"
   OCDB11B = "Ever stopped having thoughts"
   OCDB11C = "Stopped having thoughts etc. for 2 mths"
   OCDB11D = "Age when thoughts etc began again"
   OCDB11DGR = "Grade when thoughts etc began again"
   OCDB11E = "Start having thoughts ets again >1yr ago"
   OCDB11GR = "Grade 1st began to have thoughts etc."
   OCDB12A = "Sick wth fever when worrying etc.started"
   OCDB13A = "Often thoughts upset family/freinds"
   OCDB14A = "Often having thghts prevent family thngs"
   OCDB15A = "Often thoughts etc. prevent other thngs"
   OCDB16A = "How bad were school/work problems"
   OCDB17A = "How often teacher/boss upset"
   OCDB17AYA = "How bad were self care problems"
   OCDB17YA = "Having thoughts etc.made self care hard"
   OCDB18A = "How bad problems make you feel"
   OCDB19A = "Have appointment due to having thoughts"
   OCDB1A = "Worried every day that things have germs"
   OCDB1B = "Worried about germs more than others"
   OCDB1C = "Have worries about germs with friends"
   OCDB1D = "Did worries about germs upset you a lot"
   OCDB1E = "Did you try to make worries go away"
   OCDB1F = "Last 4 wks-thought things were dirty"
   OCDB20A = "What person you saw say the matter was"
   OCDB21AGR = "Grade thoughts were worst"
   OCDB2A = "Did bad thoughts come over and over"
   OCDB2B = "Have thghts re: bad things every day"
   OCDB2C = "Have thghts re: bad things with friends"
   OCDB2D = "Did thoughts re: bad things bother you"
   OCDB2E = "Try to make (bad) thoughts go away"
   OCDB2F = "Last 4 wks: often had bad thoughts"
   OCDB3A = "Can you tell me what thoughts were"
   OCDB3B = "Thghst/couldn;t get rid of every day"
   OCDB3C = "Have thghts can't get rid of wth frnds"
   OCDB3D = "Have these thoughts upset you"
   OCDB3E = "Did you try to make thoughts go away"
   OCDB3F = "Last 4wks:had thgts.kept coming back"
   OCDB5A = "Washed hands etc. over and over daily"
   OCDB5B = "Having to wash hands etc. bother you"
   OCDB5C = "Hard to stop washng hands/changng cloths"
   OCDB5D = "Miss doing thngs due to washing hands"
   OCDB5E = "Somthng bad will happn if you don't wash"
   OCDB5F = "Washing hands/body make you feel better"
   OCDB5G = "Last 4wks:had to wash hands over & over"
   OCDB6A = "Did you go and check and make sure"
   OCDB6B = "Had to keep checking on things every day"
   OCDB6C = "Checked on things more than others"
   OCDB6D = "Having to check on things bother you"
   OCDB6E = "Hard to stop checking on things"
   OCDB6F = "Miss things due to checking on things"
   OCDB6G = "Bad thng might happn if you don't check"
   OCDB6H = "Checking on things make you feel better"
   OCDB6I = "Last 4wks:often checked on things"
   OCDB7A = "Count/do things over and over every day"
   OCDB7B = "Counting/doings over and over bother you"
   OCDB7C = "Hard to stop counting/doing things"
   OCDB7D = "Miss thngs due to counting no. of times"
   OCDB7E = "Bad thng might happen if u didn't count"
   OCDB7F = "Feel better counting/doing a no.of times"
   OCDB8A = "What things have you done over and over"
   OCDB8B = "Had to do things over and over every day"
   OCDB8C = "Doing things over and over upset you"
   OCDB8D = "Hard to stop doing things"
   OCDB8E = "Miss thngs due to doing thngs ovr & ovr"
   OCDB8F = "Bad thing happen if you don't do things"
   OCDB8G = "Doing things make you feel better"
   OCDB8H = "Last 4wks:often doing things over & over"
   OCDBX1 = "Were 2/>2 responses coded in B-E"
   OCDBX2 = "Was 2/>2 responses coded in C-E"
   OCDBX3 = "Was 2/>2 responses coded in C-E"
   OCDBX4 = "Was 2/>2 responses coded in B-F"
   OCDBX5 = "Was 2/>2 responses coded in D-H"
   OCDBX6 = "Was 2/>2 responses coded in B-F"
   OCDBX7 = "Was 2/>2 responses coded in C-G"
   OCDB21A = "Age thoughts were worst" ;

LENGTH
   VISIT 3                  OCDB1 3                  OCDB2 3               
   OCDB3 3                  OCDB4 3                  OCDB5 3               
   OCDB6 3                  OCDB7 3                  OCDB8 3               
   OCDB9 3                  OCDB10 3                 OCDB11 3              
   OCDB12 3                 OCDB13 3                 OCDB14 3              
   OCDB15 3                 OCDB16 3                 OCDB17 3              
   OCDB18 3                 OCDB19 3                 OCDB20 3              
   OCDB21 3                 OCDB11A 3                OCDB11B 3             
   OCDB11C 3                OCDB11D 3                OCDB11DGR 3           
   OCDB11E 3                OCDB11GR 3               OCDB12A 3             
   OCDB13A 3                OCDB14A 3                OCDB15A 3             
   OCDB16A 3                OCDB17A 3                OCDB17AYA 3           
   OCDB17YA 3               OCDB18A 3                OCDB19A 3             
   OCDB1A 3                 OCDB1B 3                 OCDB1C 3              
   OCDB1D 3                 OCDB1E 3                 OCDB1F 3              
   OCDB20A 3                OCDB21AGR 3              OCDB2A 3              
   OCDB2B 3                 OCDB2C 3                 OCDB2D 3              
   OCDB2E 3                 OCDB2F 3                 OCDB3A 3              
   OCDB3B 3                 OCDB3C 3                 OCDB3D 3              
   OCDB3E 3                 OCDB3F 3                 OCDB5A 3              
   OCDB5B 3                 OCDB5C 3                 OCDB5D 3              
   OCDB5E 3                 OCDB5F 3                 OCDB5G 3              
   OCDB6A 3                 OCDB6B 3                 OCDB6C 3              
   OCDB6D 3                 OCDB6E 3                 OCDB6F 3              
   OCDB6G 3                 OCDB6H 3                 OCDB6I 3              
   OCDB7A 3                 OCDB7B 3                 OCDB7C 3              
   OCDB7D 3                 OCDB7E 3                 OCDB7F 3              
   OCDB8A 3                 OCDB8B 3                 OCDB8C 3              
   OCDB8D 3                 OCDB8E 3                 OCDB8F 3              
   OCDB8G 3                 OCDB8H 3                 OCDBX1 3              
   OCDBX2 3                 OCDBX3 3                 OCDBX4 3              
   OCDBX5 3                 OCDBX6 3                 OCDBX7 3              
   OCDB21A 3 ;

       

RUN ;
