/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ocdm1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ocdm1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=128;
INPUT
   CENTER $ 1-2             ID $ 3-9                 YOC011B $ 10-11       
   YOC011E $ 12-13          YOC011J $ 14-15          YOC001  16            
   YOC001A  17              YOC001B  18              YOC001C  19           
   YOC001D  20              YOC001E  21              YOC002  22            
   YOC002A  23              YOC002B  24              YOC002C  25           
   YOC002D  26              YOC002E  27              YOC003  28            
   YOC003A  29              YOC003B  30              YOC003C  31           
   YOC003D  32              YOC003E  33              YOC004  34            
   YOC005  35               YOC005A  36              YOC005B  37           
   YOC005C  38              YOC005D  39              YOC005E  40           
   YOC005F  41              YOC006  42               YOC006A  43           
   YOC006B  44              YOC006C  45              YOC006D  46           
   YOC006E  47              YOC006F  48              YOC006G  49           
   YOC006H  50              YOC007  51               YOC007A  52           
   YOC007B  53              YOC007C  54              YOC007D  55           
   YOC007E  56              YOC007F  57              YOC008  58            
   YOC008A  59              YOC008B  60              YOC008C  61           
   YOC008D  62              YOC008E  63              YOC008F  64           
   YOC008G  65              YOC009  66               YOC010  67            
   YOC011Y  68-69           YOC011Z  70              YOC011A  71           
   YOC011C  72              YOC011D  73              YOC011F  74           
   YOC011G  75              YOC011HY  76-77          YOC011HZ  78          
   YOC011I  79              YOC012  80               YOC012A  81           
   YOC012B  82              YOC013  83               YOC013A  84           
   YOC014  85               YOC014A  86              YOC015  87            
   YOC015A  88              YOC016  89               YOC016A  90           
   YOC017  91               YOC017A  92              YOC018  93            
   YOC018A  94              YOC019  95               YOC019A  96           
   VISIT  97-98             YOCO1A1M  99             YOCO1A2M  100         
   YOCO1A3M  101            YOCO2A1M  102            YOCO2A3M  103         
   YOCO3A1M  104            YOCO3A2M  105            YOCO3A3M  106         
   YOCC1A1M  107            YOCC1A2M  108            YOCC2A1M  109         
   YOCC2A2M  110            YOCC3A1M  111            YOCC3A2M  112         
   YOCC4A1M  113            YOCC4A2M  114            YOCC1CM  115          
   YOCC2CM  116             YOCC3CM  117             YOCC4CM  118          
   YOCOM  119               YOCCM  120               YOCM  121             
   YOCMIMA  122             YOCMIMB  123             YOCMIMC  124          
   YOCMIMD  125             YOCSYMP  126             YOCCRITM  127-128     
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   YOC011B = "Month having thoughts etc. began"
   YOC011E = "Month having thoughts etc. began again"
   YOC011J = "Month started having thoughts again"
   YOC001 = "Last 4 wks: worried things have germs"
   YOC001A = "Worried every day that things have germs"
   YOC001B = "Worried about germs more than others"
   YOC001C = "Have worries about germs with friends"
   YOC001D = "Do worries about germs upset you a lot"
   YOC001E = "Do you try to make these worries go away"
   YOC002 = "Last 4 wks: thoughts about doing bad thing"
   YOC002A = "Had thghts re: bad things over and over"
   YOC002B = "Had thghts re: bad things every day"
   YOC002C = "Have thghts re: bad things with friends"
   YOC002D = "Do thghts re: bad things bother you"
   YOC002E = "Try to make thghts re: bad thngs go away"
   YOC003 = "Last 4 wks: can't get rid of othr thghts"
   YOC003A = "Describe thoughts you can't get rid off"
   YOC003B = "Had thoughts can't get rid off every day"
   YOC003C = "Have thghts can't get rid off wth frnds"
   YOC003D = "Do thghts can't get rid off bother you"
   YOC003E = "Try to make thoughts can't rid go away"
   YOC004 = "Some one/power put thoughts in your head"
   YOC005 = "Last 4 wks: washed hands etc. daily"
   YOC005A = "Washed hands etc. over and over daily"
   YOC005B = "Having to wash hands etc. bother you"
   YOC005C = "Hard to stop washng hands/changng cloths"
   YOC005D = "Miss doing thngs due to washing hands"
   YOC005E = "Somthng bad will happn if you don't wash"
   YOC005F = "Washing hands/body make you feel better"
   YOC006 = "Check on things over and over again"
   YOC006A = "Do you go and check and make sure"
   YOC006B = "Had to keep checking on things every day"
   YOC006C = "Do you check on things more than others"
   YOC006D = "Having to check on things bother you"
   YOC006E = "Hard to stop checking on things"
   YOC006F = "Miss thing due to checking on things"
   YOC006G = "Bad thng might happn if you don't check"
   YOC006H = "Checking on things make you feel better"
   YOC007 = "Had to count/do things over and over"
   YOC007A = "Count/do things over and over every day"
   YOC007B = "Counting/doings over and over bother you"
   YOC007C = "Hard to stop counting/doing things"
   YOC007D = "Miss thngs due to counting no. of times"
   YOC007E = "Bad thng might happen if you don't count"
   YOC007F = "Feel better counting/doing a no.of times"
   YOC008 = "Last 4 wks: do other thing over and over"
   YOC008A = "What things have you done over and over"
   YOC008B = "Had to do things over and over every day"
   YOC008C = "Doing things over and over upset you"
   YOC008D = "Hard to stop doing things"
   YOC008E = "Miss thngs due to doing thngs ovr & ovr"
   YOC008F = "Bad thing happen if you don't do things"
   YOC008G = "Doing things make you feel better"
   YOC009 = "Time spent worrying etc. add up to 1hr"
   YOC010 = "Had thoughts etc. most days for 2 wks"
   YOC011Y = "Age when 1st began to have thoughts etc"
   YOC011Z = "Grade 1st began to have thoughts etc."
   YOC011A = "Had thoughts etc. more than 1 yr ago"
   YOC011C = "Thoughts etc stopped since started again"
   YOC011D = "Stopped having thoughts etc. for 2 mths"
   YOC011F = "Didn't have thghts etc. since 1st time"
   YOC011G = "Thoughts etc.stopped for 2 mths in a row"
   YOC011HY = "Last mth: age having thoughts started"
   YOC011HZ = "Last mth: grade having thoughts started"
   YOC011I = "Started having thoughts again >1 yr ago"
   YOC012 = "Did worrying etc start suddenly"
   YOC012A = "Sick wth fever when worrying etc.started"
   YOC012B = "What was wrong with you"
   YOC013 = "Last 4 wks: having thgts upset caretakers"
   YOC013A = "Often having thghts etc. upset caretakers"
   YOC014 = "Having thoughts etc. prevent famly thngs"
   YOC014A = "Often having thghts prevent family thngs"
   YOC015 = "Having thoughts etc. prevent other thngs"
   YOC015A = "Often thoughts etc. prevent other thngs"
   YOC016 = "Does having thoughts etc. upset you"
   YOC016A = "How bad having thgts etc make you feel"
   YOC017 = "Last 4 wk: havng thgts make wrk difficlt"
   YOC017A = "How bad has school/work problems been"
   YOC018 = "Last 4 wk: thghts etc upset teacher/boss"
   YOC018A = "Often thoughts etc. upset teacher/boss"
   YOC019 = "Seen someone in hospital in lat year"
   YOC019A = "Have appointment due to having thoughts"
   VISIT = "VISIT NUMBER"
   YOCO1A1M = "Recurrent and persistent thoughts about germs"
   YOCO1A2M = "Not simply excessive worries about germs"
   YOCO1A3M = "Attempts to ignore or suppress thoughts about germs"
   YOCO2A1M = "Recurrent and persistent thoughts about doing something bad"
   YOCO2A3M = "Attempts to ignore or suppress thoughts about doing something bad"
   YOCO3A1M = "Recurrent and persistent thoughts - other"
   YOCO3A2M = "Not simply excessive worries - other"
   YOCO3A3M = "Attempts to ignore or suppress thoughts - other"
   YOCC1A1M = "Repetitive behaviors - washing"
   YOCC1A2M = "Washing aimed at preventing or reducing stress"
   YOCC2A1M = "Repetitive behaviors - checking"
   YOCC2A2M = "Checking aimed at preventing or reducing stress"
   YOCC3A1M = "Repetitive behaviors - counting"
   YOCC3A2M = "Counting aimed at preventing or reducing stress"
   YOCC4A1M = "Repetitive behaviors - other"
   YOCC4A2M = "Other behavior aimed at preventing or reducing stress"
   YOCC1CM = "Distress, time-consuming, or interfere - washing"
   YOCC2CM = "Distress, time-consuming, or interfere - checking"
   YOCC3CM = "Distress, time-consuming, or interfere - counting"
   YOCC4CM = "Distress, time-consuming, or interfere - other"
   YOCOM = "Diagnosis for obsession"
   YOCCM = "Diagnosis for compulsion"
   YOCM = "Diagnosis for obsession-compulsion disorder"
   YOCMIMA = "OCD Impairment A"
   YOCMIMB = "OCD Impairment B"
   YOCMIMC = "OCD Impairment C"
   YOCMIMD = "OCD Impairment D"
   YOCSYMP = "OCD Symptom Count"
   YOCCRITM = "OCD Criterion Count" ;

LENGTH
   YOC001 3                 YOC001A 3                YOC001B 3             
   YOC001C 3                YOC001D 3                YOC001E 3             
   YOC002 3                 YOC002A 3                YOC002B 3             
   YOC002C 3                YOC002D 3                YOC002E 3             
   YOC003 3                 YOC003A 3                YOC003B 3             
   YOC003C 3                YOC003D 3                YOC003E 3             
   YOC004 3                 YOC005 3                 YOC005A 3             
   YOC005B 3                YOC005C 3                YOC005D 3             
   YOC005E 3                YOC005F 3                YOC006 3              
   YOC006A 3                YOC006B 3                YOC006C 3             
   YOC006D 3                YOC006E 3                YOC006F 3             
   YOC006G 3                YOC006H 3                YOC007 3              
   YOC007A 3                YOC007B 3                YOC007C 3             
   YOC007D 3                YOC007E 3                YOC007F 3             
   YOC008 3                 YOC008A 3                YOC008B 3             
   YOC008C 3                YOC008D 3                YOC008E 3             
   YOC008F 3                YOC008G 3                YOC009 3              
   YOC010 3                 YOC011Y 3                YOC011Z 3             
   YOC011A 3                YOC011C 3                YOC011D 3             
   YOC011F 3                YOC011G 3                YOC011HY 3            
   YOC011HZ 3               YOC011I 3                YOC012 3              
   YOC012A 3                YOC012B 3                YOC013 3              
   YOC013A 3                YOC014 3                 YOC014A 3             
   YOC015 3                 YOC015A 3                YOC016 3              
   YOC016A 3                YOC017 3                 YOC017A 3             
   YOC018 3                 YOC018A 3                YOC019 3              
   YOC019A 3                VISIT 3                  YOCO1A1M 3            
   YOCO1A2M 3               YOCO1A3M 3               YOCO2A1M 3            
   YOCO2A3M 3               YOCO3A1M 3               YOCO3A2M 3            
   YOCO3A3M 3               YOCC1A1M 3               YOCC1A2M 3            
   YOCC2A1M 3               YOCC2A2M 3               YOCC3A1M 3            
   YOCC3A2M 3               YOCC4A1M 3               YOCC4A2M 3            
   YOCC1CM 3                YOCC2CM 3                YOCC3CM 3             
   YOCC4CM 3                YOCOM 3                  YOCCM 3               
   YOCM 3                   YOCMIMA 3                YOCMIMB 3             
   YOCMIMC 3                YOCMIMD 3                YOCSYMP 3             
   YOCCRITM 3 ;

      

RUN ;
