/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\pcpb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = pcpb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=31;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   PCPB3  12                PCPB4  13                PCPB5  14             
   PCPB6  15                PCPB7  16                PCPB8  17             
   PCPB9  18                PCPB10  19               PCPB11  20            
   PCPB12  21               PCPB13  22               PCPB14  23            
   PCPB15  24               PCPB16  25               PCPB17  26            
   PCPB18  27               PCPB19  28               PCPB20  29            
   PCPB21  30               PCPB22  31             ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   PCPB3 = "How close do you feel to child"
   PCPB4 = "How much do you care about child"
   PCPB5 = "How often child interferes w/activities"
   PCPB6 = "How often do you trust child"
   PCPB7 = "How often feel you understand child"
   PCPB8 = "How often do you and s/he get along well"
   PCPB9 = "How often do you make decisions together"
   PCPB10 = "Feel you interfere w/childs activities"
   PCPB11 = "Pst 4wks:gone shopping with him/her"
   PCPB12 = "Pst 4wks:played a sport with him/her"
   PCPB13 = "Pst 4wks:gone to religious event w/him/her"
   PCPB14 = "Pst 4wks:talked about his/her friends"
   PCPB15 = "Pst 4wks:gone to movie/event with him/her"
   PCPB16 = "Pst 4wks:talked about personal problem"
   PCPB17 = "Pst 4wks:had a serious argument"
   PCPB18 = "Pst 4wks:talked ab. his/her school work"
   PCPB19 = "Pst 4wks:worked on a school project"
   PCPB20 = "Talked about othr school things"
   PCPB21 = "How disappoin./child didnt grad hi schl"
   PCPB22 = "How disappoin./child didnt grad college" ;

LENGTH
   VISIT 3                  PCPB3 3                  PCPB4 3               
   PCPB5 3                  PCPB6 3                  PCPB7 3               
   PCPB8 3                  PCPB9 3                  PCPB10 3              
   PCPB11 3                 PCPB12 3                 PCPB13 3              
   PCPB14 3                 PCPB15 3                 PCPB16 3              
   PCPB17 3                 PCPB18 3                 PCPB19 3              
   PCPB20 3                 PCPB21 3                 PCPB22 3 ;

        

RUN ;
