/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\pera0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = pera0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=56;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   pera1  11                pera2  12                pera3  13-14          
   pera4a  15-16            pera4b  17-18            pera5  19             
   pera6a  20               pera6b  21-22            pera7  23             
   pera8a  24               pera8b  25               pera8c  26            
   pera9 $ 27-29            pera10 DATE11.           respndt $ 41-56       
 ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   pera1 = "mo received prenatal care"
   pera2 = "month 1st prenatal visit"
   pera3 = "number of prenatal visits"
   pera4a = "weight of child at birth-lbs"
   pera4b = "weight of child at birth-oz"
   pera5 = "child premature (<37 weeks)"
   pera6a = "child in special newborn unit"
   pera6b = "# nights in special newborn unit"
   pera7 = "child received oxygen at birth"
   pera8a = "rec home visits in parenting"
   pera8b = "attended parent group on parenting"
   pera8c = "took class in parenting"
   pera9 = "interviewer initials"
   pera10 = "date of interview"
   respndt = "respondent relationship to child" ;

FORMAT
   pera10 DATE9.          ;
                     

LENGTH
   visit 3                  pera1 3                  pera2 3               
   pera3 3                  pera4a 3                 pera4b 3              
   pera5 3                  pera6a 3                 pera6b 3              
   pera7 3                  pera8a 3                 pera8b 3              
   pera8c 3 ;

        

RUN ;
