/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\pgrb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = pgrb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=30;
INPUT
   CENTER $ 1-2             ID $ 3-9                 PGRB6H $ 10-12        
   VISIT  13-14             PGRB6E  15               PGRB6E1  16-17        
   PGRB6F  18               PGRB6G  19               PGRB6I DATE11.        
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   PGRB6H = "Interviewer initials"
   VISIT = "VISIT NUMBER"
   PGRB6E = "Does child have a best friend?"
   PGRB6E1 = "How old is child^s best friend?"
   PGRB6F = "How physically attractive is child?"
   PGRB6G = "How happy has child been this year?"
   PGRB6I = "Date of interview" ;

FORMAT
   PGRB6I DATE9. ;
     

LENGTH
   VISIT 3                  PGRB6E 3                 PGRB6E1 3             
   PGRB6F 3                 PGRB6G 3 ;

        

RUN ;
