/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\pmpa1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = pmpa1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=30;
INPUT
   CENTER $ 1-2             ID $ 3-9                 PMPA6 $ 10-12         
   VISIT  13-14             PMPA1  15                PMPA2  16             
   PMPA3  17                PMPA4  18                PMPA5  19             
   PMPA7 DATE11.          ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   PMPA6 = "Interviewer initials"
   VISIT = "VISIT NUMBER"
   PMPA1 = "Know who child's friends are"
   PMPA2 = "Know where child goes at night"
   PMPA3 = "Know how child spends his/her money"
   PMPA4 = "Know what child does with free time"
   PMPA5 = "Know where child is after school"
   PMPA7 = "Date of interview" ;

FORMAT
   PMPA7 DATE9. ;
      

LENGTH
   VISIT 3                  PMPA1 3                  PMPA2 3               
   PMPA3 3                  PMPA4 3                  PMPA5 3 ;

         

RUN ;
