/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\prla1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = prla1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=18;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   PRLA1  12                PRLA2  13                PRLA3  14             
   PRLA4  15                PRLA4A  16               PRLA5  17             
   PRLA5A  18             ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   PRLA1 = "How many kids at school are friendly"
   PRLA2 = "How many kids ignore you"
   PRLA3 = "How many kids at school unfriendly"
   PRLA4 = "Group you usually hang around with?"
   PRLA4A = "How satisfied with this group"
   PRLA5 = "Do you have a best friend"
   PRLA5A = "How satisfied with this friendship" ;

LENGTH
   VISIT 3                  PRLA1 3                  PRLA2 3               
   PRLA3 3                  PRLA4 3                  PRLA4A 3              
   PRLA5 3                  PRLA5A 3 ;

        

RUN ;
