/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ptsm1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ptsm1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=117;
INPUT
   CENTER $ 1-2             ID $ 3-9                 YPT001  10            
   YPT002  11               YPT003  12               YPT004  13            
   YPT004A  14              YPT005  15               YPT006  16            
   YPT007  17               YPT008  18               YPT009  19            
   YPT009A  20              YPT010  21               YPT010A  22           
   YPT011  23               YPT012  24               YPT013  25            
   YPT014  26               YPT015  27               YPT016  28            
   YPT016A  29              YPT016B  30              YPT017  31            
   YPT018  32               YPT018A  33              YPT019  34            
   YPT019A  35              YPT020  36               YPT021  37            
   YPT021A  38              YPT021C  39              YPT022  40            
   YPT023  41               YPT024  42               YPT025  43            
   YPT026  44               YPT026A  45              YPT027  46            
   YPT027A  47              YPT028  48               YPT028A  49           
   YPT029  50               YPT029A  51              YPT030  52            
   YPT030A  53              YPT031  54               YPT031A  55           
   YPT032  56               YPT032A  57              YPT033  58            
   YPT033A  59              YPT034  60               YPT034A  61           
   YPT034B  62              YPT035  63               YPT036  64            
   YPT036A  65              YPT037  66               YPT037A  67           
   YPT038  68               YPT038A  69              YPT039  70            
   YPT039A  71              YPT040  72               YPT040A  73           
   YPT041  74               YPT041A  75              YPT042  76            
   YPT042A  77              VISIT  78-79             YPTA1M  80            
   YPTA2M  81               YPTAM  82                YPTB1M  83            
   YPTB2M  84               YPTB3M  85               YPTB4M  86            
   YPTB5M  87               YPTBM  88                YPTC1M  89            
   YPTC2M  90               YPTC3M  91               YPTC4M  92            
   YPTC5M  93               YPTC6M  94               YPTC7M  95            
   YPTCM  96                YPTD1M  97               YPTD2M  98            
   YPTD3M  99               YPTD4M  100              YPTD5M  101           
   YPTDM  102               YPTEM  103               YPTM  104             
   YPT1M  105               YPT2M  106               YPT3M  107            
   YPTMIMA  108             YPTMIMB  109             YPTMIMC  110          
   YPTMIMD  111             YPTSYMP  112-115         YPTCRITM  116-117     
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   YPT001 = "Ever been in a natural disaster"
   YPT002 = "Ever you/close one was to be killd/hurt"
   YPT003 = "Ever attacked by somebody"
   YPT004 = "Upset being forced to do somthng sexual"
   YPT004A = "Ever attacked sexually or raped"
   YPT005 = "Ever threatened by weapon"
   YPT006 = "Ever been in a bad accident"
   YPT007 = "Ever seen/heard somebody get killed"
   YPT008 = "Ever been upset by seeing dead body"
   YPT009 = "Natural disaster etc. happened > once"
   YPT009A = "Last 4 wks: thght abt nat disaster etc."
   YPT010 = "Natural disaster etc. happen same time"
   YPT010A = "Last 4 wks: thght abt nat. disaster etc."
   YPT011 = "Last 4 wks: often thght about wht happnd"
   YPT012 = "Afraid when you were/saw/heard event"
   YPT013 = "Helpless when you were/saw/heard event"
   YPT014 = "Going crazy whn you were/saw/heard event"
   YPT015 = "Last 4 wks: did traumatic event happen"
   YPT016 = "Last 4 wks:  thought about traum. event"
   YPT016A = "Though about traum. event at schl/wrk"
   YPT016B = "Thinking about traum. event upset you"
   YPT017 = "Last 4 wks: played game somone gets hurt"
   YPT018 = "Last 4 wks: had problems falling asleep"
   YPT018A = "More sleep trbl than before traum. event"
   YPT019 = "Last 4 wks: had a lot of nightmares"
   YPT019A = "Were these nightmares traumatic"
   YPT020 = "Last 4 wks: reliving traumatic event"
   YPT021 = "Last 4 wks: thngs make you rembr trauma"
   YPT021A = "Last 4 wks: nervous whn thngs remnd you"
   YPT021C = "Last 4 wks: start to sweat when reminded"
   YPT022 = "Last 4 wks: tried not to thnk abt trauma"
   YPT023 = "Last 4 wks: stopped going places"
   YPT024 = "Last 4 wks: tried to keep away frm peple"
   YPT025 = "Last 4wks: can't  rember parts of trauma"
   YPT026 = "Last 4 wks: felt less intrested in thngs"
   YPT026A = "Less interest a change frm before trauma"
   YPT027 = "Last 4 wks: felt separate from others"
   YPT027A = "Separate feeling a change frm bfr trauma"
   YPT028 = "Last 4 wks: hard to feel strong abt othr"
   YPT028A = "Hard to feel strong a change from before"
   YPT029 = "Last 4 wks: stopped thinkng about future"
   YPT029A = "Is stopped thinkng about future a change"
   YPT030 = "Last 4 wks: lost temper/more grouchy"
   YPT030A = "Lost temper a change form before trauma"
   YPT031 = "Last 4 wks: hard to keep mind on things"
   YPT031A = "Is hard to keep mind on things a change"
   YPT032 = "Last 4 wks: jumpy/nervous"
   YPT032A = "Jumpy/nervous a change frm before trauma"
   YPT033 = "Last 4 wks: jumped at sudden noises"
   YPT033A = "Jumped at sudden noises a change"
   YPT034 = "Thghts of traum. etc: bothered for 1 mth"
   YPT034A = "Thghts of traum. etc: bothrd 2 dys/longr"
   YPT034B = "Thghts of traum. etc: bothrd 3 mth/longr"
   YPT035 = "How soon after trauma start bng bothered"
   YPT036 = "Last 4 wks: trauma feelngs upset cartakr"
   YPT036A = "Often trauma feelings upset caretaker"
   YPT037 = "The way you feel/act prevent famly thngs"
   YPT037A = "Often way you feel prevent family things"
   YPT038 = "The way you feel/act prevent other thngs"
   YPT038A = "Often way you feel prevent other things"
   YPT039 = "The way you feel/act make you feel bad"
   YPT039A = "How bad being like this makes you feel"
   YPT040 = "Last 4 wks: way feel make wrk difficult"
   YPT040A = "How bad are/were school/work problems"
   YPT041 = "Way you feel/act upset teacher/boss"
   YPT041A = "Often way you feel/act upset teachr/boss"
   YPT042 = "Seen someone in hospital in last 4 wks"
   YPT042A = "Have appointment because of way you feel"
   VISIT = "VISIT NUMBER"
   YPTA1M = "Experienced, witnessed, or confronted event"
   YPTA2M = "Response involved fear, helplessness, or horror"
   YPTAM = "Exposure"
   YPTB1M = "Recurrent intrusive distressing recollections"
   YPTB2M = "Recurrent distressing dreams of event"
   YPTB3M = "Acting or feeling as event recurring"
   YPTB4M = "Intense psychological distress at cues"
   YPTB5M = "Physiological reactivity to cues"
   YPTBM = "Trauma persistently reexperienced"
   YPTC1M = "Avoid thoughts, feelings, or conversations"
   YPTC2M = "Avoid activities, places, or people"
   YPTC3M = "Inability to recall"
   YPTC4M = "Diminished interest in activities"
   YPTC5M = "Detachment or estrangement"
   YPTC6M = "Restricted range of affect"
   YPTC7M = "Sense of foreshortened future"
   YPTCM = "Avoidance of stimuli associated and numbing of responsiveness"
   YPTD1M = "Difficulty sleeping"
   YPTD2M = "Irritability or outbursts of anger"
   YPTD3M = "Difficulty concentrating"
   YPTD4M = "Hypervigilance"
   YPTD5M = "Exaggerated startle response"
   YPTDM = "Persistent symptoms of increased arousal"
   YPTEM = "Duration more than 1 month"
   YPTM = "Dianosis for post traumatic stress disorder"
   YPT1M = "One month: Acute"
   YPT2M = "One month: Chronic"
   YPT3M = "One month: With delayed onset"
   YPTMIMA = "PTSD Impairment A"
   YPTMIMB = "PTSD Impairment B"
   YPTMIMC = "PTSD Impairment C"
   YPTMIMD = "PTSD Impairment D"
   YPTSYMP = "PTSD Symptom Count"
   YPTCRITM = "PTSD Criterion Count" ;

LENGTH
   YPT001 3                 YPT002 3                 YPT003 3              
   YPT004 3                 YPT004A 3                YPT005 3              
   YPT006 3                 YPT007 3                 YPT008 3              
   YPT009 3                 YPT009A 3                YPT010 3              
   YPT010A 3                YPT011 3                 YPT012 3              
   YPT013 3                 YPT014 3                 YPT015 3              
   YPT016 3                 YPT016A 3                YPT016B 3             
   YPT017 3                 YPT018 3                 YPT018A 3             
   YPT019 3                 YPT019A 3                YPT020 3              
   YPT021 3                 YPT021A 3                YPT021C 3             
   YPT022 3                 YPT023 3                 YPT024 3              
   YPT025 3                 YPT026 3                 YPT026A 3             
   YPT027 3                 YPT027A 3                YPT028 3              
   YPT028A 3                YPT029 3                 YPT029A 3             
   YPT030 3                 YPT030A 3                YPT031 3              
   YPT031A 3                YPT032 3                 YPT032A 3             
   YPT033 3                 YPT033A 3                YPT034 3              
   YPT034A 3                YPT034B 3                YPT035 3              
   YPT036 3                 YPT036A 3                YPT037 3              
   YPT037A 3                YPT038 3                 YPT038A 3             
   YPT039 3                 YPT039A 3                YPT040 3              
   YPT040A 3                YPT041 3                 YPT041A 3             
   YPT042 3                 YPT042A 3                VISIT 3               
   YPTA1M 3                 YPTA2M 3                 YPTAM 3               
   YPTB1M 3                 YPTB2M 3                 YPTB3M 3              
   YPTB4M 3                 YPTB5M 3                 YPTBM 3               
   YPTC1M 3                 YPTC2M 3                 YPTC3M 3              
   YPTC4M 3                 YPTC5M 3                 YPTC6M 3              
   YPTC7M 3                 YPTCM 3                  YPTD1M 3              
   YPTD2M 3                 YPTD3M 3                 YPTD4M 3              
   YPTD5M 3                 YPTDM 3                  YPTEM 3               
   YPTM 3                   YPT1M 3                  YPT2M 3               
   YPT3M 3                  YPTMIMA 3                YPTMIMB 3             
   YPTMIMC 3                YPTMIMD 3                YPTCRITM 3 ;

      

RUN ;
