/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sadm1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sadm1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=98;
INPUT
   CENTER $ 1-2             ID $ 3-9                 YSA014B $ 10-11       
   YSA014E $ 12-13          YSA014J $ 14-15          YSA001  16            
   YSA001A  17              YSA002  18               YSA002A  19           
   YSA003  20               YSA003A  21              YSA004  22            
   YSA004A  23              YSA004B  24              YSA005  25            
   YSA005A  26              YSA006  27               YSA006A  28           
   YSA006B  29              YSA006C  30              YSA006D  31           
   YSA006E  32              YSA007  33               YSA007A  34           
   YSA007B  35              YSA008  36               YSA008A  37           
   YSA009  38               YSA009A  39              YSA010  40            
   YSA010A  41              YSA011  42               YSA011A  43           
   YSA011B  44              YSA011D  45              YSA011E  46           
   YSA012  47               YSA012A  48              YSA012B  49           
   YSA014Y  50-51           YSA014Z  52              YSA014A  53           
   YSA014C  54              YSA014D  55              YSA014F  56           
   YSA014G  57              YSA014HY  58-59          YSA014HZ  60          
   YSA014I  61              YSA015  62               YSA015A  63           
   YSA016  64               YSA016A  65              YSA017  66            
   YSA017A  67              YSA018  68               YSA018A  69           
   YSA019  70               YSA019A  71              YSA020  72            
   YSA020A  73              YSA021  74               YSA021A  75           
   VISIT  76-77             YSAA1M  78               YSAA2M  79            
   YSAA3M  80               YSAA4M  81               YSAA5M  82            
   YSAA6M  83               YSAA7M  84               YSAA8M  85            
   YSAAM  86                YSABM  87                YSACM  88             
   YSAM  89                 YSAMIMA  90              YSAMIMB  91           
   YSAMIMC  92              YSAMIMD  93              YSACRITM  94          
   YSASYMP  95-98         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   YSA014B = "What month started worrying"
   YSA014E = "Month you started worrying again"
   YSA014J = "Month you started worrying again"
   YSA001 = "Wanted to stay at home"
   YSA001A = "Nervous/afraid away from home"
   YSA002 = "Sick before going to school/work"
   YSA002A = "Felt sick for several weeks"
   YSA003 = "Felt sick if not with person"
   YSA003A = "Sick if not with person for weeks"
   YSA004 = "Had bad dreams/nightmares"
   YSA004A = "Nightmares about family getting sick"
   YSA004B = "Nightmares more than once"
   YSA005 = "Want person near before falling asleep"
   YSA005A = "Want person near for several weeks"
   YSA006 = "Invited to spend night away from home"
   YSA006A = "Worried about spending night away"
   YSA006B = "Worry more about spending night away"
   YSA006C = "Spent night away in last four weeks"
   YSA006D = "Got upset while away for the night"
   YSA006E = "Did not go away because of worry"
   YSA007 = "Kept worrying accident might happen"
   YSA007A = "Worry more than others about accident"
   YSA007B = "Worried about something bad happening"
   YSA008 = "Worrying about person going away"
   YSA008A = "Worried for weeks person going away"
   YSA009 = "Worried you might be without family"
   YSA009A = "Worried something happening for weeks"
   YSA010 = "Felt nervous when not with person"
   YSA010A = "Nervous when not with person for weeks"
   YSA011 = "Not gone out because without you"
   YSA011A = "Get upset/beg person not to leave"
   YSA011B = "Got upset with person for weeks"
   YSA011D = "Not gone places because without you"
   YSA011E = "Has this happened more than once"
   YSA012 = "Been away from home without person"
   YSA012A = "Upset/homesick because you missed person"
   YSA012B = "Was missing worse for you than others"
   YSA014Y = "Age when you first began to worry"
   YSA014Z = "What grade were you in"
   YSA014A = "Was worrying more than a year ago"
   YSA014C = "Was there a time you were not worried"
   YSA014D = "Time not worried last two months"
   YSA014F = "Ever a time when you were not worried"
   YSA014G = "When you worried last for two mths/more"
   YSA014HY = "When period of worrying started"
   YSA014HZ = "What grade were you in"
   YSA014I = "Started worrying again before last year"
   YSA015 = "Caretakers seem annoyed with you"
   YSA015A = "How often caretakers seemed annoyed"
   YSA016 = "Worrying prevents things with family"
   YSA016A = "How often prevents family things"
   YSA017 = "Worrying prevents things with others"
   YSA017A = "How often prevents things with others"
   YSA018 = "Worrying being away makes you feel bad"
   YSA018A = "How bad does worrying make you feel"
   YSA019 = "Worrying made doing schl work difficult"
   YSA019A = "How bad has school work problems been"
   YSA020 = "Worrying make teachers upset with you"
   YSA020A = "How often teachers been upset with you"
   YSA021 = "Seen someone in hospital in last year"
   YSA021A = "Have appointment because you worry"
   VISIT = "VISIT NUMBER"
   YSAA1M = "Distress when separated from home or AF"
   YSAA2M = "Worry about losing or harm to AF"
   YSAA3M = "Worry about untoward event to self"
   YSAA4M = "Refusal to go to school or elsewhere"
   YSAA5M = "Fearful about being without AF or alone"
   YSAA6M = "Refusal to sleep alone - away"
   YSAA7M = "Nightmares involving separation"
   YSAA8M = "Physical symptoms when separated"
   YSAAM = "Anxiety concerning separation"
   YSABM = "Duration at least 4 weeks"
   YSACM = "Onset before age 18"
   YSAM = "Month: diagnosis for Separation Anxiety"
   YSAMIMA = "Separation anxiety impairment A"
   YSAMIMB = "Separation anxiety impairment B"
   YSAMIMC = "Separation anxiety impairment C"
   YSAMIMD = "Separation anxiety impairment D"
   YSACRITM = "Separation anxiety criteria count"
   YSASYMP = "Separation anxiety symptom count" ;

LENGTH
   YSA001 3                 YSA001A 3                YSA002 3              
   YSA002A 3                YSA003 3                 YSA003A 3             
   YSA004 3                 YSA004A 3                YSA004B 3             
   YSA005 3                 YSA005A 3                YSA006 3              
   YSA006A 3                YSA006B 3                YSA006C 3             
   YSA006D 3                YSA006E 3                YSA007 3              
   YSA007A 3                YSA007B 3                YSA008 3              
   YSA008A 3                YSA009 3                 YSA009A 3             
   YSA010 3                 YSA010A 3                YSA011 3              
   YSA011A 3                YSA011B 3                YSA011D 3             
   YSA011E 3                YSA012 3                 YSA012A 3             
   YSA012B 3                YSA014Y 3                YSA014Z 3             
   YSA014A 3                YSA014C 3                YSA014D 3             
   YSA014F 3                YSA014G 3                YSA014HY 3            
   YSA014HZ 3               YSA014I 3                YSA015 3              
   YSA015A 3                YSA016 3                 YSA016A 3             
   YSA017 3                 YSA017A 3                YSA018 3              
   YSA018A 3                YSA019 3                 YSA019A 3             
   YSA020 3                 YSA020A 3                YSA021 3              
   YSA021A 3                VISIT 3                  YSAA1M 3              
   YSAA2M 3                 YSAA3M 3                 YSAA4M 3              
   YSAA5M 3                 YSAA6M 3                 YSAA7M 3              
   YSAA8M 3                 YSAAM 3                  YSABM 3               
   YSACM 3                  YSAM 3                   YSAMIMA 3             
   YSAMIMB 3                YSAMIMC 3                YSAMIMD 3             
   YSACRITM 3 ;

      

RUN ;
