/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\safa0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = safa0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=109;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   safa1  11                safa2  12                safa3  13             
   safa4  14                safa5  15                safa6  16             
   safa7  17                safa8  18                safa9  19             
   safa9a  20-21            safa9b  22-23            safa9c  24-25         
   safa9d  26-27            safa9d1 $ 28-57          safa10  58            
   safa10a  59-60           safa10b  61              safa10c  62-63        
   safa10d  64-65           safa10d1 $ 66-95         safa11 $ 96-98        
   safa12 DATE11.         ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   safa1 = "students safe from violence on playgrnd"
   safa2 = "school safe place for teachrs & students"
   safa3 = "school is in safe neighborhood"
   safa4 = "open drug activity in area around school"
   safa5 = "drug activity in school"
   safa6 = "students in school who carry weapons"
   safa7 = "maintain discipline is continual problem"
   safa8 = "students involved in gangs in school"
   safa9 = "students crime victims at school"
   safa9a = "#times students victims of theft at schl"
   safa9b = "# times students mugged at school"
   safa9c = "# times students assaulted at school"
   safa9d = "#times students hit w othr crime at schl"
   safa9d1 = "describe other crime against student"
   safa10 = "teachers crime victims at school"
   safa10a = "#times teachers victims of theft at schl"
   safa10b = "# times teachers mugged at school"
   safa10c = "# times teachers assaulted at school"
   safa10d = "#times teachers hit w othr crime at schl"
   safa10d1 = "describe other crime against teacher"
   safa11 = "interviewer initials"
   safa12 = "date of interview" ;

FORMAT
   safa12 DATE9. ;
     

LENGTH
   visit 3                  safa1 3                  safa2 3               
   safa3 3                  safa4 3                  safa5 3               
   safa6 3                  safa7 3                  safa8 3               
   safa9 3                  safa9a 3                 safa9b 3              
   safa9c 3                 safa9d 3                 safa10 3              
   safa10a 3                safa10b 3                safa10c 3             
   safa10d 3 ;

       

RUN ;
