/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sals1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sals1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=136;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   NCON18_S  12             NCON18_I  13             NPEN18_S  14          
   NPEN18_I  15             PEN18_S  16              PEN18_I  17           
   SEXABU18_S  18-19        SEXABU18_I  20           SEX_5_S  21           
   SEX_5_I  22              SEX_612_S  23            SEX_612_I  24         
   SEX_1316_S  25           SEX_1316_I  26           SEX_17_S  27          
   SEX_17_I  28             SEX_5_F  29-30           SEX_612_F  31-32      
   SEX_1316_F  33-34        SEX_17_F  35             SEX_F18  36-37        
   S_MOM5  38               S_MOM612  39             S_MOM1316  40         
   S_MOM17  41              S_MOM18  42              S_SMOM5  43           
   S_SMOM612  44            S_SMOM1316  45           S_SMOM17  46          
   S_SMOM18  47             S_FMOM5  48              S_FMOM612  49         
   S_FMOM1316  50           S_FMOM17  51             S_FMOM18  52          
   S_PGF5  53               S_PGF612  54             S_PGF1316  55         
   S_PGF17  56              S_PGF18  57              S_DAD5  58            
   S_DAD612  59             S_DAD1316  60            S_DAD17  61           
   S_DAD18  62              S_SDAD5  63              S_SDAD612  64         
   S_SDAD1316  65           S_SDAD17  66             S_SDAD18  67          
   S_FDAD5  68              S_FDAD612  69            S_FDAD1316  70        
   S_FDAD17  71             S_FDAD18  72             S_PBF5  73            
   S_PBF612  74             S_PBF1316  75            S_PBF17  76           
   S_PBF18  77              S_OFAM5  78              S_OFAM612  79         
   S_OFAM1316  80           S_OFAM17  81             S_OFAM18  82          
   S_TEA5  83               S_TEA612  84             S_TEA1316  85         
   S_TEA17  86              S_TEA18  87              S_SE5  88             
   S_SE612  89              S_SE1316  90             S_SE17  91            
   S_SE18  92               S_FAMILY5  93            S_FAMILY612  94       
   S_FAMILY1316  95         S_FAMILY17  96           S_FAMILY18  97        
   S_NFAM5  98              S_NFAM612  99            S_NFAM1316  100       
   S_NFAM17  101            S_NFAM18  102            S_IMP_MAX18  103      
   S_IMP_MN18  104-119      S_ATT_MAX18  120         S_ATT_MN18  121-136   
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   NCON18_S = "Non-Contact Sexual Abuse Score"
   NCON18_I = "Ind of Non-Contact Sexual Abuse"
   NPEN18_S = "Sexual Contact, Non-Penetration Score"
   NPEN18_I = "Ind of Sexual Contact, Non-Penetration"
   PEN18_S = "Sexual Contact, Penetration Score"
   PEN18_I = "Ind of Sexual Contact, Penetration"
   SEXABU18_S = "Sexual Abuse Score"
   SEXABU18_I = "Ind of Sexual Abuse"
   SEX_5_S = "Sexual Abuse SUM Score (<= age 5)"
   SEX_5_I = "Indicator of Sexual Abuse (<= age 5)"
   SEX_612_S = "Sexual Abuse SUM Score (6-12 yrs)"
   SEX_612_I = "Indicator of Sexual Abuse (6-12 yrs)"
   SEX_1316_S = "Sexual Abuse SUM Score (13-16 yrs)"
   SEX_1316_I = "Indicator of Sexual Abuse (13-16 yrs)"
   SEX_17_S = "Sexual Abuse SUM Score (>= 17 yrs)"
   SEX_17_I = "Indicator of Sexual Abuse (>= 17 yrs)"
   SEX_5_F = "Sexual Abuse Freq Score (<= age 5)"
   SEX_612_F = "Sexual Abuse Freq Score (6-12 yrs)"
   SEX_1316_F = "Sexual Abuse Freq Score (13-16 yrs)"
   SEX_17_F = "Sexual Abuse Freq Score (>= 17 yrs)"
   SEX_F18 = "Sexual Abuse Freq Score (ever occurred)"
   S_MOM5 = "Ind of Sexual Abuse by Mother (<= 5 yrs)"
   S_MOM612 = "Ind of Sexual Abuse by Mother (6-12 yrs)"
   S_MOM1316 = "Ind of Sexual Abuse by Mother (13-16 yrs)"
   S_MOM17 = "Ind of Sexual Abuse by Mother (>= 17 yrs)"
   S_MOM18 = "Ind of Sexual Abuse by Mother (ever occurred)"
   S_SMOM5 = "Ind of Sexual Abuse by Step Mother (<= 5 yrs)"
   S_SMOM612 = "Ind of Sexual Abuse by Step Mother (6-12 yrs)"
   S_SMOM1316 = "Ind of Sexual Abuse by Step Mother (13-16 yrs)"
   S_SMOM17 = "Ind of Sexual Abuse by Step Mother (>= 17 yrs)"
   S_SMOM18 = "Ind of Sexual Abuse by Step Mother (ever occurred)"
   S_FMOM5 = "Ind of Sexual Abuse by Foster Mother (<= 5 yrs)"
   S_FMOM612 = "Ind of Sexual Abuse by Foster Mother (6-12 yrs)"
   S_FMOM1316 = "Ind of Sexual Abuse by Foster Mother (13-16 yrs)"
   S_FMOM17 = "Ind of Sexual Abuse by Foster Mother (>= 17 yrs)"
   S_FMOM18 = "Ind of Sexual Abuse by Foster Mother (ever occurred)"
   S_PGF5 = "Ind of Sexual Abuse by Parents Girlfriend (<= 5 yrs)"
   S_PGF612 = "Ind of Sexual Abuse by Parents Girlfriend (6-12 yrs)"
   S_PGF1316 = "Ind of Sexual Abuse by Parents Girlfriend (13-16 yrs)"
   S_PGF17 = "Ind of Sexual Abuse by Parents Girlfriend (>= 17 yrs)"
   S_PGF18 = "Ind of Sexual Abuse by Parents Girlfriend (ever occurred)"
   S_DAD5 = "Ind of Sexual Abuse by Father (<= 5 yrs)"
   S_DAD612 = "Ind of Sexual Abuse by Father (6-12 yrs)"
   S_DAD1316 = "Ind of Sexual Abuse by Father (13-16 yrs)"
   S_DAD17 = "Ind of Sexual Abuse by Father (>= 17 yrs)"
   S_DAD18 = "Ind of Sexual Abuse by Father (ever occurred)"
   S_SDAD5 = "Ind of Sexual Abuse by Step Father (<= 5 yrs)"
   S_SDAD612 = "Ind of Sexual Abuse by Step Father (6-12 yrs)"
   S_SDAD1316 = "Ind of Sexual Abuse by Step Father (13-16 yrs)"
   S_SDAD17 = "Ind of Sexual Abuse by Step Father (>= 17 yrs)"
   S_SDAD18 = "Ind of Sexual Abuse by Step Father (ever occurred)"
   S_FDAD5 = "Ind of Sexual Abuse by Foster Father (<= 5 yrs)"
   S_FDAD612 = "Ind of Sexual Abuse by Foster Father (6-12 yrs)"
   S_FDAD1316 = "Ind of Sexual Abuse by Foster Father (13-16 yrs)"
   S_FDAD17 = "Ind of Sexual Abuse by Foster Father (>= 17 yrs)"
   S_FDAD18 = "Ind of Sexual Abuse by Foster Father (ever occurred)"
   S_PBF5 = "Ind of Sexual Abuse by Parents Boyfriend (<= 5 yrs)"
   S_PBF612 = "Ind of Sexual Abuse by Parents Boyfriend (6-12 yrs)"
   S_PBF1316 = "Ind of Sexual Abuse by Parents Boyfriend (13-16 yrs)"
   S_PBF17 = "Ind of Sexual Abuse by Parents Boyfriend (>= 17 yrs)"
   S_PBF18 = "Ind of Sexual Abuse by Parents Boyfriend (ever occurred)"
   S_OFAM5 = "Ind of Sexual Abuse by Other Family (<= 5 yrs)"
   S_OFAM612 = "Ind of Sexual Abuse by Other Family (6-12 yrs)"
   S_OFAM1316 = "Ind of Sexual Abuse by Other Family (13-16 yrs)"
   S_OFAM17 = "Ind of Sexual Abuse by Other Family (>= 17 yrs)"
   S_OFAM18 = "Ind of Sexual Abuse by Other Family (ever occurred)"
   S_TEA5 = "Ind of Sexual Abuse by Teacher, Coach, etc. (<= 5 yrs)"
   S_TEA612 = "Ind of Sexual Abuse by Teacher, Coach, etc. (6-12 yrs)"
   S_TEA1316 = "Ind of Sexual Abuse by Teacher, Coach, etc. (13-16 yrs)"
   S_TEA17 = "Ind of Sexual Abuse by Teacher, Coach, etc. (>= 17 yrs)"
   S_TEA18 = "Ind of Sexual Abuse by Teacher, Coach, etc. (ever occurred)"
   S_SE5 = "Ind of Sexual Abuse by Someone Else (<= 5 yrs)"
   S_SE612 = "Ind of Sexual Abuse by Someone Else (6-12 yrs)"
   S_SE1316 = "Ind of Sexual Abuse by Someone Else (13-16 yrs)"
   S_SE17 = "Ind of Sexual Abuse by Someone Else (>= 17 yrs)"
   S_SE18 = "Ind of Sexual Abuse by Someone Else (ever occurred)"
   S_FAMILY5 = "Ind of Sexual Abuse by Family Member (<= 5 yrs)"
   S_FAMILY612 = "Ind of Sexual Abuse by Family Member (6-12 yrs)"
   S_FAMILY1316 = "Ind of Sexual Abuse by Family Member (13-16 yrs)"
   S_FAMILY17 = "Ind of Sexual Abuse by Family Member (>= 17 yrs)"
   S_FAMILY18 = "Ind of Sexual Abuse by Family Member (ever occurred)"
   S_NFAM5 = "Ind of Sexual Abuse by Non-Family (<= 5 yrs)"
   S_NFAM612 = "Ind of Sexual Abuse by Non-Family (6-12 yrs)"
   S_NFAM1316 = "Ind of Sexual Abuse by Non-Family (13-16 yrs)"
   S_NFAM17 = "Ind of Sexual Abuse by Non-Family (>= 17 yrs)"
   S_NFAM18 = "Ind of Sexual Abuse by Non-Family (ever occurred)"
   S_IMP_MAX18 = "Sexual Abuse Maximum Impact Score"
   S_IMP_MN18 = "Sexual Abuse Mean Impact Score"
   S_ATT_MAX18 = "Sexual Abuse Maximum Attribution Score"
   S_ATT_MN18 = "Sexual Abuse Mean Attribution Score" ;

LENGTH
   VISIT 3                  NCON18_S 3               NCON18_I 3            
   NPEN18_S 3               NPEN18_I 3               PEN18_S 3             
   PEN18_I 3                SEXABU18_S 3             SEXABU18_I 3          
   SEX_5_S 3                SEX_5_I 3                SEX_612_S 3           
   SEX_612_I 3              SEX_1316_S 3             SEX_1316_I 3          
   SEX_17_S 3               SEX_17_I 3               SEX_5_F 3             
   SEX_612_F 3              SEX_1316_F 3             SEX_17_F 3            
   SEX_F18 3                S_MOM5 3                 S_MOM612 3            
   S_MOM1316 3              S_MOM17 3                S_MOM18 3             
   S_SMOM5 3                S_SMOM612 3              S_SMOM1316 3          
   S_SMOM17 3               S_SMOM18 3               S_FMOM5 3             
   S_FMOM612 3              S_FMOM1316 3             S_FMOM17 3            
   S_FMOM18 3               S_PGF5 3                 S_PGF612 3            
   S_PGF1316 3              S_PGF17 3                S_PGF18 3             
   S_DAD5 3                 S_DAD612 3               S_DAD1316 3           
   S_DAD17 3                S_DAD18 3                S_SDAD5 3             
   S_SDAD612 3              S_SDAD1316 3             S_SDAD17 3            
   S_SDAD18 3               S_FDAD5 3                S_FDAD612 3           
   S_FDAD1316 3             S_FDAD17 3               S_FDAD18 3            
   S_PBF5 3                 S_PBF612 3               S_PBF1316 3           
   S_PBF17 3                S_PBF18 3                S_OFAM5 3             
   S_OFAM612 3              S_OFAM1316 3             S_OFAM17 3            
   S_OFAM18 3               S_TEA5 3                 S_TEA612 3            
   S_TEA1316 3              S_TEA17 3                S_TEA18 3             
   S_SE5 3                  S_SE612 3                S_SE1316 3            
   S_SE17 3                 S_SE18 3                 S_FAMILY5 3           
   S_FAMILY612 3            S_FAMILY1316 3           S_FAMILY17 3          
   S_FAMILY18 3             S_NFAM5 3                S_NFAM612 3           
   S_NFAM1316 3             S_NFAM17 3               S_NFAM18 3            
   S_IMP_MAX18 3            S_ATT_MAX18 3 ;

   

RUN ;
