/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sczb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sczb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=2567;
INPUT
   CENTER $ 1-2             ID $ 3-9                 SCZB1F $ 10-48        
   SCZB2C $ 49-87           SCZB2D $ 88-126          SCZB2E $ 127-165      
   SCZB5A $ 166-204         SCZB5D $ 205             SCZB5G $ 206          
   SCZB5J $ 207             SCZB6B $ 208             SCZB7A $ 209-217      
   SCZB8A $ 218             SCZB9F $ 219-238         SCZB9G $ 239-277      
   SCZB9H $ 278-316         SCZB10D $ 317-355        SCZB10F $ 356-375     
   SCZB10G $ 376-414        SCZB10H $ 415-453        SCZB11D $ 454-492     
   SCZB11E $ 493            SCZB11F $ 494-513        SCZB11G $ 514-551     
   SCZB11H $ 552-590        SCZB12D $ 591-629        SCZB12F $ 630-640     
   SCZB12G $ 641-665        SCZB13A $ 666            SCZB13D $ 667-705     
   SCZB13F $ 706-733        SCZB13G $ 734-772        SCZB13H $ 773-796     
   SCZB13I $ 797-835        SCZB14D $ 836-874        SCZB14F $ 875-879     
   SCZB14G $ 880-901        SCZB14H $ 902-940        SCZB15D $ 941-979     
   SCZB15F $ 980-1004       SCZB15G $ 1005-1042      SCZB15H $ 1043-1081   
   SCZB16E $ 1082-1120      SCZBX20 $ 1121           SCZB16G $ 1122-1137   
   SCZB16H $ 1138-1176      SCZB16I $ 1177-1215      SCZBX21 $ 1216        
   SCZB17D $ 1217-1255      SCZB17F $ 1256-1270      SCZB17G $ 1271-1309   
   SCZB18D $ 1310-1348      SCZB18F $ 1349-1368      SCZB18G $ 1369-1407   
   SCZB18H $ 1408-1437      SCZB18I $ 1438-1476      SCZB19D $ 1477        
   SCZB19F $ 1478           SCZB19G $ 1479           SCZB19H $ 1480        
   SCZB19I $ 1481           SCZB20F $ 1482-1488      SCZB20G $ 1489-1527   
   SCZB20H $ 1528-1565      SCZB20I $ 1566           SCZB21D $ 1567-1605   
   SCZB21F $ 1606           SCZB21G $ 1607           SCZB21H $ 1608        
   SCZB22D $ 1609-1647      SCZB22E $ 1648           SCZB22F $ 1649-1686   
   SCZB22G $ 1687-1724      SCZB22H $ 1725-1762      SCZB24A $ 1763-1801   
   VISIT  1802-1803         SCZB1  1804              SCZB2  1805           
   SCZB3  1806              SCZB4  1807              SCZB5  1808           
   SCZB6  1809              SCZB7  1810              SCZB8  1811           
   SCZB9  1812              SCZB10  1813             SCZB11  1814          
   SCZB12  1815             SCZB13  1816             SCZB14  1817          
   SCZB15  1818             SCZB16  1819             SCZB17  1820          
   SCZB18  1821             SCZB19  1822             SCZB20  1823          
   SCZB21  1824             SCZB22  1825             SCZB23  1826          
   SCZB24  1827             SCZB10A  1828            SCZB10E  1829         
   SCZB10I  1830            SCZB11A  1831            SCZB11I  1832         
   SCZB12A  1833            SCZB12E  1834            SCZB12H  1835         
   SCZB13E  1836            SCZB13J  1837            SCZB14A  1838         
   SCZB14E  1839            SCZB14I  1840            SCZB15A  1841         
   SCZB15E  1842            SCZB15I  1843            SCZB16A  1844         
   SCZB16B  1845            SCZB16F  1846            SCZB16J  1847         
   SCZB17A  1848            SCZB17E  1849            SCZB17H  1850         
   SCZB18A  1851            SCZB18E  1852            SCZB18J  1853         
   SCZB19A  1854            SCZB19E  1855            SCZB19J  1856         
   SCZB1A  1857             SCZB1C  1858             SCZB1D  1859          
   SCZB1E  1860             SCZB1G  1861             SCZB20A  1862         
   SCZB20E  1863            SCZB21A  1864            SCZB21E  1865         
   SCZB21I  1866            SCZB22A  1867            SCZB22I  1868         
   SCZB23A  1869            SCZB23B  1870-1871       SCZB23C  1872         
   SCZB24B  1873            SCZB24C  1874            SCZB24D  1875         
   SCZB24E  1876            SCZB2A  1877             SCZB2F  1878          
   SCZB3A  1879             SCZB3B  1880             SCZB3C  1881          
   SCZB3D  1882             SCZB3E  1883             SCZB3F  1884          
   SCZB3G  1885             SCZB4A  1886             SCZB4B  1887          
   SCZB4C  1888             SCZB5B  1889             SCZB5C  1890          
   SCZB5E  1891             SCZB5F  1892             SCZB5H  1893          
   SCZB5I  1894             SCZB5K  1895             SCZB6A  1896          
   SCZB6C  1897             SCZB7B  1898             SCZB8B  1899          
   SCZB9A  1900             SCZB9D  1901             SCZB9E  1902          
   SCZB9I  1903             SCZBX1  1904             SCZBX2  1905          
   SCZBX3  1906             SCZBX4  1907             SCZBX5  1908          
   SCZBX6  1909             SCZBX7  1910             SCZBX8  1911          
   SCZBX9  1912             SCZBX10  1913            SCZBX11  1914         
   SCZBX12  1915            SCZBX13  1916            SCZBX14  1917         
   SCZBX15  1918            SCZBX16  1919            SCZBX17  1920         
   SCZBX18  1921            SCZBX19  1922            SCZBX22  1923         
   SCZBX23  1924            SCZBX24  1925            SCZBX25  1926         
   SCZBX26  1927            SCZBX27  1928            SCZBX28  1929         
   SCZBX29  1930            SCZBX30  1931            SCZBX31  1932         
   SCZBX32  1933            SCZBX33  1934            SCZBX34  1935         
   SCZBX34A  1936           SCZB24G $ 1937           SCZB24J $ 1938        
   SCZB25B $ 1939-1958      SCZB26A $ 1959-1971      SCZB27A $ 1972        
   SCZB28D $ 1973-2011      SCZB28E $ 2012           SCZB28F $ 2013-2051   
   SCZB28G $ 2052-2090      SCZB29D $ 2091-2129      SCZB29E $ 2130-2168   
   SCZB29F $ 2169-2207      SCZB30D $ 2208-2246      SCZB30E $ 2247-2285   
   SCZB30F $ 2286-2324      SCZB31B $ 2325-2363      SCZB31C $ 2364        
   SCZB34A $ 2365-2403      SCZB34D $ 2404           SCZB34G $ 2405        
   SCZB34J $ 2406           SCZB35B $ 2407-2426      SCZB36A $ 2427-2437   
   SCZB37A $ 2438           SCZB38 $ 2439-2440       SCZB39 $ 2441-2442    
   SCZB55A $ 2443-2481      SCZB25  2482             SCZB26  2483          
   SCZB27  2484             SCZB28  2485             SCZB29  2486          
   SCZB30  2487             SCZB31  2488             SCZB32  2489          
   SCZB33  2490             SCZB34  2491             SCZB35  2492          
   SCZB36  2493             SCZB37  2494             SCZB40  2495-2496     
   SCZB41  2497             SCZB42  2498             SCZB43  2499          
   SCZB44  2500             SCZB45  2501             SCZB46  2502          
   SCZB47  2503             SCZB48  2504             SCZB49  2505          
   SCZB50  2506             SCZB51  2507             SCZB52  2508          
   SCZB53  2509             SCZB54  2510             SCZB24F  2511         
   SCZB24H  2512            SCZB24I  2513            SCZB24K  2514         
   SCZB25A  2515            SCZB25C  2516            SCZB26B  2517         
   SCZB27B  2518            SCZB28A  2519            SCZB28H  2520         
   SCZB29A  2521            SCZB29G  2522            SCZB30A  2523         
   SCZB30G  2524            SCZB32A  2525            SCZB32C  2526         
   SCZB32D  2527            SCZB33A  2528            SCZB33B  2529         
   SCZB33C  2530            SCZB34B  2531            SCZB34C  2532         
   SCZB34E  2533            SCZB34F  2534            SCZB34H  2535         
   SCZB34I  2536            SCZB35A  2537            SCZB35C  2538         
   SCZB36B  2539            SCZB37B  2540            SCZB38A  2541         
   SCZB38B  2542            SCZB38C  2543            SCZB38D  2544-2545    
   SCZB38DGR  2546          SCZB38GR  2547           SCZB42A  2548         
   SCZB48A  2549            SCZB49A  2550            SCZB50A  2551         
   SCZB52A  2552            SCZB52AYA  2553          SCZB53A  2554         
   SCZB54A  2555-2556       SCZBX35  2557            SCZBX36  2558         
   SCZBX37  2559            SCZBX38  2560            SCZBX39  2561         
   SCZBX40  2562            SCZBX41  2563            SCZB34K  2564         
   SCZB38E  2565            SCZB51A  2566            SCZB52YA  2567        
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   SCZB1F = "Last vision:what did you see"
   SCZB2C = "Last heard things:what happened"
   SCZB2D = "How do you explain hearing things"
   SCZB2E = "What did it mean"
   SCZB5A = "What was the diagnosis"
   SCZB5D = "What meds were you taking"
   SCZB5G = "What were you taking"
   SCZB5J = "What was wrong with you"
   SCZB6B = "What medication were you taking"
   SCZB7A = "What were you taking"
   SCZB8A = "What was wrong with you"
   SCZB9F = "Who did you belie was spying"
   SCZB9G = "How did you know u were being spied on"
   SCZB9H = "Why were you being spied on"
   SCZB10D = "Last time people talk abt u-what happend"
   SCZB10F = "What made u think was talking abt u"
   SCZB10G = "What made u think they were discussing"
   SCZB10H = "What was reason u were being talked abt"
   SCZB11D = "Last plotting thought-what happened"
   SCZB11E = "How sure were you about plotting thought"
   SCZB11F = "Last yr:believe someone plotting agnst u"
   SCZB11G = "How did you someone was plotting against u"
   SCZB11H = "Reason that u were being plotted against"
   SCZB12D = "Last thoughts put in mind-what happened"
   SCZB12F = "Tell about a time this happened"
   SCZB12G = "Why strange thoughts being put in mind"
   SCZB13A = "Did that happen to you several times"
   SCZB13D = "Last special message sent-what happened"
   SCZB13F = "Tell about a time this happened"
   SCZB13G = "Why strange thoughts being put in mind"
   SCZB13H = "How do you know it was just for you"
   SCZB13I = "Why do you think messages were sent"
   SCZB14D = "Last time under control-what happened"
   SCZB14F = "Who/what power/force controlled you"
   SCZB14G = "How do you know it was just for you"
   SCZB14H = "Why was force controlling you"
   SCZB15D = "Last time felt force-what happened"
   SCZB15F = "What kind of force was it"
   SCZB15G = "How do you strange force was working"
   SCZB15H = "Reason strange force was working"
   SCZB16E = "Last mind read-what happened"
   SCZBX20 = "Is experience/belief normal"
   SCZB16G = "Who was reading your mind"
   SCZB16H = "How did u know they were reading mind"
   SCZB16I = "Reason someone was reading your mind"
   SCZBX21 = "Is experience/belief normal"
   SCZB17D = "Last time thinking-what happened"
   SCZB17F = "Whose thoughts did you hear"
   SCZB17G = "How was it possible to hear thinking"
   SCZB18D = "Last time othr hear thoght-what happened"
   SCZB18F = "Who could hear what you were thinking"
   SCZB18G = "How did they do that"
   SCZB18H = "How do you know othrs hear your thoughts"
   SCZB18I = "Reason others hear your thoughts"
   SCZB19D = "Last time steal your thght-what happened"
   SCZB19F = "What/who did you think steal yr thought"
   SCZB19G = "How were your thoughts stolen"
   SCZB19H = "How u know someone could steal yr thght"
   SCZB19I = "Why were your thoughts stolen"
   SCZB20F = "Who was following you"
   SCZB20G = "How did you know people following you"
   SCZB20H = "Reason people were following you"
   SCZB20I = "Last 4 wks:believed people following u"
   SCZB21D = "Last time tested secretly-what happened"
   SCZB21F = "Who was testing you"
   SCZB21G = "How did you know you were being tested"
   SCZB21H = "Reason you were being tested"
   SCZB22D = "Last time tested secretly-what happened"
   SCZB22E = "How sure you being secretly tested"
   SCZB22F = "Who was testing you"
   SCZB22G = "How did you know you were being tested"
   SCZB22H = "Reason you were being tested"
   SCZB24A = "What Dr. say was causing you to beleive"
   VISIT = "VISIT NUMBER"
   SCZB1 = "Last yr:ever had vision when awake"
   SCZB2 = "Last yr:heard things"
   SCZB3 = "Last yr:hear voices"
   SCZB4 = "Last yr: did[event]happen for a mth"
   SCZB5 = "Last yr:tell Dr. about experiences"
   SCZB6 = "When u saw/heard things were you on meds"
   SCZB7 = "When u saw/heard thngs- on drgs/alochol"
   SCZB8 = "When u saw/heard th-ings-you phys.sick"
   SCZB9 = "Last yr:believed people were spying on u"
   SCZB10 = "Last yr:thght people were talking abt u"
   SCZB11 = "Last yr:believe someone plotting agnst u"
   SCZB12 = "Last yr:convinced thoughts put in mind"
   SCZB13 = "Last yr:believed special messages sent"
   SCZB14 = "Last yr:convinced you were under control"
   SCZB15 = "Last yr:felt strange force wrking on you"
   SCZB16 = "Last yr:believed someone reading mind"
   SCZB17 = "Last yr:belived you hear person thinking"
   SCZB18 = "Last yr:belived othrs hear your thoughts"
   SCZB19 = "Last yr:convinced someone steal thghts"
   SCZB20 = "Last yr:believed people following you"
   SCZB21 = "Last yr:believed u were being tested"
   SCZB22 = "Last yr:felt book etc was meant for you"
   SCZB23 = "Did you believe [named] things for a mth"
   SCZB24 = "Last yr:tell doctor about beliefs"
   SCZB10A = "Did that happen several times"
   SCZB10E = "How sure were you talking was happening"
   SCZB10I = "Last 4wks:believed people talked abt u"
   SCZB11A = "Did plotting thought last for > 1 wk"
   SCZB11I = "Last 4wks:believed someone plot aganst u"
   SCZB12A = "Did that happen to you several times"
   SCZB12E = "How sure thghts put in mind was happning"
   SCZB12H = "Last 4wks:convinced thoughts put in mind"
   SCZB13E = "How sure special message was happning"
   SCZB13J = "Last 4wks:believed special messages sent"
   SCZB14A = "Did being under control last > 1 week"
   SCZB14E = "How sure you were being under control"
   SCZB14I = "Last 4wks:felt under control of force"
   SCZB15A = "Did that happen to you > once"
   SCZB15E = "How sure you felt strange force working"
   SCZB15I = "Last 4wks:felt stnage forcees working"
   SCZB16A = "Last yr:believ someone actualy read mind"
   SCZB16B = "Thought > once someone could read mind"
   SCZB16F = "How sure were u that this was happening"
   SCZB16J = "Last 4wks:believed someone reading mind"
   SCZB17A = "Has this happened > once"
   SCZB17E = "How sure you could hear thinking"
   SCZB17H = "Last 4 wks:believed hear othrs thinking"
   SCZB18A = "Has this happened > once"
   SCZB18E = "How sure othrs hear your thoughts"
   SCZB18J = "Last 4 wks:believed othrs hear yr thghts"
   SCZB19A = "Did this happen > once a week"
   SCZB19E = "How sure you othr steal yr thought"
   SCZB19J = "Last 4 wks:convincd smone steal yr thght"
   SCZB1A = "Had visions > once last year"
   SCZB1C = "Someone also see the vision"
   SCZB1D = "Falling asleep when saw vision"
   SCZB1E = "Had vision when completely awake"
   SCZB1G = "Last 4wks:since event-had visions"
   SCZB20A = "Did this several times"
   SCZB20E = "How sure you people follow you"
   SCZB21A = "Did this happen > once"
   SCZB21E = "How sure you being secretly tested"
   SCZB21I = "Last 4 wks:believed u were being tested"
   SCZB22A = "Did this happen > once"
   SCZB22I = "Last 4 wks:believed u were being tested"
   SCZB23A = "Tell anybody you believed these things"
   SCZB23B = "Anyone take you to see a doctor"
   SCZB23C = "Doctor give you meds for nerves"
   SCZB24B = "Dr. say you had a problem with nerves"
   SCZB24C = "Did Dr. say meds caused these things"
   SCZB24D = "What medication were you taking"
   SCZB24E = "Believe these things when not on meds"
   SCZB2A = "Last yr:heard things > once"
   SCZB2F = "Last 4wks:since event-heard things"
   SCZB3A = "Did voice come from your body"
   SCZB3B = "Hear voice commenting on you"
   SCZB3C = "Ever hear 2/>2 voices"
   SCZB3D = "Were voices discussing you"
   SCZB3E = "Ever carry 2way conversation with voices"
   SCZB3F = "Ever see who you were talking to"
   SCZB3G = "Last 4wks:since event-heard voices"
   SCZB4A = "Did you tell anybody you had experiences"
   SCZB4B = "Did anyone take you to see a doctor"
   SCZB4C = "Did doctor give you any meds"
   SCZB5B = "Did Dr say you had prblm with nerves"
   SCZB5C = "Did Dr. say meds caused this"
   SCZB5E = "Ever see/hear things when not on meds"
   SCZB5F = "Did Dr. say drugs/alcohol caused this"
   SCZB5H = "Ever see/hear thngs whn no drugs/alcohol"
   SCZB5I = "Did Dr. say things caused by phys.sick"
   SCZB5K = "Ever see/hear things when not phys.sick"
   SCZB6A = "Did Dr give meds because of these things"
   SCZB6C = "See/hear things when not on this meds"
   SCZB7B = "See/hear things when not on drgs/alochol"
   SCZB8B = "See/hear things when not phys.sick"
   SCZB9A = "Did that happen several times"
   SCZB9D = "Last spying-what happened"
   SCZB9E = "How sure were you spying was happening"
   SCZB9I = "Last 4wks:since event-people were spying"
   SCZBX1 = "Us respondent experince normal"
   SCZBX2 = "Is experience described normal"
   SCZBX3 = "Is experience described normal"
   SCZBX4 = "Informant describe hearing voice"
   SCZBX5 = "Is experience/belief normal"
   SCZBX6 = "Is experience/belief normal"
   SCZBX7 = "Is experience/belief normal"
   SCZBX8 = "Is experience/belief normal"
   SCZBX9 = "Is experience/belief normal"
   SCZBX10 = "Is experience/belief normal"
   SCZBX11 = "Is experience/belief normal"
   SCZBX12 = "Is experience/belief normal"
   SCZBX13 = "Is experience/belief normal"
   SCZBX14 = "INV response"
   SCZBX15 = "Is experience/belief normal"
   SCZBX16 = "Is experience/belief normal"
   SCZBX17 = "Was response coded in Q1-14"
   SCZBX18 = "Is experience/belief normal"
   SCZBX19 = "Is experience/belief normal"
   SCZBX22 = "Is experience/belief normal"
   SCZBX23 = "Is experience/belief normal"
   SCZBX24 = "Is experience/belief normal"
   SCZBX25 = "Is experience/belief normal"
   SCZBX26 = "Is experience/belief normal"
   SCZBX27 = "Is experience/belief normal"
   SCZBX28 = "Is experience/belief normal"
   SCZBX29 = "Is experience/belief normal"
   SCZBX30 = "Is experience/belief normal"
   SCZBX31 = "Is experience/belief normal"
   SCZBX32 = "Is experience/belief normal"
   SCZBX33 = "Is experience/belief normal"
   SCZBX34 = "Is experience/belief normal"
   SCZBX34A = "Record delusionsINV response"
   SCZB24G = "What were you taking"
   SCZB24J = "What was wrong with you"
   SCZB25B = "What were you taking"
   SCZB26A = "What were you taking"
   SCZB27A = "What was wrong with you"
   SCZB28D = "Last strange smell- what happened"
   SCZB28E = "Somebody could also smell odors"
   SCZB28F = "Where did odors come from"
   SCZB28G = "How do you explain smelling things"
   SCZB29D = "Last strange taste- what happened"
   SCZB29E = "Where did taste come from"
   SCZB29F = "How do you explain strange tastes"
   SCZB30D = "Last unusual feeling- what happened"
   SCZB30E = "How do you explain strange feelings"
   SCZB30F = "What did they mean"
   SCZB31B = "Why couldn't you move"
   SCZB31C = "Last 4wks: unable to move"
   SCZB34A = "What Dr. say was causing smell etc"
   SCZB34D = "What medication were you taking"
   SCZB34G = "What were you taking"
   SCZB34J = "What was wrong with you"
   SCZB35B = "What medication were you taking"
   SCZB36A = "What were you taking"
   SCZB37A = "What was wrong with you"
   SCZB38 = "Age first experience began"
   SCZB39 = "Last time you had beliefs/experiences"
   SCZB55A = "What person you saw say the matter was"
   SCZB25 = "When believed things were you on meds"
   SCZB26 = "Believed thngs were you on drugs/alcohol"
   SCZB27 = "When believed things were u phys sick"
   SCZB28 = "Last yr:bothered by strange smells"
   SCZB29 = "Last yr:had strange tastes"
   SCZB30 = "Last yr:had unusual feelings"
   SCZB31 = "Last yr: unable to move at all"
   SCZB32 = "Last yr:moved constantly"
   SCZB33 = "These [name] things happen for a mth"
   SCZB34 = "Tell a doctor about these experiences"
   SCZB35 = "When you smelled etc were you on med"
   SCZB36 = "Smelled etc. when taking drugs/alcohol"
   SCZB37 = "When smelled ect were you phys sick"
   SCZB40 = "How much time went that you had beliefs"
   SCZB41 = "Beliefs/exper.present most of the time"
   SCZB42 = "At that time were you not normal self"
   SCZB43 = "Which spells [sad etc] came first"
   SCZB44 = "Spells [sad etc] present time as beliefs"
   SCZB45 = "Were the present same time for 2wks"
   SCZB46 = "Have beliefs for >2wks when not sad etc"
   SCZB47 = "Which lasted longer: beliefs or sad etc"
   SCZB48 = "Because of beliefs:family/friends upset"
   SCZB49 = "Beliefs keep you from doing things"
   SCZB50 = "Belief keep you frm doing thngs wth othr"
   SCZB51 = "Problems worst:difficult to do schl/work"
   SCZB52 = "Experiences cause teacher/boss upset"
   SCZB53 = "Problems worst:make you feel upset"
   SCZB54 = "Seen someone in hospital in last year"
   SCZB24F = "Dr. say drgs/alcohol caused these things"
   SCZB24H = "Believe thngs when not on drugs/alcohol"
   SCZB24I = "Dr. say u believd thngs 'cause phys sick"
   SCZB24K = "Have strange beliefs when u weren't sick"
   SCZB25A = "Dr. give meds 'cause u believed things"
   SCZB25C = "Believed things when u weren't on meds"
   SCZB26B = "Believe thngs when not on drugs/alcohol"
   SCZB27B = "Have these beliefs when u weren't sick"
   SCZB28A = "Has this happened > once in last yr"
   SCZB28H = "Last 4wks:bothered by strange smells"
   SCZB29A = "Has this happened > once a year"
   SCZB29G = "Last 4wks:had strange tastes"
   SCZB30A = "Has this happened > once in last yr"
   SCZB30G = "Last 4 wks:had unusual feelings"
   SCZB32A = "Has this happened >once in last year"
   SCZB32C = "Why couldn't you stop moving"
   SCZB32D = "Last 4wks:moved constantly"
   SCZB33A = "Tell anybody you had these experiences"
   SCZB33B = "Anyone take you to see a doctor"
   SCZB33C = "Did Dr.give you meds for nerves"
   SCZB34B = "Dr. say you had a problem with nerves"
   SCZB34C = "Dr. say this was because of meds"
   SCZB34E = "Smell etc when you weren't on this med"
   SCZB34F = "Dr. say smell etc 'cause of drugs/drink"
   SCZB34H = "Smell etc when u weren't takng drgs/drnk"
   SCZB34I = "Dr. say smell etc 'cause phys sick"
   SCZB35A = "Dr. give u this med 'cause u smelled etc"
   SCZB35C = "Smelled etc. when u weren't taking med"
   SCZB36B = "Smelled etc -u weren't takng drgs/alcohl"
   SCZB37B = "Smelled etc when u weren't sick"
   SCZB38A = "Was 1st time > a yr ago"
   SCZB38B = "Since 1st time ever not had experience"
   SCZB38C = "Did no experience time last 2/2 mths"
   SCZB38D = "Last yr: age when experience began"
   SCZB38DGR = "Last yr: grade when experience began"
   SCZB38GR = "Grade 1st time had these experiences"
   SCZB42A = "Did period-not normal self- last > 6mths"
   SCZB48A = "How often family/friends upset"
   SCZB49A = "How oftn belief keep you frm doing thngs"
   SCZB50A = "How oftn belief keep u frm thng wth othr"
   SCZB52A = "How often teacher/boss upset"
   SCZB52AYA = "Problems worst:hard to do selfcare"
   SCZB53A = "How bad problems make you feel upset"
   SCZB54A = "Have appointment re:beliefs/expernces"
   SCZBX35 = "Is experience/belief normal"
   SCZBX36 = "Is experience/belief normal"
   SCZBX37 = "Is experience/belief normal"
   SCZBX38 = "Is experience/belief normal"
   SCZBX39 = "Is experience/belief normal"
   SCZBX40 = "Is experience/belief normal"
   SCZBX41 = "Is experience/belief normal"
   SCZB34K = "Ever smell/taste these thngs/not sick"
   SCZB38E = "Beliefs/exp. started again >1 yr ago"
   SCZB51A = "How bad problems were"
   SCZB52YA = "When problms worst-selfcare hard" ;

LENGTH
   VISIT 3                  SCZB1 3                  SCZB2 3               
   SCZB3 3                  SCZB4 3                  SCZB5 3               
   SCZB6 3                  SCZB7 3                  SCZB8 3               
   SCZB9 3                  SCZB10 3                 SCZB11 3              
   SCZB12 3                 SCZB13 3                 SCZB14 3              
   SCZB15 3                 SCZB16 3                 SCZB17 3              
   SCZB18 3                 SCZB19 3                 SCZB20 3              
   SCZB21 3                 SCZB22 3                 SCZB23 3              
   SCZB24 3                 SCZB10A 3                SCZB10E 3             
   SCZB10I 3                SCZB11A 3                SCZB11I 3             
   SCZB12A 3                SCZB12E 3                SCZB12H 3             
   SCZB13E 3                SCZB13J 3                SCZB14A 3             
   SCZB14E 3                SCZB14I 3                SCZB15A 3             
   SCZB15E 3                SCZB15I 3                SCZB16A 3             
   SCZB16B 3                SCZB16F 3                SCZB16J 3             
   SCZB17A 3                SCZB17E 3                SCZB17H 3             
   SCZB18A 3                SCZB18E 3                SCZB18J 3             
   SCZB19A 3                SCZB19E 3                SCZB19J 3             
   SCZB1A 3                 SCZB1C 3                 SCZB1D 3              
   SCZB1E 3                 SCZB1G 3                 SCZB20A 3             
   SCZB20E 3                SCZB21A 3                SCZB21E 3             
   SCZB21I 3                SCZB22A 3                SCZB22I 3             
   SCZB23A 3                SCZB23B 3                SCZB23C 3             
   SCZB24B 3                SCZB24C 3                SCZB24D 3             
   SCZB24E 3                SCZB2A 3                 SCZB2F 3              
   SCZB3A 3                 SCZB3B 3                 SCZB3C 3              
   SCZB3D 3                 SCZB3E 3                 SCZB3F 3              
   SCZB3G 3                 SCZB4A 3                 SCZB4B 3              
   SCZB4C 3                 SCZB5B 3                 SCZB5C 3              
   SCZB5E 3                 SCZB5F 3                 SCZB5H 3              
   SCZB5I 3                 SCZB5K 3                 SCZB6A 3              
   SCZB6C 3                 SCZB7B 3                 SCZB8B 3              
   SCZB9A 3                 SCZB9D 3                 SCZB9E 3              
   SCZB9I 3                 SCZBX1 3                 SCZBX2 3              
   SCZBX3 3                 SCZBX4 3                 SCZBX5 3              
   SCZBX6 3                 SCZBX7 3                 SCZBX8 3              
   SCZBX9 3                 SCZBX10 3                SCZBX11 3             
   SCZBX12 3                SCZBX13 3                SCZBX14 3             
   SCZBX15 3                SCZBX16 3                SCZBX17 3             
   SCZBX18 3                SCZBX19 3                SCZBX22 3             
   SCZBX23 3                SCZBX24 3                SCZBX25 3             
   SCZBX26 3                SCZBX27 3                SCZBX28 3             
   SCZBX29 3                SCZBX30 3                SCZBX31 3             
   SCZBX32 3                SCZBX33 3                SCZBX34 3             
   SCZBX34A 3               SCZB25 3                 SCZB26 3              
   SCZB27 3                 SCZB28 3                 SCZB29 3              
   SCZB30 3                 SCZB31 3                 SCZB32 3              
   SCZB33 3                 SCZB34 3                 SCZB35 3              
   SCZB36 3                 SCZB37 3                 SCZB40 3              
   SCZB41 3                 SCZB42 3                 SCZB43 3              
   SCZB44 3                 SCZB45 3                 SCZB46 3              
   SCZB47 3                 SCZB48 3                 SCZB49 3              
   SCZB50 3                 SCZB51 3                 SCZB52 3              
   SCZB53 3                 SCZB54 3                 SCZB24F 3             
   SCZB24H 3                SCZB24I 3                SCZB24K 3             
   SCZB25A 3                SCZB25C 3                SCZB26B 3             
   SCZB27B 3                SCZB28A 3                SCZB28H 3             
   SCZB29A 3                SCZB29G 3                SCZB30A 3             
   SCZB30G 3                SCZB32A 3                SCZB32C 3             
   SCZB32D 3                SCZB33A 3                SCZB33B 3             
   SCZB33C 3                SCZB34B 3                SCZB34C 3             
   SCZB34E 3                SCZB34F 3                SCZB34H 3             
   SCZB34I 3                SCZB35A 3                SCZB35C 3             
   SCZB36B 3                SCZB37B 3                SCZB38A 3             
   SCZB38B 3                SCZB38C 3                SCZB38D 3             
   SCZB38DGR 3              SCZB38GR 3               SCZB42A 3             
   SCZB48A 3                SCZB49A 3                SCZB50A 3             
   SCZB52A 3                SCZB52AYA 3              SCZB53A 3             
   SCZB54A 3                SCZBX35 3                SCZBX36 3             
   SCZBX37 3                SCZBX38 3                SCZBX39 3             
   SCZBX40 3                SCZBX41 3                SCZB34K 3             
   SCZB38E 3                SCZB51A 3                SCZB52YA 3 ;

      

RUN ;
