/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sfia0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sfia0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=60;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   sfia1  11                sfia2  12                sfia3  13             
   sfia4  14                sfia5  15                sfia6  16             
   sfia7  17                sfia8  18                sfia9  19             
   sfia10  20               sfia11  21               sfia12  22            
   sfia13  23               sfia14  24               sfia15  25            
   sfia16  26               sfia17  27               sfia18  28            
   sfia19  29               sfia20  30               sfia21  31            
   sfia22  32               sfia23  33               sfia24  34            
   sfia25  35               sfia26  36               sfia27  37            
   sfia28  38               sfia29  39               sfia30  40            
   sfia31  41               sfia32  42               sfia33  43            
   sfia34  44               sfia35  45               sfia36  46            
   sfia37 $ 47-49           sfia38 DATE11.         ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   sfia1 = "members pay attn. others' feelings"
   sfia2 = "rather do things together"
   sfia3 = "all have say in household plans"
   sfia4 = "grwnps understand-agree on decisions"
   sfia5 = "grwnps compete and fight"
   sfia6 = "closeness & individuality among mem."
   sfia7 = "accept each others' friends"
   sfia8 = "confusion because no leader"
   sfia9 = "members touch-hold each other"
   sfia10 = "members put each other down"
   sfia11 = "speak minds no matter what"
   sfia12 = "feel loved in home"
   sfia13 = "members embarrassed to admit closeness"
   sfia14 = "argue and don't solve problems"
   sfia15 = "happiest times at home"
   sfia16 = "grownups are strong leaders"
   sfia17 = "future looks good to household"
   sfia18 = "one person gets blame"
   sfia19 = "members get own way most of time"
   sfia20 = "household proud of closeness"
   sfia21 = "household good at solving problems"
   sfia22 = "members express warmth-caring"
   sfia23 = "okay to fight-yell in household"
   sfia24 = "one of adults has favorite child"
   sfia25 = "blame each other when things wrong"
   sfia26 = "say what think and feel"
   sfia27 = "members prefer other people"
   sfia28 = "members pay attn. to each other"
   sfia29 = "worry about hurting others' feelings"
   sfia30 = "mood in household blue-sad"
   sfia31 = "argue a lot"
   sfia32 = "one person controls-leads household"
   sfia33 = "household mostly happy"
   sfia34 = "each person takes resp. for behavior"
   sfia35 = "rating of household functioning"
   sfia36 = "rating of independence in household"
   sfia37 = "interviewer initials"
   sfia38 = "date of interview" ;

FORMAT
   sfia38 DATE9. ;
     

LENGTH
   visit 3                  sfia1 3                  sfia2 3               
   sfia3 3                  sfia4 3                  sfia5 3               
   sfia6 3                  sfia7 3                  sfia8 3               
   sfia9 3                  sfia10 3                 sfia11 3              
   sfia12 3                 sfia13 3                 sfia14 3              
   sfia15 3                 sfia16 3                 sfia17 3              
   sfia18 3                 sfia19 3                 sfia20 3              
   sfia21 3                 sfia22 3                 sfia23 3              
   sfia24 3                 sfia25 3                 sfia26 3              
   sfia27 3                 sfia28 3                 sfia29 3              
   sfia30 3                 sfia31 3                 sfia32 3              
   sfia33 3                 sfia34 3                 sfia35 3              
   sfia36 3 ;

        

RUN ;
