/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sfrb1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sfrb1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=36;
INPUT
   CENTER $ 1-2             ID $ 3-9                 SFRB12 $ 10-12        
   VISIT  13-14             SFRB1  15                SFRB2  16             
   SFRB3  17                SFRB4  18                SFRB5  19             
   SFRB6  20                SFRB7  21                SFRB8  22             
   SFRB9  23                SFRB10  24               SFRB11  25            
   SFRB13 DATE11.         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   SFRB12 = "Interviewer initials"
   VISIT = "VISIT NUMBER"
   SFRB1 = "Time to talk with child each day"
   SFRB2 = "Things we do each morning"
   SFRB3 = "Child has regular routine after school"
   SFRB4 = "Child sleeps in same place every night"
   SFRB5 = "Child does homework same time each day"
   SFRB6 = "Child has things to ask for at bedtime"
   SFRB7 = "Child goes to bed same time every night"
   SFRB8 = "Family eats dinner same time each night"
   SFRB9 = "Family eats at least one meal together"
   SFRB10 = "Family members check in/out w each other"
   SFRB11 = "Discipline child each time out of line"
   SFRB13 = "Date of interview" ;

FORMAT
   SFRB13 DATE9. ;
     

LENGTH
   VISIT 3                  SFRB1 3                  SFRB2 3               
   SFRB3 3                  SFRB4 3                  SFRB5 3               
   SFRB6 3                  SFRB7 3                  SFRB8 3               
   SFRB9 3                  SFRB10 3                 SFRB11 3 ;

        

RUN ;
