/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sfs0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sfs0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=90;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   sfahea  11-12            sfacon  13-14            sfacoh  15-16         
   sfaexp  17-18            sfalea  19-20            sfahea2  21-34        
   sfacon2  35-48           sfacoh2  49-62           sfaexp2  63-76        
   sfalea2  77-90         ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   sfahea = "sfa: health/competence: total score"
   sfacon = "sfa: conflict: total score"
   sfacoh = "sfa: cohesion: total score"
   sfaexp = "sfa: expressiveness: total score"
   sfalea = "sfa: leadership: total score"
   sfahea2 = "sfa: health/competence: mean score"
   sfacon2 = "sfa: conflict: mean score"
   sfacoh2 = "sfa: cohesion: mean score"
   sfaexp2 = "sfa: expressiveness: mean score"
   sfalea2 = "sfa: leadership: mean score" ;

LENGTH
   visit 3                  sfahea 3                 sfacon 3              
   sfacoh 3                 sfaexp 3                 sfalea 3 ;

        

RUN ;
