/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sib0708.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sib0708 ;

DATA library.&dataset ;
INFILE datafile LRECL=38;
INPUT
   id $ 1-7                 visit  8-9               center $ 10-11        
   sib1  12                 sib2  13                 sib3a  14-16          
   sib3b  17-19             sib3c  20-22             sib3d  23-24          
   sib4 $ 25-27             sib5 DATE11.           ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   sib1 = "extent of parental involvement w school"
   sib2 = "how much parents reinforce educ at home"
   sib3a = "# of days student assigned to your class"
   sib3b = "# of days student absent from your class"
   sib3c = "# of days student tardy"
   sib3d = "# of days student suspended from school"
   sib4 = "interviewer initials"
   sib5 = "date of interview" ;

FORMAT
   sib5 DATE9. ;
       

LENGTH
   visit 3                  sib1 3                   sib2 3                
   sib3a 4                  sib3b 4                  sib3c 4               
   sib3d 3 ;

         

RUN ;
