/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\skia1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = skia1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=31;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   SKIA1  12                SKIA2  13                SKIA3  14             
   SKIA4  15                SKIA5  16                SKIA6  17             
   SKIA7  18                SKIA8  19                SKIA9  20             
   SKIA10  21               SKIA11  22               SKIA12  23            
   SKIA13  24               SKIA14  25               SKIA15  26            
   SKIA16  27               SKIA17  28               SKIA18  29            
   SKIA19  30               SKIA20  31             ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   SKIA1 = "Can arrange for telephone & utilities"
   SKIA2 = "Can complete rental agreement or lease"
   SKIA3 = "Can calculate living arrangments costs"
   SKIA4 = "I get my work done on time"
   SKIA5 = "I get to school/work on time"
   SKIA6 = "I prepare for exams and presentations"
   SKIA7 = "I use the library ect to get information"
   SKIA8 = "I can explain how to prevent preganancy"
   SKIA9 = "I can expalin 2 ways to prevent STDs"
   SKIA10 = "I can explain what happens-if you smoke"
   SKIA11 = "I can explain how I am feeling"
   SKIA12 = "I get help if mt feelings bother me"
   SKIA13 = "I ask for help when I need it"
   SKIA14 = "I use things in the kitchen"
   SKIA15 = "I fix meals for myself on my own"
   SKIA16 = "I store food so it doesn't spoil"
   SKIA17 = "I prevent or minimize roaches, ants, mice, mold, mildew, etc"
   SKIA18 = "I am polite to others"
   SKIA19 = "I show appreciation"
   SKIA20 = "I respect other people's things" ;

LENGTH
   VISIT 3                  SKIA1 3                  SKIA2 3               
   SKIA3 3                  SKIA4 3                  SKIA5 3               
   SKIA6 3                  SKIA7 3                  SKIA8 3               
   SKIA9 3                  SKIA10 3                 SKIA11 3              
   SKIA12 3                 SKIA13 3                 SKIA14 3              
   SKIA15 3                 SKIA16 3                 SKIA17 3              
   SKIA18 3                 SKIA19 3                 SKIA20 3 ;

        

RUN ;
