/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\sops1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = sops1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=41;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   YSO001  12               YSO002  13               YSO003  14            
   YSO004  15               YSO005  16               YSO006  17            
   YSO007  18               YSO008  19               YSO009  20            
   YSO010  21               YSO011  22               YSO012  23            
   YSO013  24               YSO014  25               YSO001A  26           
   YSO003A  27              YSOAY  28                YSOAM  29             
   YSOBY  30                YSOBM  31                YSOCY  32             
   YSOCM  33                YSODY  34                YSODM  35             
   YSOY  36                 YSOM  37                 YSOCRITY  38          
   YSOCRITM  39             YSOSYMP  40-41         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   YSO001 = "Do you have any friends"
   YSO002 = "Have same age relatives like being with"
   YSO003 = "Last yr: afraid with people not know"
   YSO004 = "Last yr: afraid when in a group"
   YSO005 = "Afraid doing things in front of people"
   YSO006 = "Afraid you might embarrass yourself"
   YSO007 = "Last yr: afraid nervousness noticed"
   YSO008 = "Afraid ever time wth people not know"
   YSO009 = "Not tried thngs where nervous wth people"
   YSO010 = "Keep quiet when nervous with people"
   YSO011 = "Usually try to leave as soon as you can"
   YSO012 = "Nervous most times with people not know"
   YSO013 = "More nervous around people thn should be"
   YSO014 = "Last 4 wks:almost always felt nervous"
   YSO001A = "Have you had friends in the last year"
   YSO003A = "Last yr: afraid with same age people"
   YSOAY = "Fear of social or perform situations"
   YSOAM = "Fear of social or perform situations"
   YSOBY = "Exposure to situation provokes anxiety"
   YSOBM = "Exposure to situation provokes anxiety"
   YSOCY = "Recognizes fear excessive or unreasonable"
   YSOCM = "Recognizes fear excessive or unreasonable"
   YSODY = "Situations avoided or endured with anxiety  label"
   YSODM = "Situations avoided or endured with anxiety"
   YSOY = "year: diagnosis for social phobia"
   YSOM = "month: diagnosis for social phobia"
   YSOCRITY = "Youth Social Phobia Criteria Count - Last Year"
   YSOCRITM = "Youth Social Phobia Criteria Count - Last Month"
   YSOSYMP = "Youth Social Phobia - Symptom Count" ;

LENGTH
   VISIT 3                  YSO001 3                 YSO002 3              
   YSO003 3                 YSO004 3                 YSO005 3              
   YSO006 3                 YSO007 3                 YSO008 3              
   YSO009 3                 YSO010 3                 YSO011 3              
   YSO012 3                 YSO013 3                 YSO014 3              
   YSO001A 3                YSO003A 3                YSOAY 3               
   YSOAM 3                  YSOBY 3                  YSOBM 3               
   YSOCY 3                  YSOCM 3                  YSODY 3               
   YSODM 3                  YSOY 3                   YSOM 3                
   YSOCRITY 3               YSOCRITM 3               YSOSYMP 3 ;

       

RUN ;
