/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\spps1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = spps1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=85;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   YSP001A  12              YSP001B  13-17           YSP001C  18           
   YSP001D  19              YSP001E  20              YSP001F  21           
   YSP001G  22              YSP001H  23-25           YSP001I  26           
   YSP001J  27-28           YSP001K  29              YSP001L  30           
   YSP1AY  31               YSP2AY  32               YSP3AY  33            
   YSP4AY  34               YSP1AM  35               YSP2AM  36            
   YSP3AM  37               YSP4AM  38               YSP1BY  39            
   YSP2BY  40               YSP3BY  41               YSP4BY  42            
   YSP1BM  43               YSP2BM  44               YSP3BM  45            
   YSP4BM  46               YSP1CY  47               YSP2CY  48            
   YSP3CY  49               YSP4CY  50               YSP1CM  51            
   YSP2CM  52               YSP3CM  53               YSP4CM  54            
   YSP1DY  55               YSP2DY  56               YSP3DY  57            
   YSP4DY  58               YSP1DM  59               YSP2DM  60            
   YSP3DM  61               YSP4DM  62               YSP1EY  63            
   YSP2EY  64               YSP3EY  65               YSP4EY  66            
   YSP1EM  67               YSP2EM  68               YSP3EM  69            
   YSP4EM  70               YSP1Y  71                YSP2Y  72             
   YSP3Y  73                YSP4Y  74                YSPY  75              
   YSP1M  76                YSP2M  77                YSP3M  78             
   YSP4M  79                YSPM  80                 YSPCRITY  81-82       
   YSPCRITM  83-84          YSPSYMP  85            ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   YSP001A = "Last yr: afraid of insects/animals"
   YSP001B = "Which ones have you been afraid of"
   YSP001C = "Last 4 wks: afraid of being high up"
   YSP001D = "Afraid of thundr & lightning"
   YSP001E = "Afraid of being in the dark"
   YSP001F = "Afraid of water"
   YSP001G = "Afraid of being on a bridge"
   YSP001H = "Which ones have you been afraid of"
   YSP001I = "Afraid of elevator/escalator"
   YSP001J = "Which fear have you been afraid of"
   YSP001K = "More afraid than others re: needle/shots"
   YSP001L = "Sight of blood/cuts made you afraid"
   YSP1AY = "Excessive or unreasonable fear of [(WORST) FEAR]"
   YSP2AY = "Excessive or unreasonable fear of thunder and lightning"
   YSP3AY = "Excessive or unreasonable fear of needles or shots"
   YSP4AY = "Excessive or unreasonable fear of blood or cuts"
   YSP1AM = "Excessive or unreasonable fear of [(WORST) FEAR]"
   YSP2AM = "Excessive or unreasonable fear of thunder and lightning"
   YSP3AM = "Excessive or unreasonable fear of needles or shots"
   YSP4AM = "Excessive or unreasonable fear of blood or cuts"
   YSP1BY = "Exposure to [(WORST) FEAR] provokes anxiety"
   YSP2BY = "Exposure to thunder and lightning provokes anxiety"
   YSP3BY = "Exposure to needles or shots provokes anxiety"
   YSP4BY = "Exposure to blood or cuts provokes anxiety"
   YSP1BM = "Exposure to [(WORST) FEAR] provokes anxiety"
   YSP2BM = "Exposure to thunder and lightning provokes anxiety"
   YSP3BM = "Exposure to needles or shots provokes anxiety"
   YSP4BM = "Exposure to blood or cuts provokes anxiety"
   YSP1CY = "Recognizes fear of [(WORST) FEAR] is excessive"
   YSP2CY = "Recognizes fear of thunder and lightning is excessive"
   YSP3CY = "Recognizes fear of needles or shots is excessive"
   YSP4CY = "Recognizes fear of blood or cuts is excessive"
   YSP1CM = "Recognizes fear of [(WORST) FEAR] is excessive"
   YSP2CM = "Recognizes fear of thunder and lightning is excessive"
   YSP3CM = "Recognizes fear of needles or shots is excessive"
   YSP4CM = "Recognizes fear of blood or cuts is excessive"
   YSP1DY = "[(WORST) FEAR] is avoided or endured with anxiety"
   YSP2DY = "Thunder and lightning is avoided or endured with anxiety"
   YSP3DY = "Needles or shots are avoided or endured with anxiety"
   YSP4DY = "Blood or cuts are avoided or endured with anxiety"
   YSP1DM = "[(WORST) FEAR] is avoided or endured with anxiety"
   YSP2DM = "Thunder and lightning is avoided or endured with anxiety"
   YSP3DM = "Needles or shots are avoided or endured with anxiety"
   YSP4DM = "Blood or cuts are avoided or endured with anxiety"
   YSP1EY = "Fear of [(WORST) FEAR] interferes significantly or marked distress about phobia"
   YSP2EY = "Fear of thunder and lightning interferes significantly or marked distress about phobia"
   YSP3EY = "Fear of needles or shots interferes significantly or marked distress about phobia"
   YSP4EY = "Fear of blood or cuts interferes significantly or marked distress about phobia"
   YSP1EM = "Fear of [(WORST) FEAR] interferes significantly or marked distress about phobia"
   YSP2EM = "Fear of thunder and lightning interferes significantly or marked distress about phobia"
   YSP3EM = "Fear of needles or shots interferes significantly or marked distress about phobia"
   YSP4EM = "Fear of blood or cuts interferes significantly or marked distress about phobia"
   YSP1Y = "Miscellaneous (animals,heights,water,dark,highways,escalators,etc.)"
   YSP2Y = "Thunder and lightning"
   YSP3Y = "Needles or shots"
   YSP4Y = "Blood or cuts"
   YSPY = "Specific Phobia - Last Year"
   YSP1M = "Miscellaneous (animals,heights,water,dark,highways,escalators,etc.)"
   YSP2M = "Thunder and lightning"
   YSP3M = "Needles or shots"
   YSP4M = "Blood or cuts"
   YSPM = "Specific Phobia - Last Month"
   YSPCRITY = "Youth Specific Phobia Criteria Count - Last Year"
   YSPCRITM = "Youth Specific Phobia Criteria Count - Last Month"
   YSPSYMP = "Youth Specific Phobia Symptom Count" ;

LENGTH
   VISIT 3                  YSP001A 3                YSP001B 4             
   YSP001C 3                YSP001D 3                YSP001E 3             
   YSP001F 3                YSP001G 3                YSP001H 4             
   YSP001I 3                YSP001J 3                YSP001K 3             
   YSP001L 3                YSP1AY 3                 YSP2AY 3              
   YSP3AY 3                 YSP4AY 3                 YSP1AM 3              
   YSP2AM 3                 YSP3AM 3                 YSP4AM 3              
   YSP1BY 3                 YSP2BY 3                 YSP3BY 3              
   YSP4BY 3                 YSP1BM 3                 YSP2BM 3              
   YSP3BM 3                 YSP4BM 3                 YSP1CY 3              
   YSP2CY 3                 YSP3CY 3                 YSP4CY 3              
   YSP1CM 3                 YSP2CM 3                 YSP3CM 3              
   YSP4CM 3                 YSP1DY 3                 YSP2DY 3              
   YSP3DY 3                 YSP4DY 3                 YSP1DM 3              
   YSP2DM 3                 YSP3DM 3                 YSP4DM 3              
   YSP1EY 3                 YSP2EY 3                 YSP3EY 3              
   YSP4EY 3                 YSP1EM 3                 YSP2EM 3              
   YSP3EM 3                 YSP4EM 3                 YSP1Y 3               
   YSP2Y 3                  YSP3Y 3                  YSP4Y 3               
   YSPY 3                   YSP1M 3                  YSP2M 3               
   YSP3M 3                  YSP4M 3                  YSPM 3                
   YSPCRITY 3               YSPCRITM 3               YSPSYMP 3 ;

       

RUN ;
