/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\tsa0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = tsa0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=68;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   tsa1  11                 tsa2  12                 tsa3  13              
   tsa4  14                 tsa5  15                 tsa6  16              
   tsa7  17                 tsa8  18                 tsa9  19              
   tsa10  20                tsa11  21                tsa12  22             
   tsa13  23                tsa14  24                tsa15  25             
   tsa16  26                tsa17  27                tsa18  28             
   tsa19  29                tsa20  30                tsa21  31             
   tsa22  32                tsa23  33                tsa24  34             
   tsa25  35                tsa26  36                tsa27  37             
   tsa28  38                tsa29  39                tsa30  40             
   tsa31  41                tsa32  42                tsa33  43             
   tsa34  44                tsa35  45                tsa36  46             
   tsa37  47                tsa38  48                tsa39  49             
   tsa40  50                tsa41  51                tsa42  52             
   tsa43  53                tsa44  54                tsa45 $ 55-57         
   tsa46 DATE11.          ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   tsa1 = "bad dreams or nightmares"
   tsa2 = "feel afraid something bad might happen"
   tsa3 = "scary ideas/pictures pop in your head"
   tsa4 = "pretending you are someone else"
   tsa5 = "arguing too much"
   tsa6 = "feeling lonely"
   tsa7 = "feeling sad or unhappy"
   tsa8 = "remembering past events you didn^t like"
   tsa9 = "going away in your mind/try not to think"
   tsa10 = "remembering scary things"
   tsa11 = "wanting to yell and break things"
   tsa12 = "crying"
   tsa13 = "get scared suddenly and don^t know why"
   tsa14 = "getting mad and can^t calm down"
   tsa15 = "feeling dizzy"
   tsa16 = "wanting to yell at people"
   tsa17 = "wanting to hurt yourself"
   tsa18 = "wanting to hurt other people"
   tsa19 = "feeling scared of men"
   tsa20 = "feeling scared of women"
   tsa21 = "wash yourself because feel dirty inside"
   tsa22 = "feeling stupid or bad"
   tsa23 = "feel like you did something wrong"
   tsa24 = "feeling like things aren^t real"
   tsa25 = "forget things/can^t remember things"
   tsa26 = "feeling like you^re not in your body"
   tsa27 = "feeling nervous or jumpy inside"
   tsa28 = "feeling afraid"
   tsa29 = "dwell on bad event that happened to you"
   tsa30 = "getting into fights"
   tsa31 = "feeling mean"
   tsa32 = "pretending you^re somewhere else"
   tsa33 = "being afraid of the dark"
   tsa34 = "worrying about things"
   tsa35 = "feeling like nobody likes you"
   tsa36 = "remember things don^t want to remember"
   tsa37 = "your mind going empty or blank"
   tsa38 = "feeling like you hate people"
   tsa39 = "trying not to have any feelings"
   tsa40 = "feeling mad"
   tsa41 = "feeling afraid someone will kill you"
   tsa42 = "wish bad things had never happened"
   tsa43 = "wanting to kill yourself"
   tsa44 = "daydreaming"
   tsa45 = "interviewer initials"
   tsa46 = "date of interview" ;

FORMAT
   tsa46 DATE9. ;
      

LENGTH
   visit 3                  tsa1 3                   tsa2 3                
   tsa3 3                   tsa4 3                   tsa5 3                
   tsa6 3                   tsa7 3                   tsa8 3                
   tsa9 3                   tsa10 3                  tsa11 3               
   tsa12 3                  tsa13 3                  tsa14 3               
   tsa15 3                  tsa16 3                  tsa17 3               
   tsa18 3                  tsa19 3                  tsa20 3               
   tsa21 3                  tsa22 3                  tsa23 3               
   tsa24 3                  tsa25 3                  tsa26 3               
   tsa27 3                  tsa28 3                  tsa29 3               
   tsa30 3                  tsa31 3                  tsa32 3               
   tsa33 3                  tsa34 3                  tsa35 3               
   tsa36 3                  tsa37 3                  tsa38 3               
   tsa39 3                  tsa40 3                  tsa41 3               
   tsa42 3                  tsa43 3                  tsa44 3 ;

         

RUN ;
