/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\tsis1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = tsis1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=82;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   AA_RAW  12-13            DEP_RAW  14-15           AI_RAW  16-17         
   IE_RAW  18-19            DA_RAW  20-21            DIS_RAW  22-23        
   DSB_RAW  24-25           ISR_RAW  26-27           TRB_RAW  28-29        
   SC_RAW  30-31            ATR_RAW  32-33           RL_RAW  34-35         
   INC_RAW  36-37           CRITICAL  38-39          ATR_T  40-42          
   RL_T  43-44              INC_T  45-46             AA_T  47-48           
   DEP_T  49-50             AI_T  51-52              IE_T  53-54           
   DA_T  55-56              DIS_T  57-58             SC_T  59-60           
   DSB_T  61-63             ISR_T  64-65             TRB_T  66-68          
   AGE_YRS  69-70           GENDER  71               DATEVIEW DATE11.      
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   AA_RAW = "ANXIOUS AROUSAL RAW SCORE"
   DEP_RAW = "DEPRESSION RAW SCORE"
   AI_RAW = "ANGER/IRRITABILITY RAW SCORE"
   IE_RAW = "INTRUSIVE EXPERIENCES RAW SCORE"
   DA_RAW = "DEFENSIVE AVOIDANT RAW SCORE"
   DIS_RAW = "DISSOCIATION RAW SCORE"
   DSB_RAW = "DYSFUNCTIONAL SEXUAL BEHAVIOR RAW SCORE"
   ISR_RAW = "IMPAIRED SELF-REFERENCE RAW SCORE"
   TRB_RAW = "TENSION REDUCTION BEHAVIOR RAW SCORE"
   SC_RAW = "SEXUAL CONCERNS RAW SCORE"
   ATR_RAW = "ATYPICAL RESPONSE RAW SCORE"
   RL_RAW = "RESPONSE LEVEL RAW SCORE"
   INC_RAW = "INCONSISTENT RESPONSE RAW SCORE"
   CRITICAL = "NUMBER OF CRITIAL ITEMS WITH NONZERO RESPONSES"
   ATR_T = "ATYPICAL RESPONSE T-SCORE"
   RL_T = "RESPONSE LEVEL T-SCORE"
   INC_T = "INCONSISTENT RESPONSE T-SCORE"
   AA_T = "ANXIOUS AROUSAL T-SCORE"
   DEP_T = "DEPRESSION T-SCORE"
   AI_T = "ANGER/IRRITABILITY T-SCORE"
   IE_T = "INTRUSIVE EXPERIENCES T-SCORE"
   DA_T = "DEFENSIVE AVOIDANT T-SCORE"
   DIS_T = "DISSOCIATION T-SCORE"
   SC_T = "SEXUAL CONCERNS T-SCORE"
   DSB_T = "DYSFUNCTIONAL SEXUAL BEHAVIOR T-SCORE"
   ISR_T = "IMPAIRED SELF-REFERENCE T-SCORE"
   TRB_T = "TENSION REDUCTION BEHAVIOR T-SCORE"
   AGE_YRS = "AGE OF RESPONDENT AT TIME OF INTERVIEW"
   GENDER = "GENDER OF RESPONDENT: 1 = MALE, 2 = FEMALE"
   DATEVIEW = "DATE OF THE AGE 18 INTERVIEW" ;

FORMAT
   DATEVIEW DATE9. ;
   

LENGTH
   VISIT 3                  AA_RAW 3                 DEP_RAW 3             
   AI_RAW 3                 IE_RAW 3                 DA_RAW 3              
   DIS_RAW 3                DSB_RAW 3                ISR_RAW 3             
   TRB_RAW 3                SC_RAW 3                 ATR_RAW 3             
   RL_RAW 3                 INC_RAW 3                CRITICAL 3            
   ATR_T 3                  RL_T 3                   INC_T 3               
   AA_T 3                   DEP_T 3                  AI_T 3                
   IE_T 3                   DA_T 3                   DIS_T 3               
   SC_T 3                   DSB_T 3                  ISR_T 3               
   TRB_T 3                  AGE_YRS 3                GENDER 3 ;

        

RUN ;
