/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\vica0404.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = vica0404 ;

DATA library.&dataset ;
INFILE datafile LRECL=107;
INPUT
   id $ 1-7                 center $ 8-9             visit  10             
   vica1  11                vica1a1  12              vica1a2  13           
   vica1b1  14              vica1b2  15              vica1c1  16           
   vica1c2  17              vica2  18                vica2a1  19           
   vica2a2  20              vica2b1  21              vica2b2  22           
   vica2c1  23              vica2c2  24              vica3  25             
   vica3a1  26              vica3a2  27              vica3b1  28           
   vica3b2  29              vica3c1  30              vica3c2  31           
   vica4  32                vica4a1  33              vica4a2  34           
   vica4b1  35              vica4b2  36              vica4c1  37           
   vica4c2  38              vica5  39                vica5a1  40           
   vica5a2  41              vica5b1  42              vica5b2  43           
   vica5c1  44              vica5c2  45              vica6  46             
   vica6a1  47              vica6a2  48              vica6b1  49           
   vica6b2  50              vica6c1  51              vica6c2  52           
   vica7  53                vica7a1  54              vica7a2  55           
   vica7b1  56              vica7b2  57              vica7c1  58           
   vica7c2  59              vica8  60                vica8a1  61           
   vica8a2  62              vica8b1  63              vica8b2  64           
   vica8c1  65              vica8c2  66              vica9  67             
   vica9a1  68              vica9a2  69              vica9b1  70           
   vica9b2  71              vica9c1  72              vica9c2  73           
   vica9d1  74              vica9d2  75              vica10  76            
   vica10a1  77             vica10a2  78             vica10b1  79          
   vica10b2  80             vica10c1  81             vica10c2  82          
   vica10d1  83             vica10d2  84             vica11  85            
   vica11a1  86             vica11a2  87             vica11b1  88          
   vica11b2  89             vica11c1  90             vica11c2  91          
   vica11d1  92             vica11d2  93             vica12 $ 94-96        
   vica13 DATE11.         ;                       

LABEL
   id = "longscan subject id"
   center = "field center"
   visit = "visit number"
   vica1 = "mo as child:physical abuse"
   vica1a1 = "mo as child:phys abuse by parent figure"
   vica1a2 = "mo as child:upset-phys abuse by par fig"
   vica1b1 = "mo as child:phys abuse by other family"
   vica1b2 = "mo as child:upset-phys abuse by oth fam"
   vica1c1 = "mo as child:phys abuse by non-family"
   vica1c2 = "mo as child:upset-phys abuse by non-fam"
   vica2 = "mo as child:excessive punishment"
   vica2a1 = "mo as child:excess punish by parent fig"
   vica2a2 = "mo as child:upset-excess punish-par fig"
   vica2b1 = "mo as child:excess punish by oth family"
   vica2b2 = "mo as child:upset-excess punish-oth fam"
   vica2c1 = "mo as child:excess punish by non-fam"
   vica2c2 = "mo as child:upset-excess punish-non-fam"
   vica3 = "mo < 13:fondled"
   vica3a1 = "mo < 13:fondled by parent fig"
   vica3a2 = "mo < 13:upset-fondled-par fig"
   vica3b1 = "mo < 13:fondled by oth family"
   vica3b2 = "mo < 13:upset-fondled-oth fam"
   vica3c1 = "mo < 13:fondled by non-fam"
   vica3c2 = "mo < 13:upset-fondled-non-fam"
   vica4 = "mo < 13:forced fondle"
   vica4a1 = "mo < 13:forced fondle by parent fig"
   vica4a2 = "mo < 13:upset-forced fondle-par fig"
   vica4b1 = "mo < 13:forced fondle by oth family"
   vica4b2 = "mo < 13:upset-forced fondle-oth fam"
   vica4c1 = "mo < 13:forced fondle by non-fam"
   vica4c2 = "mo < 13:upset-forced fondle-non-fam"
   vica5 = "mo < 13:sex intercrs"
   vica5a1 = "mo < 13:sex intercrs by parent fig"
   vica5a2 = "mo < 13:upset-sex intercrs-par fig"
   vica5b1 = "mo < 13:sex intercrs by oth family"
   vica5b2 = "mo < 13:upset-sex intercrs-oth fam"
   vica5c1 = "mo < 13:sex intercrs by non-fam"
   vica5c2 = "mo < 13:upset-sex intercrs-non-fam"
   vica6 = "mo as teen:fondled"
   vica6a1 = "mo as teen:fondled by parent fig"
   vica6a2 = "mo as teen:upset-fondled-par fig"
   vica6b1 = "mo as teen:fondled by oth family"
   vica6b2 = "mo as teen:upset-fondled-oth fam"
   vica6c1 = "mo as teen:fondled by non-fam"
   vica6c2 = "mo as teen:upset-fondled-non-fam"
   vica7 = "mo as teen:forced fondle"
   vica7a1 = "mo as teen:forced fondle by parent fig"
   vica7a2 = "mo as teen:upset-forced fondle-par fig"
   vica7b1 = "mo as teen:forced fondle by oth family"
   vica7b2 = "mo as teen:upset-forced fondle-oth fam"
   vica7c1 = "mo as teen:forced fondle by non-fam"
   vica7c2 = "mo as teen:upset-forced fondle-non-fam"
   vica8 = "mo as teen:sex intercrs"
   vica8a1 = "mo as teen:sex intercrs by parent fig"
   vica8a2 = "mo as teen:upset-sex intercrs-par fig"
   vica8b1 = "mo as teen:sex intercrs by oth family"
   vica8b2 = "mo as teen:upset-sex intercrs-oth fam"
   vica8c1 = "mo as teen:sex intercrs by non-fam"
   vica8c2 = "mo as teen:upset-sex intercrs-non-fam"
   vica9 = "mo as adult:beaten"
   vica9a1 = "mo as adult:beaten by husband"
   vica9a2 = "mo as adult:upset-beaten-husband"
   vica9b1 = "mo as adult:beaten by oth family"
   vica9b2 = "mo as adult:upset-beaten-oth fam"
   vica9c1 = "mo as adult:beaten by acquaint"
   vica9c2 = "mo as adult:upset-beaten-acquaint"
   vica9d1 = "mo as adult:beaten by stranger"
   vica9d2 = "mo as adult:upset-beaten-stranger"
   vica10 = "mo as adult:oth phys abuse"
   vica10a1 = "mo as adult:oth phys abuse by husband"
   vica10a2 = "mo as adult:upset-oth phys abuse-husband"
   vica10b1 = "mo as adult:oth phys abuse by oth family"
   vica10b2 = "mo as adult:upset-oth phys abuse-oth fam"
   vica10c1 = "mo as adult:oth phys abuse by acquaint"
   vica10c2 = "mo as adult:upset-oth phy abuse-acquaint"
   vica10d1 = "mo as adult:oth phys abuse by stranger"
   vica10d2 = "mo as adult:upset-oth phy abuse-stranger"
   vica11 = "mo as adult:sex assault"
   vica11a1 = "mo as adult:sex assault by husband"
   vica11a2 = "mo as adult:upset-sex assault-husband"
   vica11b1 = "mo as adult:sex assault by oth family"
   vica11b2 = "mo as adult:upset-sex assault-oth fam"
   vica11c1 = "mo as adult:sex assault by acquaint"
   vica11c2 = "mo as adult:upset-sex assault-acquaint"
   vica11d1 = "mo as adult:sex assault by stranger"
   vica11d2 = "mo as adult:upset-sex assault-stranger"
   vica12 = "interviewer initials"
   vica13 = "date on interview" ;

FORMAT
   vica13 DATE9. ;
     

LENGTH
   visit 3                  vica1 3                  vica1a1 3             
   vica1a2 3                vica1b1 3                vica1b2 3             
   vica1c1 3                vica1c2 3                vica2 3               
   vica2a1 3                vica2a2 3                vica2b1 3             
   vica2b2 3                vica2c1 3                vica2c2 3             
   vica3 3                  vica3a1 3                vica3a2 3             
   vica3b1 3                vica3b2 3                vica3c1 3             
   vica3c2 3                vica4 3                  vica4a1 3             
   vica4a2 3                vica4b1 3                vica4b2 3             
   vica4c1 3                vica4c2 3                vica5 3               
   vica5a1 3                vica5a2 3                vica5b1 3             
   vica5b2 3                vica5c1 3                vica5c2 3             
   vica6 3                  vica6a1 3                vica6a2 3             
   vica6b1 3                vica6b2 3                vica6c1 3             
   vica6c2 3                vica7 3                  vica7a1 3             
   vica7a2 3                vica7b1 3                vica7b2 3             
   vica7c1 3                vica7c2 3                vica8 3               
   vica8a1 3                vica8a2 3                vica8b1 3             
   vica8b2 3                vica8c1 3                vica8c2 3             
   vica9 3                  vica9a1 3                vica9a2 3             
   vica9b1 3                vica9b2 3                vica9c1 3             
   vica9c2 3                vica9d1 3                vica9d2 3             
   vica10 3                 vica10a1 3               vica10a2 3            
   vica10b1 3               vica10b2 3               vica10c1 3            
   vica10c2 3               vica10d1 3               vica10d2 3            
   vica11 3                 vica11a1 3               vica11a2 3            
   vica11b1 3               vica11b2 3               vica11c1 3            
   vica11c2 3               vica11d1 3               vica11d2 3 ;

      

RUN ;
