/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\vnla0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = vnla0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=54;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   vsaa1  11                vsaa2  12                vsaa3  13             
   vsaa4 $ 14               vsaa5  15                vsaa6  16             
   vsaa7  17                vsaa8  18                vsaa9  19             
   vsaa10  20               vsaa11 $ 21              vsaa12 $ 22           
   vsaa13  23               vsaa14  24               vsaa15  25            
   vsab1  26                vsab2  27                vsab3  28             
   vsab4  29                vsab5  30                vsab6  31             
   vsab7  32                vsab8 $ 33               vsab9  34             
   vsab10  35               vsab11  36               vsab12  37            
   vsab13  38               vsab14  39               vsab15  40            
   vsab16 $ 41-43           vsab17 DATE11.         ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   vsaa1 = "how is child at dressing self"
   vsaa2 = "how well does child tend to toilet needs"
   vsaa3 = "how well does child use silverware"
   vsaa4 = "how well does child handle restaurant"
   vsaa5 = "how does child deal with strangers"
   vsaa6 = "how is child at crossing street alone"
   vsaa7 = "how aware is child of day of week"
   vsaa8 = "how well does child tell time"
   vsaa9 = "how well does child know value of coins"
   vsaa10 = "has child saved money and bought item"
   vsaa11 = "how would child use phone in emergency"
   vsaa12 = "can child make long distance calls"
   vsaa13 = "can child use stove or microwave"
   vsaa14 = "most complicated dish child can prepare"
   vsaa15 = "what rooms does child regularly clean"
   vsab1 = "how child expresses feelings"
   vsab2 = "how child handles hurt feelings/told no"
   vsab3 = "who are child^s friends"
   vsab4 = "does child have a best friend"
   vsab5 = "how is child at sharing with friends"
   vsab6 = "what games does child play/follow rules"
   vsab7 = "does child play card/board/video games"
   vsab8 = "does child watch/listen news/documentary"
   vsab9 = "how does child behave with other people"
   vsab10 = "what child does when finish conversation"
   vsab11 = "how child respond to hints to end talk"
   vsab12 = "does child apologize w/out being told"
   vsab13 = "how child acts if falsely blames another"
   vsab14 = "does child consider feelings of others"
   vsab15 = "whose birthdays does child remember"
   vsab16 = "interviewer initials"
   vsab17 = "date of interview" ;

FORMAT
   vsab17 DATE9. ;
     

LENGTH
   visit 3                  vsaa1 3                  vsaa2 3               
   vsaa3 3                  vsaa5 3                  vsaa6 3               
   vsaa7 3                  vsaa8 3                  vsaa9 3               
   vsaa10 3                 vsaa13 3                 vsaa14 3              
   vsaa15 3                 vsab1 3                  vsab2 3               
   vsab3 3                  vsab4 3                  vsab5 3               
   vsab6 3                  vsab7 3                  vsab9 3               
   vsab10 3                 vsab11 3                 vsab12 3              
   vsab13 3                 vsab14 3                 vsab15 3 ;

        

RUN ;
