/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\vnls0603.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = vnls0603 ;

DATA library.&dataset ;
INFILE datafile LRECL=45;
INPUT
   id $ 1-7                 visit  8                 center $ 9-10         
   vsa_age  11-26           vsa_mth  27-29           dl_raw  30-31         
   so_raw  32-33            dleqraw  34-36           soeqraw  37-39        
   dl_std  40-42            so_std  43-45          ;                       

LABEL
   id = "longscan subject id"
   visit = "visit number"
   center = "field center"
   vsa_age = "child age at vineland admin (years)"
   vsa_mth = "child age at vineland admin (months)"
   dl_raw = "vineland:daily living skills raw score"
   so_raw = "vineland:socialization raw score"
   dleqraw = "vineland:daily lv skills equated raw sc"
   soeqraw = "vineland:socialization  equated raw sco"
   dl_std = "vineland:daily living skills standard sc"
   so_std = "vineland:socialization standard score" ;

LENGTH
   visit 3                  vsa_mth 4                dl_raw 3              
   so_raw 3                 dleqraw 4                soeqraw 4             
   dl_std 4                 so_std 4 ;

        

RUN ;
