/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\vsbs0807.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = vsbs0807 ;

DATA library.&dataset ;
INFILE datafile LRECL=59;
INPUT
   ID $ 1-7                 CENTER $ 8-9             VISIT  10-11          
   VSCB02 DATE11.           AGE_YR  23-24            AGE_MO  25-27         
   SORAW_6  28-29           DLRAW_6  30-31           DLRAW_13  32-33       
   SORAW_13  34-35          DLEQI_6  36-38           DLEQI_13  39-41       
   SOEQI_6  42-44           SOEQI_13  45-47          SOSTD_6  48-50        
   DLSTD_6  51-53           SOSTD_13  54-56          DLSTD_13  57-59       
 ;                       

LABEL
   ID = "LONGSCAN SUBJECT ID"
   CENTER = "FIELD CENTER"
   VISIT = "VISIT NUMBER"
   VSCB02 = "Date of interview"
   AGE_YR = "CHILD AGE IN YEARS"
   AGE_MO = "CHILD AGE IN MONTHS"
   SORAW_6 = "SOCIALIZATION RAW SCORE V6-12"
   DLRAW_6 = "DAILY LIVING RAW SCORE V6-12"
   DLRAW_13 = "DAILY LIVING RAW SCORE V13-18"
   SORAW_13 = "SOCIALIZATION RAW SCORE V13-18"
   DLEQI_6 = "DAILY LIVING EQUATED RAW SCORE V6-12"
   DLEQI_13 = "DAILY LIVING EQUATED RAW SCORE V13-18"
   SOEQI_6 = "SOCIALIZATION EQUATED RAW SCORE V6-12"
   SOEQI_13 = "SOCIALIZATION EQUATED RAW SCORE V13-18"
   SOSTD_6 = "SOCIALIZATION STANDARD SCORE V6-12"
   DLSTD_6 = "DAILY LIVING STANDARD SCORE V6-12"
   SOSTD_13 = "SOCIALIZATION STANDARD SCORE V13-18"
   DLSTD_13 = "DAILY LIVING STANDARD SCORE V13-18" ;

FORMAT
   VSCB02 DATE9.          ;
                     

LENGTH
   VISIT 3                  AGE_YR 3                 AGE_MO 4              
   SORAW_6 3                DLRAW_6 3                DLRAW_13 3            
   SORAW_13 3               DLEQI_6 4                DLEQI_13 4            
   SOEQI_6 4                SOEQI_13 4               SOSTD_6 4             
   DLSTD_6 4                SOSTD_13 4               DLSTD_13 4 ;

      

RUN ;
