/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\vscb0807.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = vscb0807 ;

DATA library.&dataset ;
INFILE datafile LRECL=72;
INPUT
   ID $ 1-7                 CENTER $ 8-9             VISIT  10-11          
   VSCBZ1 $ 12              VSCBA5 $ 13              VSCBA15 $ 14          
   VSCBA16 $ 15             VSCBA17 $ 16             VSCBA23 $ 17          
   VSCBA24 $ 18             VSCBB10 $ 19             VSCBB11 $ 20          
   VSCBB12 $ 21             VSCB01 $ 22-24           VSCBA1  25            
   VSCBA2  26               VSCBA3  27               VSCBA4  28            
   VSCBA6  29               VSCBA7  30               VSCBA8  31            
   VSCBA9  32               VSCBA10  33              VSCBA11  34           
   VSCBA12  35              VSCBA13  36              VSCBA14  37           
   VSCBA18  38              VSCBA19  39              VSCBA20  40           
   VSCBA21  41              VSCBA22  42              VSCBB1  43            
   VSCBB2  44               VSCBB3  45               VSCBB4  46            
   VSCBB5  47               VSCBB6  48               VSCBB7  49            
   VSCBB8  50               VSCBB9  51               VSCBB13  52           
   VSCBB14  53              VSCBB15  54              VSCBB16  55           
   VSCBB17  56              VSCBB18  57              VSCBB19  58           
   VSCBB20  59              VSCBB21  60              VSCBB22  61           
   VSCB02 DATE11.         ;                       

LABEL
   ID = "LONGSCAN SUBJECT ID"
   CENTER = "FIELD CENTER"
   VISIT = "VISIT NUMBER"
   VSCBZ1 = "VSCBZ1"
   VSCBA5 = "How well does child handle restaurant"
   VSCBA15 = "How is child at being on time for job"
   VSCBA16 = "Lets supervisor know if can't be there"
   VSCBA17 = "Pays attention to time limits for breaks"
   VSCBA23 = "How does child use a telephone by self"
   VSCBA24 = "Long distance/dir. assistance by self"
   VSCBB10 = "What child watches/listens on TV/radio"
   VSCBB11 = "Does child watch/listen practical info"
   VSCBB12 = "Does child watch/listen to news"
   VSCB01 = "Interviewer initials"
   VSCBA1 = "How is child at dressing self"
   VSCBA2 = "Who takes care of child's clothes"
   VSCBA3 = "How well does child tend to toilet needs"
   VSCBA4 = "How well does child use silverware"
   VSCBA6 = "Does child need help w/stove/microwave"
   VSCBA7 = "What foods does child prepare by self"
   VSCBA8 = "What rooms does child regularly clean"
   VSCBA9 = "What household maintenance does child do"
   VSCBA10 = "How well does child count change"
   VSCBA11 = "How well does child know value of coins"
   VSCBA12 = "Has child saved money and bought item"
   VSCBA13 = "What does child do to earn money"
   VSCBA14 = "How well does child manage checking acct"
   VSCBA18 = "How well does child deal with strangers"
   VSCBA19 = "How is child at going places alone"
   VSCBA20 = "How well does child know full date"
   VSCBA21 = "How well does child know day of week"
   VSCBA22 = "How well does child tell time"
   VSCBB1 = "How child lets people know feelings"
   VSCBB2 = "How child handles hurt feelings/told no"
   VSCBB3 = "Who are child's friends"
   VSCBB4 = "Does child have a best friend"
   VSCBB5 = "How is child at sharing with friends"
   VSCBB6 = "What activities child does with friends"
   VSCBB7 = "Has child gone out on a date"
   VSCBB8 = "What games does child play/follow rules"
   VSCBB9 = "Does child play card/board/video games"
   VSCBB13 = "How are child's table manners"
   VSCBB14 = "What does s/he say when introduced"
   VSCBB15 = "What child does when finish conversation"
   VSCBB16 = "How child respond to hints to end talk"
   VSCBB17 = "Does child consider feelings of others"
   VSCBB18 = "Does child apologize w/out being told"
   VSCBB19 = "How child acts if falsely blames another"
   VSCBB20 = "How is child at keeping secrets"
   VSCBB21 = "Whose birthdays does child remember"
   VSCBB22 = "Does child repay money s/he borrows"
   VSCB02 = "Date of interview" ;

FORMAT
   VSCB02 DATE9. ;
     

LENGTH
   VISIT 3                  VSCBA1 3                 VSCBA2 3              
   VSCBA3 3                 VSCBA4 3                 VSCBA6 3              
   VSCBA7 3                 VSCBA8 3                 VSCBA9 3              
   VSCBA10 3                VSCBA11 3                VSCBA12 3             
   VSCBA13 3                VSCBA14 3                VSCBA18 3             
   VSCBA19 3                VSCBA20 3                VSCBA21 3             
   VSCBA22 3                VSCBB1 3                 VSCBB2 3              
   VSCBB3 3                 VSCBB4 3                 VSCBB5 3              
   VSCBB6 3                 VSCBB7 3                 VSCBB8 3              
   VSCBB9 3                 VSCBB13 3                VSCBB14 3             
   VSCBB15 3                VSCBB16 3                VSCBB17 3             
   VSCBB18 3                VSCBB19 3                VSCBB20 3             
   VSCBB21 3                VSCBB22 3 ;

       

RUN ;
