/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ydea1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ydea1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=81;
INPUT
   CENTER $ 1-2             ID $ 3-9                 YDEA17 $ 10           
   YDEA18 $ 11              YDEA21 $ 12              YDEA25 $ 13-15        
   VISIT  16-17             YDEA1  18                YDEA1A  19            
   YDEA1B  20               YDEA1A1  21              YDEA2  22             
   YDEA3  23                YDEA4A  24               YDEA4B  25            
   YDEA4C  26               YDEA4D  27               YDEA4E  28            
   YDEA4F  29               YDEA4G  30               YDEA4H  31            
   YDEA4I  32               YDEA4J  33               YDEA4K  34            
   YDEA4L  35               YDEA4M  36               YDEA4N  37            
   YDEA4O  38               YDEA5  39                YDEA6  40             
   YDEA7  41                YDEA8  42-43             YDEA9  44             
   YDEA11  45-46            YDEA12  47-48            YDEA13  49            
   YDEA14  50               YDEA15  51               YDEA16  52            
   YDEA18A  53              YDEA19  54               YDEA20  55            
   YDEA21A  56              YDEA22  57               YDEA23  58            
   YDEA24  59               YDEA10 DATE11.           YDEA26 DATE11.        
 ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   YDEA17 = "Kind of work s/he did"
   YDEA18 = "Kind of company s/he work for"
   YDEA21 = "Kind of compnay/place s/he work for"
   YDEA25 = "Interviewer Initials"
   VISIT = "VISIT NUMBER"
   YDEA1 = "Currently living with parent"
   YDEA1A = "Where are you living now"
   YDEA1B = "Do you live with a spouse/partner"
   YDEA1A1 = "Wher living/Code for other"
   YDEA2 = "Last yr/ married /living with a partner"
   YDEA3 = "What is your current legal status"
   YDEA4A = "Ethnic origin/Black/African-American"
   YDEA4B = "Ethnic origin/White"
   YDEA4C = "Ethnic origin/Latino/Hispanic/L.American"
   YDEA4D = "Ethnic origin/Asian Indian/South Indian"
   YDEA4E = "Ethnic origin/Chinese"
   YDEA4F = "Ethnic origin/Filipino"
   YDEA4G = "Ethnic origin/Japanese"
   YDEA4H = "Ethnic origin/Korean"
   YDEA4I = "Ethnic origin/Vietnamese"
   YDEA4J = "Ethnic origin/Other Asian"
   YDEA4K = "Ethnic origin/Native Amercian/A.Indian"
   YDEA4L = "Ethnic origin/Inuit/Eskimo"
   YDEA4M = "Ethnic origin/Hawaiain"
   YDEA4N = "Ethnic origin/Pacific Islander"
   YDEA4O = "Ethnic origin/Other"
   YDEA5 = "Last yr/ did you attend school"
   YDEA6 = "Are you currently going to school"
   YDEA7 = "Have you dropped out of school"
   YDEA8 = "Highest grade you passed/compl. in schl"
   YDEA9 = "Gender of partner"
   YDEA11 = "Him/her-how old"
   YDEA12 = "Highest grade partner pasd/compl.in schl"
   YDEA13 = "Did s/he get high school diploma/GED"
   YDEA14 = "Othr educational degree since high schl"
   YDEA15 = "Descrpt his/her currnt employment status"
   YDEA16 = "S/he been employed in last six months"
   YDEA18A = "Employment Code"
   YDEA19 = "Does s/he have more than one job"
   YDEA20 = "Kind of work s/he do on main job"
   YDEA21A = "Employment Code"
   YDEA22 = "Amt money householed takes in each week"
   YDEA23 = "# people dependent on this income"
   YDEA24 = "# rooms in entire home"
   YDEA10 = "Date of his/her birth"
   YDEA26 = "Date of interview" ;

FORMAT
   YDEA10 DATE9.            YDEA26 DATE9. ;
     

LENGTH
   VISIT 3                  YDEA1 3                  YDEA1A 3              
   YDEA1B 3                 YDEA1A1 3                YDEA2 3               
   YDEA3 3                  YDEA4A 3                 YDEA4B 3              
   YDEA4C 3                 YDEA4D 3                 YDEA4E 3              
   YDEA4F 3                 YDEA4G 3                 YDEA4H 3              
   YDEA4I 3                 YDEA4J 3                 YDEA4K 3              
   YDEA4L 3                 YDEA4M 3                 YDEA4N 3              
   YDEA4O 3                 YDEA5 3                  YDEA6 3               
   YDEA7 3                  YDEA8 3                  YDEA9 3               
   YDEA11 3                 YDEA12 3                 YDEA13 3              
   YDEA14 3                 YDEA15 3                 YDEA16 3              
   YDEA18A 3                YDEA19 3                 YDEA20 3              
   YDEA21A 3                YDEA22 3                 YDEA23 3              
   YDEA24 3 ;

        

RUN ;
