/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ydeb1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ydeb1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=91;
INPUT
   CENTER $ 1-2             ID $ 3-9                 YDEB31 $ 10-12        
   VISIT  13-14             YDEB1  15                YDEB2  16             
   YDEB3  17                YDEB5  18                YDEB6  19             
   YDEB7  20                YDEB8  21-22             YDEB9  23             
   YDEB10  24               YDEB11  25               YDEB12  26            
   YDEB13  27               YDEB14  28               YDEB15  29            
   YDEB16  30               YDEB17  31               YDEB19  32-33         
   YDEB20  34-35            YDEB21  36               YDEB22  37            
   YDEB23  38               YDEB24  39               YDEB25  40            
   YDEB26  41-42            YDEB27  43-44            YDEB28  45            
   YDEB29  46-47            YDEB30  48-49            YDEB10A  50           
   YDEB11A  51              YDEB1A  52               YDEB1A1  53-54        
   YDEB4A  55               YDEB4B  56               YDEB4C  57            
   YDEB4D  58               YDEB4E  59               YDEB4F  60            
   YDEB4G  61               YDEB4H  62               YDEB4I  63            
   YDEB4J  64               YDEB4K  65               YDEB4L  66            
   YDEB4M  67               YDEB4N  68               YDEB4O  69            
   YDEB18 DATE11.           YDEB32 DATE11.         ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   YDEB31 = "Interviewer Initials"
   VISIT = "VISIT NUMBER"
   YDEB1 = "Currently living with parent"
   YDEB2 = "Do you live with a spouse/partner"
   YDEB3 = "Current legal marital status"
   YDEB5 = "Are you currently going to school"
   YDEB6 = "Last yr/ did you attend school"
   YDEB7 = "Have you dropped out of school"
   YDEB8 = "Highest grade you passed/compl. in schl"
   YDEB9 = "Did you receive high school diploma/GED"
   YDEB10 = "Othr educational degree since high schl"
   YDEB11 = "Typical wk:# hrs spent working for pay"
   YDEB12 = "School wk:# hrs spent working for pay"
   YDEB13 = "Typ.wk/no schl:# hrs working for pay"
   YDEB14 = "Do you have more than one job"
   YDEB15 = "How satisfied are you wth current job"
   YDEB16 = "How much job cause stress and tension"
   YDEB17 = "Gender of partner"
   YDEB19 = "Him/her-how old"
   YDEB20 = "Highest grade partner pasd/compl.in schl"
   YDEB21 = "Did s/he get high school diploma/GED"
   YDEB22 = "Othr educational degree since high schl"
   YDEB23 = "Descrpt his/her currnt employment status"
   YDEB24 = "S/he been employed in last six months"
   YDEB25 = "Does s/he have more than one job"
   YDEB26 = "Amt money householed takes in each week"
   YDEB27 = "# people dependent on this income"
   YDEB28 = "Do you live in house/apartment"
   YDEB29 = "# rooms in entire house/apartment"
   YDEB30 = "How many people live there"
   YDEB10A = "How prepared for steady job"
   YDEB11A = "Why aren't you working now"
   YDEB1A = "Where are you living now"
   YDEB1A1 = "Code for where living-other"
   YDEB4A = "Ethnic origin/Black/African-American"
   YDEB4B = "Ethnic origin/White"
   YDEB4C = "Ethnic origin/Latino/Hispanic/L.American"
   YDEB4D = "Ethnic origin/Asian Indian/South Indian"
   YDEB4E = "Ethnic origin/Chinese"
   YDEB4F = "Ethnic origin/Filipino"
   YDEB4G = "Ethnic origin/Japanese"
   YDEB4H = "Ethnic origin/Korean"
   YDEB4I = "Ethnic origin/Vietnamese"
   YDEB4J = "Ethnic origin/Other Asian"
   YDEB4K = "Ethnic origin/Native Amercian/A.Indian"
   YDEB4L = "Ethnic origin/Inuit/Eskimo"
   YDEB4M = "Ethnic origin/Hawaiain"
   YDEB4N = "Ethnic origin/Pacific Islander"
   YDEB4O = "Ethnic origin/Other"
   YDEB18 = "Date of his/her birth"
   YDEB32 = "Date of interview" ;

FORMAT
   YDEB18 DATE9.            YDEB32 DATE9. ;
     

LENGTH
   VISIT 3                  YDEB1 3                  YDEB2 3               
   YDEB3 3                  YDEB5 3                  YDEB6 3               
   YDEB7 3                  YDEB8 3                  YDEB9 3               
   YDEB10 3                 YDEB11 3                 YDEB12 3              
   YDEB13 3                 YDEB14 3                 YDEB15 3              
   YDEB16 3                 YDEB17 3                 YDEB19 3              
   YDEB20 3                 YDEB21 3                 YDEB22 3              
   YDEB23 3                 YDEB24 3                 YDEB25 3              
   YDEB26 3                 YDEB27 3                 YDEB28 3              
   YDEB29 3                 YDEB30 3                 YDEB10A 3             
   YDEB11A 3                YDEB1A 3                 YDEB1A1 3             
   YDEB4A 3                 YDEB4B 3                 YDEB4C 3              
   YDEB4D 3                 YDEB4E 3                 YDEB4F 3              
   YDEB4G 3                 YDEB4H 3                 YDEB4I 3              
   YDEB4J 3                 YDEB4K 3                 YDEB4L 3              
   YDEB4M 3                 YDEB4N 3                 YDEB4O 3 ;

        

RUN ;
