/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\yfra1002.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = yfra1002 ;

DATA library.&dataset ;
INFILE datafile LRECL=22;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   YFRA1  12                YFRA2  13                YFRA3  14             
   YFRA4  15                YFRA5  16                YFRA6  17             
   YFRA7  18                YFRA8  19                YFRA9  20             
   YFRA10  21               YFRA11  22             ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   YFRA1 = "Time each day to talk with my parents"
   YFRA2 = "We do certain things each morning"
   YFRA3 = "Regular routine each day after school"
   YFRA4 = "Sleep in the same place every night"
   YFRA5 = "Do homework at the same time each day/night"
   YFRA6 = "Do certain things each might at bedtime"
   YFRA7 = "Go to bed at the same time every night"
   YFRA8 = "Family eats dinner same time every night"
   YFRA9 = "Some of our family eat together once/day"
   YFRA10 = "Family members check in with each other"
   YFRA11 = "Parents discipline each time out of line" ;

LENGTH
   VISIT 3                  YFRA1 3                  YFRA2 3               
   YFRA3 3                  YFRA4 3                  YFRA5 3               
   YFRA6 3                  YFRA7 3                  YFRA8 3               
   YFRA9 3                  YFRA10 3                 YFRA11 3 ;

        

RUN ;
