/* This SAS program was automatically generated by Stat/Transfer ver.12.0.63.0712 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\temp\LONGSCAN_SRI_2014\ypva1201.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\temp\longscan_sri_2014\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = ypva1201 ;

DATA library.&dataset ;
INFILE datafile LRECL=105;
INPUT
   CENTER $ 1-2             ID $ 3-9                 VISIT  10-11          
   YPVA1  12                YPVA2A  13               YPVA2B  14            
   YPVA2C  15               YPVA2D  16               YPVA3  17             
   YPVA4A  18               YPVA4B  19               YPVA4C  20            
   YPVA4D  21               YPVA4E  22               YPVA4F  23            
   YPVA4G  24               YPVA4H  25               YPVA4I  26            
   YPVA4J  27               YPVA4K  28               YPVA4L  29            
   YPVA5A1  30              YPVA5A2  31              YPVA5A3  32           
   YPVA5A4  33              YPVA5B1  34              YPVA5B2  35           
   YPVA5B3  36              YPVA5B4  37              YPVA5C1  38           
   YPVA5C2  39              YPVA5C3  40              YPVA5C4  41           
   YPVA5D1  42              YPVA5D2  43              YPVA5D3  44           
   YPVA5D4  45              YPVA5E1  46              YPVA5E2  47           
   YPVA5E3  48              YPVA5E4  49              YPVA5F1  50           
   YPVA5F2  51              YPVA5F3  52              YPVA5F4  53           
   YPVA5G1  54              YPVA5G2  55              YPVA5G3  56           
   YPVA5G4  57              YPVA5H1  58              YPVA5H2  59           
   YPVA5H3  60              YPVA5H4  61              YPVA5I1  62           
   YPVA5I2  63              YPVA5I3  64              YPVA5I4  65           
   YPVA5J1  66              YPVA5J2  67              YPVA5J3  68           
   YPVA5J4  69              YPVA5K1  70              YPVA5K2  71           
   YPVA5K3  72              YPVA5K4  73              YPVA6  74             
   YPVA7A  75               YPVA7B  76               YPVA7C  77            
   YPVA7D  78               YPVA7E  79               YPVA7F  80            
   YPVA7G  81               YPVA8A1  82              YPVA8A2  83           
   YPVA8A3  84              YPVA8A4  85              YPVA8B1  86           
   YPVA8B2  87              YPVA8B3  88              YPVA8B4  89           
   YPVA8C1  90              YPVA8C2  91              YPVA8C3  92           
   YPVA8C4  93              YPVA8D1  94              YPVA8D2  95           
   YPVA8D3  96              YPVA8D4  97              YPVA8E1  98           
   YPVA8E2  99              YPVA8E3  100             YPVA8E4  101          
   YPVA8F1  102             YPVA8F2  103             YPVA8F3  104          
   YPVA8F4  105           ;                       

LABEL
   CENTER = "FIELD CENTER"
   ID = "LONGSCAN SUBJECT ID"
   VISIT = "VISIT NUMBER"
   YPVA1 = "Pick on you-how often"
   YPVA2A = "Pick on you-brother/sister/kid"
   YPVA2B = "Pick on you-boyfriend/girlfriend"
   YPVA2C = "Pick on you-other kid outside household"
   YPVA2D = "Pick on you-a group of kids"
   YPVA3 = "Another kid-how often physic. hurt you"
   YPVA4A = "Another kid-bruised you"
   YPVA4B = "Another kid-cut/scraped you"
   YPVA4C = "Another kid-knocked you out"
   YPVA4D = "Another kid-caused injury to teeth etc"
   YPVA4E = "Another kid-put smthing over your mouth"
   YPVA4F = "Another kid-tried to drown you"
   YPVA4G = "Another kid-broken one of your bones"
   YPVA4H = "Another kid-burned you"
   YPVA4I = "Another kid-shot you"
   YPVA4J = "Another kid-caused other injuries"
   YPVA4K = "Another kid-done something harmful"
   YPVA4L = "Another kid-other injury"
   YPVA5A1 = "Bruised you-brother/sister/kid"
   YPVA5A2 = "Bruised you-boyfriend/girlfriend"
   YPVA5A3 = "Bruised you-other kid outside household"
   YPVA5A4 = "Bruised you-a group of kids"
   YPVA5B1 = "Cut/scraped-brother/sister/kid"
   YPVA5B2 = "Cut/scraped-boyfriend/girlfriend"
   YPVA5B3 = "Cut/scraped-other kid outside household"
   YPVA5B4 = "Cut/scraped-a group of kids"
   YPVA5C1 = "Knocked you out-brother/sister/kid"
   YPVA5C2 = "Knocked you out-boyfriend/girlfriend"
   YPVA5C3 = "Knocked you out-other kid outside household"
   YPVA5C4 = "Knocked you out-a group of kids"
   YPVA5D1 = "Injury to teeth-brother/sister/kid"
   YPVA5D2 = "Injury to teeth-boyfriend/girlfriend"
   YPVA5D3 = "Injury to teeth-other kid outside h/hold"
   YPVA5D4 = "Injury to teeth-a group of kids"
   YPVA5E1 = "Something over mouth-brother/sister/kid"
   YPVA5E2 = "Something over mouth-boyfriend/girlfriend"
   YPVA5E3 = "Something over mouth-other kid outside h/hold"
   YPVA5E4 = "Something over mouth-a group of kids"
   YPVA5F1 = "Drown you-brother/sister/kid"
   YPVA5F2 = "Drown you-boyfriend/girlfriend"
   YPVA5F3 = "Drown you teeth-other kid outside h/hold"
   YPVA5F4 = "Drown you teeth-a group of kids"
   YPVA5G1 = "Broke bones-brother/sister/kid"
   YPVA5G2 = "Broke bones-boyfriend/girlfriend"
   YPVA5G3 = "Broke bones-other kid outside h/hold"
   YPVA5G4 = "Broke bones-a group of kids"
   YPVA5H1 = "Burned you-brother/sister/kid"
   YPVA5H2 = "Burned you-boyfriend/girlfriend"
   YPVA5H3 = "Burned you-other kid outside h/hold"
   YPVA5H4 = "Burned you teeth-a group of kids"
   YPVA5I1 = "Shot you-brother/sister/kid"
   YPVA5I2 = "Shot you-boyfriend/girlfriend"
   YPVA5I3 = "Shot you-other kid outside h/hold"
   YPVA5I4 = "Shot you-a group of kids"
   YPVA5J1 = "Other injuries-brother/sister/kid"
   YPVA5J2 = "Other injuries-boyfriend/girlfriend"
   YPVA5J3 = "Other injuries-other kid outside h/hold"
   YPVA5J4 = "Other injuries-a group of kids"
   YPVA5K1 = "Something harmful-brother/sister/kid"
   YPVA5K2 = "Something harmful-boyfriend/girlfriend"
   YPVA5K3 = "Somthng harmful-other kid outside h/hold"
   YPVA5K4 = "Something harmful-a group of kids"
   YPVA6 = "How often another kid done sexual things"
   YPVA7A = "Another kid-looked at your private parts"
   YPVA7B = "Another kid-touched/felt private parts"
   YPVA7C = "Another kid-hurt private parts"
   YPVA7D = "Another kid-kissed mouth/private parts"
   YPVA7E = "Another kid-put penis etc in private parts"
   YPVA7F = "Another kid-done other sexual thing"
   YPVA7G = "Another kid-other"
   YPVA8A1 = "Looked at priv.parts-brother/sister/kid"
   YPVA8A2 = "Looked at priv.parts-boyfriend/girlfriend"
   YPVA8A3 = "Looked at priv.parts-othr kid out h/hold"
   YPVA8A4 = "Looked at priv.parts-a group of kids"
   YPVA8B1 = "Touched priv.parts-brother/sister/kid"
   YPVA8B2 = "Touched priv.parts-boyfriend/girlfriend"
   YPVA8B3 = "Touched priv.parts-othr kid out h/hold"
   YPVA8B4 = "Touched priv.parts-a group of kids"
   YPVA8C1 = "Hurt priv.parts-brother/sister/kid"
   YPVA8C2 = "Hurt priv.parts-boyfriend/girlfriend"
   YPVA8C3 = "Hurt priv.parts-othr kid out h/hold"
   YPVA8C4 = "Hurt priv.parts-a group of kids"
   YPVA8D1 = "Kissed priv.parts-brother/sister/kid"
   YPVA8D2 = "Kissed priv.parts-boyfriend/girlfriend"
   YPVA8D3 = "Kissed priv.parts-othr kid out h/hold"
   YPVA8D4 = "Kissed  priv.parts-a group of kids"
   YPVA8E1 = "Penis in priv.parts-brother/sister/kid"
   YPVA8E2 = "Penis in priv.parts-boyfriend/girlfriend"
   YPVA8E3 = "Penis in priv.parts-othr kid out h/hold"
   YPVA8E4 = "Penis inpriv.parts-a group of kids"
   YPVA8F1 = "Other sexual thing-brother/sister/kid"
   YPVA8F2 = "Other sexual thing-boyfriend/girlfriend"
   YPVA8F3 = "Other sexual thing-othr kid out h/hold"
   YPVA8F4 = "Other sexual thing-a group of kids" ;

LENGTH
   VISIT 3                  YPVA1 3                  YPVA2A 3              
   YPVA2B 3                 YPVA2C 3                 YPVA2D 3              
   YPVA3 3                  YPVA4A 3                 YPVA4B 3              
   YPVA4C 3                 YPVA4D 3                 YPVA4E 3              
   YPVA4F 3                 YPVA4G 3                 YPVA4H 3              
   YPVA4I 3                 YPVA4J 3                 YPVA4K 3              
   YPVA4L 3                 YPVA5A1 3                YPVA5A2 3             
   YPVA5A3 3                YPVA5A4 3                YPVA5B1 3             
   YPVA5B2 3                YPVA5B3 3                YPVA5B4 3             
   YPVA5C1 3                YPVA5C2 3                YPVA5C3 3             
   YPVA5C4 3                YPVA5D1 3                YPVA5D2 3             
   YPVA5D3 3                YPVA5D4 3                YPVA5E1 3             
   YPVA5E2 3                YPVA5E3 3                YPVA5E4 3             
   YPVA5F1 3                YPVA5F2 3                YPVA5F3 3             
   YPVA5F4 3                YPVA5G1 3                YPVA5G2 3             
   YPVA5G3 3                YPVA5G4 3                YPVA5H1 3             
   YPVA5H2 3                YPVA5H3 3                YPVA5H4 3             
   YPVA5I1 3                YPVA5I2 3                YPVA5I3 3             
   YPVA5I4 3                YPVA5J1 3                YPVA5J2 3             
   YPVA5J3 3                YPVA5J4 3                YPVA5K1 3             
   YPVA5K2 3                YPVA5K3 3                YPVA5K4 3             
   YPVA6 3                  YPVA7A 3                 YPVA7B 3              
   YPVA7C 3                 YPVA7D 3                 YPVA7E 3              
   YPVA7F 3                 YPVA7G 3                 YPVA8A1 3             
   YPVA8A2 3                YPVA8A3 3                YPVA8A4 3             
   YPVA8B1 3                YPVA8B2 3                YPVA8B3 3             
   YPVA8B4 3                YPVA8C1 3                YPVA8C2 3             
   YPVA8C3 3                YPVA8C4 3                YPVA8D1 3             
   YPVA8D2 3                YPVA8D3 3                YPVA8D4 3             
   YPVA8E1 3                YPVA8E2 3                YPVA8E3 3             
   YPVA8E4 3                YPVA8F1 3                YPVA8F2 3             
   YPVA8F3 3                YPVA8F4 3 ;

       

RUN ;
